### ISSUE TITLE
Integration test failing for rubyspec

### ISSUE THREAD

**Issue by telyn** [mbj/mutant#1001]
I see the following error when running the integration tests on my PR #1000 . I've run them locally using the master branch and also see them, so it's not specific to my branch.

```
1) Mutant on ruby corpus rubyspec does not fail on mutation generation
     Failure/Error: node = Parser::CurrentRuby.parse(path.read)
     
     Parser::SyntaxError:
       literal contains escape sequences incompatible with UTF-8
```

**Comment by mbj** [comment]
This is standard rusting from rubyspec. Typically we add excludes in `spec/integrations.yml`. These are files rubyspec has `parser` does not support in the configuration we use it.

**Comment by mbj** [comment]
Feel free to separately PR a fix. And yes I know your CLA is pending. Trying to catch up with my work.

**Comment by mbj** [comment]
@telyn As you've updated the references in your PR I'll close this issue.
