### ISSUE TITLE
Create a Website for this Repo

### ISSUE THREAD

**Issue by xdvrx1** [mbj/mutant#1017]
Hi there. 

Is there a website for this repo? 

Because if you don't have, well, this repo can simply be turned into a website right away. Others will discover this project in that website.

Steps:
1. Go to Settings and look for `GitHub Pages`, scroll down. That's almost at the bottom.

2. You will see there: `Branch:none`, so you should change that to `master` because you have a `README.md` file in the master repo. This will be your page. Click `Save` first.

3. Then click `Choose a theme`, you select a predefined theme of your site.

4. Visit your site now! The URL will be `https://mbj.github.io/mutant`. 

If you were amazed by that, simply read the documentation about GitHub Pages.

**Comment by mbj** [comment]
@xdvrx1 I'm well aware of this feature, and I had the website online for a longer time, BUT: What would doing this get me?

Just another thing to maintain, the information conveyable to another person stays the same.

**Comment by xdvrx1** [comment]
Nope, when you edit your `README.md`, that's also editing your page. The good thing  is that you have your full-pledged website.

Anyways, I am just suggesting. You can ignore and close this issue anytime.

**Comment by mbj** [comment]
> The good thing is that you have your full-pledged website.

Thats what I say with duplication. Why should I want "another place" for the readme? Maybe lets re-parse the question:

* What is the benefit of having a full-pledged website for mutant that *just* renders the README people could also read under `https://github.com/mbj/mutant` ?

Unless that website would add some information, I do not see why I should add it. I'm open for your thoughts here.

**Comment by xdvrx1** [comment]
Using the `github.io` domain, in the case of GitHub Pages, or your own domain, will add another location on the web, so that your projects will be discovered not only in GitHub, but elsewhere. Take note, `github.com` is different from `github.io`. Sometimes your project will be discovered from `github.io` not in `github.com`. 

So, that adds the visibility of your project only in `github.com` but elsewhere. Also, when you render that `README.md` file as web page, they can only focus on the content, not on the source code, if that is what they are looking for, particularly for full documentation.  

Why do you think the `Bootstrap` framework has its own domain despite the fact the project is hosted on `github.com`?

**Comment by mbj** [comment]
I'm not sure if adding duplicate content to another location in the web that just renders my `README.md` is a win at this point.

Once I've more content, I'd consider it. Still as mutant is commercial software and I also need an automated web based sign up that would very likely be hosted outside of github pages.

I'll close this issue for the moment as I do not think its actionable for me in the suggested path. Feel free to continue to discuss if you think I missed a nuance in my reasoning.
