### ISSUE TITLE
Drop `git` in gemspec

### ISSUE THREAD

**Issue by utkarsh2102** [mbj/mutant#1052]
Hi @mbj,

Thanks for your lovely work on this! ❤️ 

However, whilst trying to maintain this in Debian, we found that mutant relies on `git` to produce a list of files.
Using `git` in gemspec is a bit troublesome and it's best to not use them!

More about this can be found here: https://docs.rubocop.org/rubocop-packaging/cops_packaging.html#packaginggemspecgit

If you agree with this, I'll be very happy to raise a PR for this! 😄

**Comment by mbj** [comment]
@utkarsh2102 I'm happy to change it. No need to PR on yourself. I like the reasoning of the change.

I suspect this also applies to all of mutant downstream dependencies I maintain.

**Comment by mbj** [comment]
@utkarsh2102 curious where is mutant packaged in debian? I never heard about it. Archlinux user here ;)

**Comment by utkarsh2102** [comment]
@mbj, hello 👋🏻 

> No need to PR on yourself. I like the reasoning of the change.

Great, thank you! ❤️ 
There are some other small things like bumping RuboCop version and using rubocop-packaging that I'd be willing to introduce and so on. In case you want a PR for that, I'd be happy to do that! Let me know!

> curious where is mutant packaged in debian? I never heard about it. Archlinux user here ;)

Haha, I use Arch ("BTW"), too 😄 
However, I am a Debian core developer and I maintain a bunch of Ruby stuff in Debian. I already maintain `anima`, `concord`, `unparser`, `adamantium`, `morpher`, `procto`, `abstract_types`, etc there already (so you can also `apt install` these things ;)) and so when I was packaging `mutant` for Debian, I faced these problems (using `git` and so on) and was  therefore asking here 😄 
Hopefully, in the next weeks, we'll also have `mutant-rspec`, `mutant`, and `ice_nine` as well! 💯 

Additionally, I really want to thank you for all your work and willing to help us maintain that! ❤️

**Comment by mbj** [comment]
> There are some other small things like bumping RuboCop version and using rubocop-packaging that I'd be willing to introduce and so on. In case you want a PR for that, I'd be happy to do that! Let me know!

you are fine to PR anything you wish. But please be aware that mutant, as its NOT opensource anymore (cannot afford to maintain it under opensource economy) requires you to sign an ICA.

Please contact me in private for details. Find my email in the gemspec.

**Comment by utkarsh2102** [comment]
Hey,

> For all the gems I'm the "primary" author I've released the following versions that all do not rely on git anymore:
> 
>    concord-0.1.6 (first release in 6 years!)
>   anima-0.3.2
>    unparser-0.4.9
>    mutant-0.9.12

Wow, you're the best! 🔥 
Thank you! 🤗 

> For the other gems I recommend you open the issue at the respective repositories. These gems are typically very small hence still work but their CI setup will have bitrotted. I've to talk to each maintainer on what their preferences are to stetup CI.

Ah, sure thing! I'll do this as and when I re-work on those packages! Thanks again! ^.^

> Please contact me in private for details. Find my email in the gemspec.

Emailed! \o/

> BTW morpher is basically EOL. Mutant::Transform is the next version of this. May be extracted to a separate gem in the future.

Ah, okay! Thanks for letting me know!
