### ISSUE TITLE
Multiple cover expressions

### ISSUE THREAD

**Issue by andrzejkrzywda** [mbj/mutant#1075]
It would be nice to have a way of declaring tests with multiple cover expressions (or allow one expression to cover multiple namespaces).

My use case:

I have a test suite which covers one big module. During refactoring, I'm extracting new modules/namespaces. The tests remain the same, but now they test 2 modules. 

Currently, for mutant to work with this, I need to make both modules to be part of the same parent namespace. This is OK for many situation, but it's not always the namespace configuration that I want.

**Comment by mbj** [comment]
@andrzejkrzywda I've merged support for multiple cover expressions in #1076, with the intention to release this as `0.10.1` later this day. Can you check it out from master meanwhile?

**Comment by andrzejkrzywda** [comment]
Works perfectly, thank you!

**Comment by mbj** [comment]
@andrzejkrzywda Released as `mutant{,-minitest,-rspec}-0.10.1`.
