### ISSUE TITLE
Support multiple coverage expressions in mutant-rspec

### ISSUE THREAD

**Issue by dgollahon** [mbj/mutant#1079]
Support was recently added for `mutant-minitest` but per [this comment](https://github.com/mbj/mutant/pull/1076#issue-512312493)
> Rspec integrations could also be adapted. Feel free to open an issue for this in the future.

 `mutant-rspec` does not yet have support. This is a feature my team would use and I think it will be helpful to have this issue open to track it.

**Comment by mbj** [comment]
@dgollahon I'm happy to add it to rspec also, but we need to specify it in some way. In rspec there are multiple sources for coverage expressions and the interactions with these sources need a definition.

I'll put up a PR and we can discuss tit than.

**Comment by dgollahon** [comment]
What would be the next steps for this? Can I help guide this along? I have a workaround for this that is a dirty hack and have had to use it for a few more niche cases recently. It would be helpful to have first class support.

**Comment by mbj** [comment]
@dgollahon The step is basically:

Make `Mutant::Test` instances, derived from rspec examples inside the `Mutant::Integration::Rspec`: Emit more `Mutant::Expression` in `Mutant::Test#expressions`. 

Currently it only emits a one element array. And that one element is chosen from either the rspec description, or the (single) overwrite `mutant: ` in the rspec metadata.

This logic would have to change to also allow arrays in the metadata, and possibly concatenate the rspec description.
