### ISSUE TITLE
Add an ability to specify path to the configuration file

### ISSUE THREAD

**Issue by pawelpacana** [mbj/mutant#1171]
At the moment mutant looks for configuration file in predefined place. This is a good convention and a default. 

In a repository hosting several components, each one in need of such configuration, it would require as many configuration files. With shared configuration for components that's a lot of symlinking. It would be nice to have a CLI flag to specify single, shared config file to avoid that.

**Comment by mbj** [comment]
@pawelpacana While I support this initiative, I wounder if in `rails_event_store` you'll end up in actually defining a global config file, since mutant now (since `v0.10.24` that was just released) has the ability to define the matcher configuration in the config file natively: https://github.com/mbj/mutant/blob/master/docs/configuration.md#matcher.

I suspect the amount of sharable config is quite small.

I wounder if in addition to having the option to define the configuration file location, we need to support *multiple* config files. Or config file inheritance.

**Comment by pawelpacana** [comment]
> I wounder if in addition to having the option to define the configuration file location, we need to support multiple config files. Or config file inheritance.

The only reason I currently use config files is inability to pass `coverage_criteria` via flags. Everything else was fine so far with flags and I did not feel the need for any change.

With `matcher` in config perhaps I could transform my setup if this flags vs. config file asymmetry continues. I do not see the need for mutiple config files nor inheritance.

**Comment by mbj** [comment]
The challenge is  that the `coverage_criteria` will be supported per subject, and that would not fit within the CLI flags without becoming a source of headache for the user.

Curious why you do not want a project specific config file, and want to configure everything via flags?

**Comment by pawelpacana** [comment]
> Curious why you do not want a project specific config file, and want to configure everything via flags?

Simply put — presence and sunk cost of existing tooling

**Comment by mbj** [comment]
> presence and sunk cost of existing tooling

Can you elaborate? From my perspective, RES would still use the Makefile to trigger mutant, but not have to re-implement a mutant config file format anymore.

Do I miss something?

BTW: I support making the config file location configurable anyway, this is a sibling discussion at this point.

**Comment by pawelpacana** [comment]
> From my perspective, RES would still use the Makefile to trigger mutant, but not have to re-implement a mutant config file format anymore.

I need to evaluate that option

**Comment by pawelpacana** [comment]
This is no longer an issue for me, closing.

**Comment by mbj** [comment]
I still think that feature should exist, so re-opening it.
