### ISSUE TITLE
Minitest integration riddle

### ISSUE THREAD

**Issue by pawelpacana** [mbj/mutant#1206]
I have a subject covered by 4 tests. I'm pretty sure they're selected when mutating given subject:

```
Matcher:         #<Mutant::Matcher::Config subjects: [Ordering::OnSubmitOrder]>
Integration:     minitest
Jobs:            8
Includes:        ["test"]
Requires:        ["./config/environment"]
Subjects:        2
Total-Tests:     26
Selected-Tests:  4

...

Ordering::OnSubmitOrder#initialize:/Users/pawelpacana/Code/cqrs-es-sample-with-res/ordering/lib/ordering/on_submit_order.rb:5
- minitest:Ordering::SubmitOrderTest#test_order_is_submitted
- minitest:Ordering::SubmitOrderTest#test_already_created_order_could_not_be_created_again
- minitest:Ordering::SubmitOrderTest#test_could_not_create_order_where_customer_is_not_given
- minitest:Ordering::SubmitOrderTest#test_expired_order_could_not_be_created
```

Mutant would suggest there's an uncovered code. Yet when I perform manual code change similar to one that mutant does, corresponding tests fail as I'd expect. Any obvious reasons what I'm doing wrong?
* log from run and manual mutation: https://gist.github.com/pawelpacana/09a08ecb469da41b5a5215d6ccf79377
* reproduction on: https://github.com/RailsEventStore/cqrs-es-sample-with-res/commit/344e352fa022a3edf8eebda1a5bbea4c326959a1

Context:
* mutant-minitest 0.10.25
* rails 6.1.0
* minitest 5.14.2

**Comment by pawelpacana** [comment]
Worth mentioning where subject is initialized: https://github.com/RailsEventStore/cqrs-es-sample-with-res/blob/master/config/initializers/rails_event_store.rb#L29

**Comment by mbj** [comment]
@pawelpacana Given your comment about initialization of the objects, before I look into it in detail: Its very likely that the code that is being mutated is NOT executed during the **test runs**.

It appears that the only instances you make for this objects are created *during boot* of the tests. **outside** of the code that is executed by each test example.

This is a very important distinction: Tests should verify the semantics of the code that is executed *during test runs*, not of code that is executed *during loading of the tests*.

When you manually run the tests, the failures you detect may be on boot of the test environment, but NOT during test execution. So when the mutation gets inserted: The mutation would affect code that is only run during boot: Hence no effect can be measured.

**Comment by pawelpacana** [comment]
> It appears that the only instances you make for this objects are created during boot of the tests. outside of the code that is executed by each test example.

That was the case, thank you for spotting the issue.

**Comment by mbj** [comment]
@pawelpacana Yeah, so in fact your tests where NOT executing the code, they where testing state inherited from your test setup!

**Comment by pawelpacana** [comment]
They were using fake implementation of a dependency for entire test session, I can agree with that and that was kind of expected.
