### ISSUE TITLE
Mutant can alter method visibility

### ISSUE THREAD

**Issue by dgollahon** [mbj/mutant#1242]
I am in the habit of creating tools where I have something like `Client` and `Client::Fake` and I initialize one or the other in my app depending on the environment. I also have a test which asserts that these two classes share the same public instance methods and same method signatures. This test fails when running mutant and has to be manually excluded because of a situation like this:

```ruby
class Client
  def do_work
    # ...
    some_helper
    # ...
  end
  
  private
  
  def some_helper
     # do some heavy lifting
  end
end
```  

```ruby
class Client
  class Fake
    def do_work
      # no-op
    end
  end
end
```  

My unit tests pass when I assert that they have the same public methods and the same signatures but under mutation testing `some_helper` can become public and then lead to a neutral failure. Asserting things based on method visibility might be slightly niche, but it does seem like something mutant should not change if it can help it.

**Comment by mbj** [comment]
Yeah, I think visibility "reconstruction" needs to handle subclasses better.

**Comment by dgollahon** [comment]
I think the subclass aspect is probably irrelevant, it was just my motivating example. Could probably narrow the reproduction to something a lot smaller but haven't messed with it further.

**Comment by mbj** [comment]
@dgollahon AFAIK mutant has code to restore original visibility, but this is pure memory. could be I dropped it once as overwrites used to inherit the parents visibility at some point.

**Comment by dgollahon** [comment]
```ruby
```

**Comment by dgollahon** [comment]
(sorry, fat-fingered the issue close)

Given this code:

```ruby
class Test
  private

  def foo
  end
end
```

this test will pass under RSpec

```ruby
RSpec.describe Test do
  it 'has no public methods' do
    expect(described_class.public_instance_methods(false)).to eql([])
  end
end
```

but not mutant:

```
[killfork]   1) Test has no public methods
[killfork]      Failure/Error: expect(described_class.public_instance_methods(false)).to eql([])
[killfork]
[killfork]        expected: []
[killfork]             got: [:foo]
[killfork]
[killfork]        (compared using eql?)
[killfork]
[killfork]        Diff:
[killfork]        @@ -1 +1 @@
[killfork]        -[]
[killfork]        +[:foo]
```

**Comment by dgollahon** [comment]
Just as a note, ran into this again today. Not sure if this is easy to fix or not but would be helpful to have it work properly. Do we have utilities that track visibility or would solving this require invasive changes?

**Comment by mbj** [comment]
> Just as a note, ran into this again today. Not sure if this is easy to fix or not but would be helpful to have it work properly. Do we have utilities that track visibility or would solving this require invasive changes?

I have a local fix, but it was hard to get stable cross all supported ruby versions. I'll try again in the next window. Thanks for raising its importance.
