### ISSUE TITLE
mutating a module included method breaks require

### ISSUE THREAD

**Issue by HashNotAdam** [mbj/mutant#1248]
I have a module included in a class. The module includes both class and instance method and is formatted like:
```ruby
def self.included(klass)
  klass.extend(ClassMethods)
end

module ClassMethods
  # class methods here
end

# instance methods here
```

While mutant is correctly mutating the `included` method, changes there cause a crash in spec_helper since requiring the class will fail.

**Comment by mbj** [comment]
@HashNotAdam I'm not 100% sure this falls within mutants domain. Does it crash mutant itself? Can I get a stacktrace?
