### ISSUE TITLE
Setup issue, all mutants stay alive

### ISSUE THREAD

**Issue by nukdown** [mbj/mutant#1264]
I'm trying to integrate Mutant to Diaspora Network, but i freeze on this issue that describe bellow.

All mutants just stay alive, regardless of selected class. See the result of exec mutant in image on this link:
[https://media.discordapp.net/attachments/809958886269386782/893008096618749972/Captura_de_tela_de_2021-09-30_02-22-47.png?width=674&height=451](url)

Anyone can reproduce it yourself in this repository:

https://github.com/nukdown/diaspora-suite-test-evaluation/tree/mutant

1. Clone repository
2. Make sure you are in branch -> Mutant.
3. Run in CLI:
 3.1 bundle install
 3.2 bin/rake assets:generate_error_pages
 3.3 RAILS_ENV="test" bin/rake db:create db:migrate
 3.4 RAILS_ENV="test" bundle exec mutant run --require ./config/environment.rb --use rspec -- 'AdminsController'

**Comment by vaporyhumo** [comment]
Are your tests following the adequate naming patterns? I.e:
```ruby
RSpec.describe SomeClass do
  describe '#some_instance_method' do
    # examples
  end

  describe '.some_class_method' do
    # examples
  end
end
```

**Comment by nukdown** [comment]
No, just without "Rspec."
> ```ruby
> describe SomeClass do
>   describe '#some_instance_method' do
>     # examples
>   end
> 
>   describe '.some_class_method' do
>     # examples
>   end
> end
> ```

**Comment by vaporyhumo** [comment]
Oh that shouldn't be important, just the descriptions themselves. I'll look the repo for anything I can find to suggest.

**Comment by vaporyhumo** [comment]
I think you might be missing an * at the end of the subject. Try with `AdminsController*` instead.
>    3.4 RAILS_ENV="test" bundle exec mutant run --require ./config/environment.rb --use rspec -- 'AdminsController'

**Comment by nukdown** [comment]
I do it but not solve, after it i just reinstall gems manualy, when i did exec again magically works. Thanks for help @vaporyhumo 
> I think you might be missing an * at the end of the subject. Try with `AdminsController*` instead.

**Comment by mbj** [comment]
@vaporyhumo thanks for your input here!
