### ISSUE TITLE
Do not mutate sorbet's `T.must`

### ISSUE THREAD

**Issue by vaporyhumo** [mbj/mutant#1287]
I've found that there are cases where it is extremely difficult to satisfy the mutation that deletes sorounding `T.must(arg) -> arg`.

This is particullary the case for overloaded methods, for example `Array#[]`.

Since `sorbet` would already report any redundant call to `T.must` I think it would be really cool to avoid mutating it. 

I think this is probably the case for some of `T.must`'s siblings too: `T.let`, `T.cast`, `T.assert_type!`, `T.bind`; I'll create issues for them if that's the case.

Should I provide a little repo?

**Comment by mbj** [comment]
@vaporyhumo I agree and: I think we should generally forbid to recurse into `T` constants. This is very easy to patch. Wanna take a stab at it?

**Comment by mbj** [comment]
Super high level:

Tests for mutation operators `meta/` directory.

Code: Find the emitter that handles send nodes, and prevent any mutation in case the receiver is the constant `T`.

```
bundle exec ruby-parse -e 'T.must'
```

to learn the AST involved.

**Comment by vaporyhumo** [comment]
I already started taking a look at this. For what I can see in the case of `T.must` which only receives one argument we should expect only the mutations for the argument to be emitted; no modification to the receiver `T` nor the message `.must`.

**Comment by vaporyhumo** [comment]
For what I can tell by now, only the `mutate_arguments` should run on case we have `T.must(...)`.

I tested with `T.must(a > b)` and the mutations am getting make sense to me. Should I try with a more contrived example? any suggestion on that?

I mean, I think I still intend to use the the fork for a few moments before submitting something. I'm beginning to get how mutations are done so I can maybe try for a while on some personal project.

👂 

```ruby
def normal_dispatch
  emit_naked_receiver
  emit_selector_replacement
  emit_selector_specific_mutations
  emit_argument_propagation
  emit_receiver_selector_mutations
  mutate_receiver
  mutate_arguments
end
```

**Comment by dgollahon** [comment]
> I'm assuming that the better place to identify if we are talking about a T.must() is on the Meta::Send class amirite? Something like meta.is_t_must?.

If it were me I'd probably do something like `meta.sorbet_receiver?` if the goal is just to skip mutating the `T.` statements by default. Then you could short-circuit in `dispatch` or `normal_dispatch` I think.

You may need to skip the `emit_singletons` (probably the entire dispatch?) if you don't want mutant to replace `T.whatever` with `nil`. I think you will also have a near-equivalent problem where mutant will generically delete your `T.whatever` statement so that may need special-casing if mutant shouldn't just strip sorbet's assertions. I assume this may be reasonable but @mbj will have better guidance and maybe it would make sense to keep some of those.

**Comment by vaporyhumo** [comment]
Hey @dgollahon 👋 Thanks for answering.

About this: 
> If it were me I'd probably do something like meta.sorbet_receiver? if the goal is just to skip mutating the T. statements by default. Then you could short-circuit in dispatch or normal_dispatch I think.

Totally right. Like the name and the short-circuit idea. 

I talket a little bit more with @mbj (thru discord) so he also gave me some more advise.

Thing is, there are still things to discover/decide. I think `T.must` is the easiest of the sorbet thingies to treat, but other methods might be complicated. I'm going to throw out my thoughts here just for the record. I'm glad to be corrected if I'm wrong about anything here.

`T.must`:
* Should always be kept as `T.must`. (no removing in whole or in part, i.e. `nil`, `must(...)`, etc.)
* Only takes one argument, which should be mutated in everyway a regular argument should. Removing the argument or making it nil will cause the method to fail so that should make most tests suites fail per se. Regular mutations are still useful, you might still want to consider changin a `#[]` for `#fetch` for instance. I think there *might* be some corner cases, but am not sure (for example, how different are `T.must(hash[index])` and `hash.fetch(index)`? ).

`T.let`:
* Should always be kept as `T.let`
* Takes two arguments
* The first argument should be mutated regularly (this might also lead to corner cases)
* The second argument is always a constant or a `T` method. Some mutations *are* useful here. For instance you might want to remove redundant namespace in a case like this:
```ruby
module SomeModule
  class SomeClass
  end

  var = T.let(some_nasty_method, SomeModule::SomeClass)
end
```

Will keep you updated on things as I discover them, I'm using my fork on a personal project so I can get real use examples. I will open a PR once I feel confident with the changes.

**Comment by mbj** [comment]
@vaporyhumo I recommend you do this increments (in separate PRs):

1. Ignore all mutations on `T.` via early exit.
2. Turn the early exit into a delegate to a sorbet specific mutation emitter accouting for sorbet API rules. Note that this can optentially re-use the sorbet API around that AST nodes so we do not have to re-interpret the AST.

1) actually gives us 80% of the value, very cheaply.
2) is something to explore iteratively.

**Comment by mbj** [comment]
@vaporyhumo this can be done now via user specific settings, see: #1341. I agree mutant should do this by default, but having user control is a step up.

**Comment by vaporyhumo** [comment]
hey @mbj I've been a little distant to the project, and sorbet too btw. I'll close the issue as you mention that this can already be accomplished. Thanks a lot for the work!

**Comment by mbj** [comment]
Yes this is "not" the final solution the real solution is to run sorbet post mutation to use its erroing as pointer to not remove the `T.must` and friends.

I mostly mentioned the generic AST filtering as an incremental improvement.

**Comment by mbj** [comment]
@vaporyhumo This is now supported via ignore patterns:

```
mutation:
  ignore_patterns:
  - 'send{receiver=const{name=T}}'
```
