### ISSUE TITLE
ruby2_keywords support

### ISSUE THREAD

**Issue by pawelpacana** [mbj/mutant#1293]
I have a following code with keyword argument delegation, that behaves differently in Ruby 2.7 vs. 3.0. That difference is well managed with `ruby2_keywords`:

```ruby
module Constructor
  def new(*)
    super.tap { |instance| instance.instance_variable_set(:@version, -1) }
  end

  # https://eregon.me/blog/2021/02/13/correct-delegation-in-ruby-2-27-3.html
  ruby2_keywords :new if respond_to?(:ruby2_keywords, true)
end
```

I have a sample code (https://github.com/pawelpacana/mutant-ruby2-keywords) with unit tests passing on both 2.7 and 3.0 MRI. When I run mutant on Ruby 2.7 that also passes. 

On Ruby 3.0 there's is a neutral failure:

```
Mutant environment:
Matcher:         #<Mutant::Matcher::Config subjects: [Constructor*]>
Integration:     minitest
Jobs:            8
Includes:        ["lib"]
Requires:        ["constructor"]
Subjects:        1
Total-Tests:     7
Selected-Tests:  7
Tests/Subject:   7.00 avg
Mutations:       27
Constructor#new:/Users/mostlyobvious/Code/mutant-ruby2-keywords/lib/constructor.rb:2
- minitest:ConstructorTest#test_allows_initializer_with_mixed_arguments
- minitest:ConstructorTest#test_allows_initializer_with_variable_keyword_arguments
- minitest:ConstructorTest#test_allows_default_initializer
- minitest:ConstructorTest#test_allows_initializer_with_arguments
- minitest:ConstructorTest#test_allows_initializer_with_variable_arguments
- minitest:ConstructorTest#test_allows_initializer_with_block
- minitest:ConstructorTest#test_allows_initializer_with_keyword_arguments
neutral:Constructor#new:/Users/mostlyobvious/Code/mutant-ruby2-keywords/lib/constructor.rb:2:30d4b
-----------------------
Killfork: #<Process::Status: pid 88770 exit 0>
Log messages (combined stderr and stdout):
[killfork] Run options:
[killfork]
[killfork] # Running:
[killfork]
[killfork]
[killfork]
[killfork] Finished in 0.000533s, 1876.1723 runs/s, 0.0000 assertions/s.
[killfork]
[killfork]   1) Error:
[killfork] ConstructorTest#test_allows_initializer_with_mixed_arguments:
[killfork] ArgumentError: missing keyword: :b
[killfork]     /Users/mostlyobvious/Code/mutant-ruby2-keywords/test/constructor_test.rb:93:in `initialize'
[killfork]     /Users/mostlyobvious/Code/mutant-ruby2-keywords/lib/constructor.rb:5:in `new'
[killfork]     /Users/mostlyobvious/Code/mutant-ruby2-keywords/lib/constructor.rb:5:in `new'
[killfork]     /Users/mostlyobvious/Code/mutant-ruby2-keywords/test/constructor_test.rb:100:in `test_allows_initializer_with_mixed_arguments'
[killfork]
[killfork] 1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
--- Neutral failure ---
Original code was inserted unmutated. And the test did NOT PASS.
Your tests do not pass initially or you found a bug in mutant / unparser.
Subject AST:
s(:def, :new,
  s(:args,
    s(:restarg)),
  s(:block,
    s(:send,
      s(:zsuper), :tap),
    s(:args,
      s(:procarg0,
        s(:arg, :instance))),
    s(:send,
      s(:lvar, :instance), :instance_variable_set,
      s(:sym, :@version),
      s(:int, -1))))
Unparsed Source:
def new(*)
  super.tap { |instance|
    instance.instance_variable_set(:@version, -1)
  }
end
-----------------------
Mutant environment:
Matcher:         #<Mutant::Matcher::Config subjects: [Constructor*]>
Integration:     minitest
Jobs:            8
Includes:        ["lib"]
Requires:        ["constructor"]
Subjects:        1
Total-Tests:     7
Selected-Tests:  7
Tests/Subject:   7.00 avg
Mutations:       27
Results:         27
Kills:           26
Alive:           1
Timeouts:        0
Runtime:         0.05s
Killtime:        0.03s
Overhead:        75.01%
Mutations/s:     499.22
Coverage:        96.30%
Uncovered mutations detected, exiting nonzero!
```

Such failure (`ArgumentError`) can be reproduced in units on MRI 3.0, if `ruby2_keywords :new if respond_to?(:ruby2_keywords, true)` line is removed.

What can be done here to have a passing mutant on MRI 3.0 in that situation?

**Comment by mbj** [comment]
My solution in the past was to remove `ruby2_keywords` ;) But thats not an option for a library that suppors 2.7 - 3.0.

I'm just back from a very good vacation (first one in years). Will give this some thought over the weekend.

**Comment by pawelpacana** [comment]
Just curious if you stumbled upon other options than `ruby2_keywords` removal

**Comment by mbj** [comment]
> Just curious, have you stumbled upon other options than ruby2_keywords removal already?

Do not write code that needs it?

Mutant works on 2.7-3.1 (up until today also including 2.6 which I just dropped as its EOL) nicely while also using keyword args. The few cases where it makes a different can easily be refactored away.

**Comment by mbj** [comment]
>  But thats not an option for a library that suppors 2.7 - 3.0.

I was mistaken there, this very code base is an example on how to do it.

**Comment by pawelpacana** [comment]
Since you have experience with that, I'd love to know how would you refactor the code from the issue to not use `ruby2_keywords`. 

Which is a minimal sample derived from a code I didn't initially want to post and primary reason of submitting this issue:

- https://github.com/RailsEventStore/rails_event_store/blob/be89cf85a50461b2a4df5835e5b80c2672267b9f/aggregate_root/lib/aggregate_root.rb#L34-L41

- https://github.com/RailsEventStore/rails_event_store/blob/be89cf85a50461b2a4df5835e5b80c2672267b9f/aggregate_root/spec/aggregate_root_spec.rb#L270-L364

**Comment by pawelpacana** [comment]
Closing, does not seem needed with RUBY 2.6 EOLed.

**Comment by mbj** [comment]
IMO best option ;)
