### ISSUE TITLE
Shouldn't the license be issues by you and not Mike Perham? ;)

### ISSUE THREAD

**Issue by mensfeld** [mbj/mutant#1297]
lol
https://github.com/mbj/mutant/blob/dad8181e7f6fc111d50afae7048dd4735ae65ea0/LICENSE#L8

**Comment by mbj** [comment]
gah, I scouted this.

**Comment by mbj** [comment]
stupidity on my side, I had his okay to use this license and I substituded every occurence, but only missed scream text :P Funny how many corpo lawyers did not see it either. fixed in: https://github.com/mbj/mutant/pull/1298 thx.
