### ISSUE TITLE
Mutant does not handle `...` argument forwarding correctly

### ISSUE THREAD

**Issue by dgollahon** [mbj/mutant#1316]
If you have a method such as:

```ruby
def foo(...)
  bar(...)
end
```

mutant will mutate like this:

```diff
- def foo(...)
+ def foo
```

which raises a `SyntaxError` because `bar(...)` tries to incorrectly reference `...` and results in

> Killing the mutation resulted in an integration error.

I believe mutant needs to either never delete `...` or check if it is used in the scope below.

I am using ruby 2.7.5, mutant-rspec 0.11.4, and parser 3.1.0.0

**Comment by mbj** [comment]
correct, I think mutant should not delete `...` easy fix,expect it this weekend.

**Comment by mbj** [comment]
@dgollahon this is fixed in release v0.11.6.
