### ISSUE TITLE
Add --seed flag (or similar mechanism)

### ISSUE THREAD

**Issue by dgollahon** [mbj/mutant#1375]
I would like to be able to fine-tune parallelism and other factors to see how it affects mutations/s. Unfortunately each run is extremely variable and I _believe_ it is due to RSpec ordering. I haven't confirmed that but I suspect it's the major cause. It would be very helpful to have an option to reuse a specific seed.

**Comment by mbj** [comment]
@dgollahon You can now use `--integration-argument=--seed --integration-argument=0` to set rspec arguments controlling the seed.
