### ISSUE TITLE
Improve `ignore_patterns` behavior for method removals

### ISSUE THREAD

**Issue by dgollahon** [mbj/mutant#1398]
Motivating example: there are some cases where I pass an object to an API I don't control. In those cases I sometimes freeze the object first and generally am happy to do "unnecessary" freezing of objects. In some cases it's easy to write a test where the result of something is frozen but in cases where the object is passed into a different method and the result is a new object it's not possible to assert that something received `#freeze` or is frozen.

It might be reasonable to generally not try to delete `#freeze` (although you lose the ability to detect redundant freezes if you care about that) or  (what I want with this issue) make the ignore pattern system support ignoring these. I tried adding:

```yml
mutation:
  ignore_patterns:
    - send{selector=freeze}
```

to my `.mutant.yml` but it did not prevent the removal mutation from applying.

Here is a trivial/contrived example but it shows the problem:

```ruby
class MutantExample
  def demo
    {}.freeze
  end
end
```

```ruby
RSpec.describe MutantExample do
  it 'is a hash' do
    expect(described_class.new.demo).to be_a(Hash)
  end
end
```

Result of running mutant is one alive mutation:

```diff
 def demo
-  {}.freeze
+  {}
 end
 ```

**Comment by mbj** [comment]
@dgollahon I think this was fixed via #1409.
