### ISSUE TITLE
Puts itself into infinite loop

### ISSUE THREAD

**Issue by moonglum** [mbj/mutant#147]
Mutant is caught in an infinite loop when mutating `Ashikawa::Core::Cursor#each:/Users/moonglum/Code/ashikawa-core/lib/ashikawa-core/cursor.rb:57`.

[File](https://github.com/triAGENS/ashikawa-core/blob/mutant/lib/ashikawa-core/cursor.rb)

I guess it tries to remove the `unless` statement.

**Comment by mbj** [comment]
@moonglum Years later, and mutant now being a commercial tool (receiving much better support): There is now an option to deal with this from the mutant side: https://github.com/mbj/mutant/blob/master/docs/configuration.md#mutation_timeout.
