### ISSUE TITLE
Implicit default matcher

### ISSUE THREAD

**Issue by sferik** [mbj/mutant#174]
It should not be necessary to specify a class/method matcher. By default, mutant should run for any classes/methods that are `describe`d.

**Comment by mbj** [comment]
I like the idea, but I do not have a need to do it for my projects. So tagging as `not-on-authors-free-time` to encourage funding or (preferred) outside contribution.

**Comment by mbj** [comment]
I see a big problem with this approach: It would NOT discover non described classes that should be mutated. 

I'd argue mutant instead should have framework specific integrations that discover subjects to mutate, such like a rails integration discovering all controllers etc.

Closing this for now.
