### ISSUE TITLE
Add a mutation from def foo(*args) to def foo(*); args = []; end

### ISSUE THREAD

**Issue by mbj** [mbj/mutant#181]
This will catch cases where there is no spec for calling the method with zero arguments.

**Comment by backus** [comment]
Working on this now.  Would have the same effect and be easier to implement if the mutation `def foo(*args); args = []; end`

**Comment by mbj** [comment]
Make sure you keep the body intact!

**Comment by mbj** [comment]
@backus ^^ I changed the title to actually reference valid ruby syntax. This ticket was made in a rush.

**Comment by backus** [comment]
> Make sure you keep the body intact!

Of course. My point was just that `restarg` doesn't need to drop the name.
