### ISSUE TITLE
Re-introduce filtering out specific mutations

### ISSUE THREAD

**Issue by solnic** [mbj/mutant#184]
I'd like to be able to tell mutant which mutations should be skipped using a pattern. My specific case is debugging statements so I'd imagine doing something like "mutant --skip "/debug(\w+)/".

**Comment by mbj** [comment]
I like the idea. But I do not need this. So tagging as `not-on-authors-free-time` to encourage people to fund this, or preferred: Contribute it ;)

**Comment by mbj** [comment]
@solnic This was implemented in: https://github.com/mbj/mutant/blob/main/Changelog.md#v01112-2022-06-27.

Closing.
