### ISSUE TITLE
Using it on a Rails app

### ISSUE THREAD

**Issue by radanskoric** [mbj/mutant#21]
Is anyone using this on a Rails app?

I'm sure it's possible but I can not find an example or documentation for the mutant command line parameters to figure out what is the correct way to use it on a rails app. 

Any help or pointers appreciated.

**Comment by mbj** [comment]
Mutant now has worker process start hooks that can be used to setup a per worker process test DB isolating tests run in concurrency from each other: https://github.com/mbj/mutant/pull/1379

**Comment by mbj** [comment]
```RAILS_ENV=test bundle exec mutant --require ./config/application --jobs 1 -- descendants:ApplicationController descendants:ActiveRecord::Base```
