### ISSUE TITLE
Make the --use $integration flag mandatory.

### ISSUE THREAD

**Issue by UrsMetz** [mbj/mutant#246]
When omitting the `--use rspec` flag calling mutant you get the following kind of error:

```
neutral:<method in your code>
--- Neutral failure ---
Original code was inserted unmutated. And the test did NOT PASS.
Your tests do not pass initially or you found a bug in mutant / unparser.
Subject AST:
<some AST>
Unparsed Source:
<the method you wanted to be mutated>
Test Reports: 0
```

This mistake in calling mutant might be hard to spot with the error report above. I think mutant should either fall back to using RSpec or maybe even better just report that there was no testing framework given so that the user can correct the command line arguments passed to mutant.

**Comment by mbj** [comment]
Mutant enforces the presence of an explicit integration since v0.10.14.
