### ISSUE TITLE
Mutant creates an endless loop in Range (replaces value with Infinity)

### ISSUE THREAD

**Issue by Stormwind** [mbj/mutant#25]
Hi,

I discovered another bug in mutant in combination with ranges:

```
@@ -3,7 +3,7 @@
     return(0)
   end
   result = 1
-  (1..exponent).each do
+  (1..((1.0) / (0.0))).each do
     result = multiply(2, result)
   end
   result
.......
```

It replaces the variable `exponent` here with `(1.0) / (0.0)` (Infinity), which leads to an endless loop.

Test code is still the same:
https://gist.github.com/cfbba9f7f3ed0bbfa8ab

**Comment by mbj** [comment]
There is now also explicit support mutant side for dealing with these situations: https://github.com/mbj/mutant/blob/master/docs/configuration.md#mutation_timeout
