### ISSUE TITLE
Add ability to have stricter requirements for code written after a specific time

### ISSUE THREAD

**Issue by dkubb** [mbj/mutant#262]
The idea with this is that you could configure mutant to be stricter with newer code than older code. You might want to say "all code written after today must be 100% covered", while still allowing the older code to be covered by the default thresholds.

I would use this on our $work project and force all new code to be 100% covered, while allowing us to be a bit more lenient with legacy code. I could see others using it this way too.

**Comment by kbrock** [comment]
I have a list of files that I have 100% coverage.
I then add files to that list over time. Of course, you could do a black list instead of a whitelist. Anything more complex would probably be better done in ruby than bash. Hope this gives you some ideas to pursue.

I have a `run_mutant` script in my root directory:

```bash
#!/usr/bin/env bash

if [ $# -eq 0 ] ; then
  # NOTE: missing:
  # Cli
  # BookCreator

  args="Binder BookDef CachedHash CascadingArray Chapter Editor Logging PageDb PageDef Runner Speaker SpeakerDef Spider SpokenChapter UrlFilter Web"
else
  args="$*"
fi
args=" $args"
class="${args// / AudioBookCreator::}"
MUTANT=true mutant --include lib --require audio_book_creator --use rspec ${class} --fail-fast -d --jobs 1
```

I can run with a new class via run_mutant Cli

Good luck. And let me know if you have a better method.

**Comment by kbrock** [comment]
Mutants take a little while for me to run.
I have come up with [run_mutant](https://github.com/kbrock/audio_book_creator/blob/master/run_mutant) that will only run mutants when a source or spec file changes. The mutant results are stored in a file so they are easy to fix.

```
./run_mutant 
  251/ 251  AudioBookCreator::Binder
   88/  88  AudioBookCreator::BookCreator
  147/ 147  AudioBookCreator::BookDef
   35/  35  AudioBookCreator::CachedHash
  199/ 199  AudioBookCreator::CascadingArray
  158/ 158  AudioBookCreator::Chapter
* 620/ 630  AudioBookCreator::Cli
  205/ 205  AudioBookCreator::Conductor
  130/ 130  AudioBookCreator::Editor
    7/   7  AudioBookCreator::Logging
  129/ 129  AudioBookCreator::PageDb
  129/ 129  AudioBookCreator::PageDef
  161/ 161  AudioBookCreator::Runner
  246/ 246  AudioBookCreator::Speaker
   94/  94  AudioBookCreator::SpeakerDef
  353/ 353  AudioBookCreator::Spider
   69/  69  AudioBookCreator::SpokenChapter
   32/  32  AudioBookCreator::SurferDef
  183/ 183  AudioBookCreator::UrlFilter
  158/ 158  AudioBookCreator::Web
  134/ 134  AudioBookCreator
```

**Comment by mbj** [comment]
@kbrock That works also but is less selective than the feature @dkubb has in mind. I wounder if combined with #370 your style could be shipped from mainline also.
