### ISSUE TITLE
Add a mutation from `a != b` to `!a.eql?(b)` and `!a.equal?(b)`.

### ISSUE THREAD

**Issue by mbj** [mbj/mutant#270]
This will fix cases where permissive `Object#==` semantics get used unintentionally.

**Comment by kbrock** [comment]
@mbj would you would prefer `eql?` and `equal?` over the simpler `==`?

(sorry if I asked this before - not sure if I submitted it the last time I typed this question)

**Comment by mbj** [comment]
@kbrock `eql?`, `equal?` and `==` are not equal in its semantics, `==` is the operator with most semantics, `eql?` has less and `equal?` the least. Sometimes these are just aliases of each other.

As the fundamental 'Mutation operator design axiom' mutant tries to force the use of the 'Least powerful primitive'. Both for simple expressions (turning an `==` into an `eql?` etc) and for composed expressions (like a sequence `a; b` being turned into `b` etc).

Ruby does not have a build in representation for negations on `eql?` and `equal?`. We tend to use `!=` here. But this is equivalent to `!(a == b)` which uses the "weak" semantics of `==` internally. Hence this ticket exists.

Does all this answer your question?
