### ISSUE TITLE
What's the point of this mutation?

### ISSUE THREAD

**Issue by knovoselic** [mbj/mutant#283]
Can anyone explain in what cases this mutation makes sense?

     def self.new(*args)
    -  if self.equal?(SomeType)
    +  if equal?(SomeType)

Isn't it just a matter of style in this example?

**Comment by mbj** [comment]
Mutant does no style mutations. Its based on the AST.

If you compare the AST of the original:

```
bundle exec ruby-parse -e 'self.equal?(SomeType)'
send
  (self) :equal?
  (const nil :SomeType))
```

```
bundle exec ruby-parse -e 'equal?(SomeType)'
(send nil :equal?
  (const nil :SomeType))
```

You'll notice a difference. The explicit receiver in the original source could be replaced with an implicit receiver. Implicit sends always are targeted to the current self. Hence from mutant POV the send to implicit self is "less primitive" than the send to any arbitrary object (including the explicit self).

Mutation operators in mutant are based on the idea to generally mutate to less powerful constructs and let your tests prove that a more powerful construct is needed.

This is easy to explain with an expression like `a; b`. If the calls to `a` or `b` can be removed without your tests noticing they are probably redundant (or a test is missing).

I derived close to all mutation operators in mutant from the "mutate to less powerful primitive" rule. Hence this operator exist.

I hope this answer is sufficient. I'll close this issue now. Feel free to continue this discussion.

**Comment by mbj** [comment]
BTW I write a slightly longer version of this explanation here: https://github.com/mbj/mutant/issues/274#issuecomment-69909437

**Comment by mbj** [comment]
Before I made up the "mutation operator axioms" there is another longer thread asking about the same mutation with more links and context: https://github.com/mbj/mutant/issues/2

**Comment by knovoselic** [comment]
Thank you for a great explanation. I've read both tickets and now I understand why this mutation exists.
You did a great job with mutant, keep up the good work :)

**Comment by mbj** [comment]
@knovoselic thx.
