### ISSUE TITLE
Remove mutation `foo and bar` to `!(foo and bar)`

### ISSUE THREAD

**Issue by mbj** [mbj/mutant#287]
Right now mutant assumes that the use of the AST nodes `or` and `and` is always about boolean, non side effectful computations.

As those nodes are also used for control flow a mutation like:

```ruby
def operation
  foo and bar
  other
end
```

To 

```ruby
def operation
  !(foo and bar)
  other
end
```

Is not killable.

This mutation probably should be removed for that reason.

**Comment by dkubb** [comment]
@mbj is there a heuristic that could be defined to test whether and expression's return value is part of another expression, or a method's return value? If we could know whether an expression is a subexpression, we could exclude performing the negation mutation since it won't make any difference at all.

**Comment by mbj** [comment]
@dkubb Mutant actually carries the parents node around. So we can at least create a whitelist of cases where the return value *is* significant.

If the parent is one of, we know the return value is used:

* `lvasgn`, excluding assignments to `_` prefixed lvars
* `ivasgn`
* `gvasgn`
* send with attribute assignment
* send with index assignment
* `mlhs` (parallel assignment left hand side), excluding assignments to `_` prefixed lvars
* Some op asgns.
* Probably some I forgot.

But I think that bringing back this mutation is not worth the time. Especially as we emit the negated left hand side already it would be mostly equivalent for a big increase of complexity because of the context dependant whitelisting above.

**Comment by dkubb** [comment]
> But I think that bringing back this mutation is not worth the time.

Yeah, I wasn't suggesting that. I was mainly trying to see if there was a higher level rule we could encode into the system that will cover this *and* other cases that are not yet handled. Effectively I was trying to find a deeper truth that can simplify more of the logic.

**Comment by mbj** [comment]
> Effectively I was trying to find a deeper truth that can simplify more of the logic.

The only thing I can think about is adding real control flow analysis, incorporating what I listed above. Something that I'd really not want to do with rubies "unorthogonal" primitives.

In more sane languages with better fundamental theory this is lot easier.

**Comment by mbj** [comment]
> is there a heuristic that could be defined to test whether and expression's return value is part of another expression,

The return value could also be intentionally ignored by the call side.

```ruby
class SomeIO
  def call
    do_thing_a
    do_other_thing_b
  end

private

  def do_thing_a
    action_a and action_b
  end
end
```

Unless we do control flow analysis we cannot see through the body of `#do_thing_a` to discover the result is thrown anway and a mutation to `!(action_a and action_b)` is an equivalent.

**Comment by dkubb** [comment]
@mbj good point about control flow analysis being needed. Other languages would make this easier than ruby.
