### ISSUE TITLE
Erroneous mutation when using `super` 

### ISSUE THREAD

**Issue by rranelli** [mbj/mutant#288]
When running:
    RAILS_ENV=test bundle exec mutant -r ./config/environment -j 1 --use rspec 'Bundle*'

I get:

```diff
-def invoke_callback(resource_url)
+def invoke_callback(resource_url__mutant__)
   plan.confirm!(action)
   super
 end
```

I tried to explicitly call super with `resource_url` and then I got:

```diff
 def invoke_callback(resource_url)
   plan.confirm!(action)
-  super(resource_url)
+  super
 end
```

I understand the need for the first mutation, but not for the second.
Is it possible for me to ignore it ?

I'm using ruby 2.1.2

**Comment by mbj** [comment]
@rranelli When you do not reference an lvar in a scope, but still need to declare it for interface arity reasons: Prefix with an underscore like `_resource_url`. This will tell mutant the argument is intentionally  not referenced and it should kill your mutation.

The mutation from `super(arg)` to `super`, speaking in nodes from `super` to `zsuper` is valid. As `zsuper` is a simpler primitive than `super`.

Feel free to discuss, I hope I answered the requestion, closing this issue now.

**Comment by rranelli** [comment]
Nice, that was what I was looking for =)

Thanks for the attention.
