### ISSUE TITLE
Uninitialized constant

### ISSUE THREAD

**Issue by nli-mdsol** [mbj/mutant#289]
The structure of my project is like this:
* lib/level1/level2
* spec/level1/level2

When I ran test at *spec/level1* against classes or modules at *lib/level1*, it was fine. I got the error when I ran the tests at *spec/level1/level2* against classes at *lib/level1/level2*.
There are two classes under *lib/level1/level2*: *class1* and *class2*. *Class2* extends from *class1*.
In *class1*, the def is:
```
module level1
   module level2
       class class1
```

In *class2*, the def is:
```
module level1
   module level2
       class class2 < class1
```

Under *spec/level1/level2*, I have *class1_spec* and *class2_spec* test files.
*class1_spec* has 
```
describe level1::level2
 do ... end
```
*class2_spec* has 
```
describe level1::level2::class2 
do ... end
```
When I ran 
```bundle exec mutant -I lib -r level1/level2/class1 --use rspec level::level2```
to execute *class1_spec* against *class1*, it was fine.
However, when I tried to execute *class2_spec* against *class2* using the command ```bundle exec mutant -I lib -r level1/level2/class2 --use rspec level1::level2::class2```, I got the error ```<module:level2>: uninitialized constant level1::level2::class1 (NameError)```. 
I also tried other commands such as ```bundle exec mutant -I lib -r level1::level2 --use rspec level1::level2::class2``` and ```bundle exec mutant -I lib -r level1--use rspec level1::level2::class2,``` it was unsuccessful.

Do you have an idea why I got the error? Thanks.

**Comment by mbj** [comment]
@nli-mdsol I'm busy right now. Could you fix formatting a bit meanwhile to render commands and outputs in backticks? Thx. I'll look into it in my next OSS cycle.

**Comment by nli-mdsol** [comment]
I have updated the original post. The backtrace for the command ```bundle exec mutant -I lib -r level1/level2/class2 --use rspec level1::level2::class2``` is shown below:
```
/Users/nli/Documents/git/project/lib/level1/level2/class2.rb:6:in `<module:level2>': uninitialized constant level1::level2::class1 (NameError)
	from /Users/nli/Documents/git/project/lib/level1/level2/class2.rb:5:in `<module:level1>'
	from /Users/nli/Documents/git/project/lib/level1/level2/class2.rb:4:in `<top (required)>'
	from /Users/nli/.rvm/gems/ruby-2.0.0-p598/gems/mutant-0.6.7/lib/mutant/env.rb:144:in `require'
	from /Users/nli/.rvm/gems/ruby-2.0.0-p598/gems/mutant-0.6.7/lib/mutant/env.rb:144:in `each'
	from /Users/nli/.rvm/gems/ruby-2.0.0-p598/gems/mutant-0.6.7/lib/mutant/env.rb:144:in `infect'
	from /Users/nli/.rvm/gems/ruby-2.0.0-p598/gems/mutant-0.6.7/lib/mutant/env.rb:27:in `initialize'
	from /Users/nli/.rvm/gems/ruby-2.0.0-p598/gems/adamantium-0.2.0/lib/adamantium/class_methods.rb:17:in `new'
	from /Users/nli/.rvm/gems/ruby-2.0.0-p598/gems/adamantium-0.2.0/lib/adamantium/class_methods.rb:17:in `new'
	from /Users/nli/.rvm/gems/ruby-2.0.0-p598/gems/mutant-0.6.7/lib/mutant/env.rb:15:in `new'
	from /Users/nli/.rvm/gems/ruby-2.0.0-p598/gems/mutant-0.6.7/lib/mutant/cli.rb:25:in `run'
	from /Users/nli/.rvm/gems/ruby-2.0.0-p598/gems/mutant-0.6.7/bin/mutant:19:in `<top (required)>'
	from /Users/nli/.rvm/gems/ruby-2.0.0-p598/bin/mutant:23:in `load'
	from /Users/nli/.rvm/gems/ruby-2.0.0-p598/bin/mutant:23:in `<main>'
```
Note the the line 4-6 of class2 is shown below.
```
4: module level1
5:   module level2
6:       class class2 < class1
```

**Comment by mbj** [comment]
To me this looks like your environment is not fully populated when mutant executes your requires. 

This behavior is not specific to mutant.

`ruby -I lib -r level1/level2/class2` will probably fail the same way.

You probably need to list `class1` explicitly in require (in correct order). Or use a more general 'require entrypoint'.

I typically avoid testing against a subtree of my requires, since this can lead to a false sense of security, especially with partially initialized constant scope that make your test execute a different behavior than you'd see in production.

**Comment by nli-mdsol** [comment]
Thanks, I explicitly required class1 and it worked. The command I used is ```bundle exec mutant -I lib -r level1/level2/class1 -r level1/level2/class2 --use rspec level1::level2::class2.```

When you say "use a more general require entrypoint," do you mean to use ```-r level1``` or ```-r level1/level2```? 
When I used ```bundle exec mutant -I lib -r level1::level2 --use rspec level1::level2::class2,``` I got an error ```/Users/nli/.rvm/gems/ruby-2.0.0-p598/gems/mutant-0.6.7/lib/mutant.rb:53:in `const_get': uninitialized constant class2 (NameError).```
When I used ```bundle exec mutant -I lib -r level1 --use rspec level1::level2::class2,``` I got an error ```/Users/nli/.rvm/gems/ruby-2.0.0-p598/gems/mutant-0.6.7/lib/mutant.rb:53:in `const_get': uninitialized constant level2 (NameError).```

One more question, when I executed ```bundle exec mutant -I lib -r level1/level2/class1 -r level1/level2/class2 --use rspec level1::level2::class2.``` or ```bundle exec mutant -I lib -r level1/level2/class1 --use rspec level::level2.``` No mutants were generated in class1. Class 1 is implemented as below.

```
module level1
   module level2
       class class1
           def method1(param)
                 raise 'provide an implementation'
           end
   end
end
```
Is it because no mutation operator is applied to this method in class1 or something wrong with my settings?

**Comment by mbj** [comment]
> One more question, when I executed bundle exec mutant -I lib -r level1/level2/class1 -r level1/level2/class2 --use rspec level1::level2::class2. or bundle exec mutant -I lib -r level1/level2/class1 --use rspec level::level2. No mutants were generated in class1. Class 1 is implemented as below.

Because `Class1` was not loaded at this point. Mutant cannot mutate what is not loaded. I think you should load *everything* into your ruby VM than test / mutation-test. Testing partial requires does not make too much sense as you run into integration problems and a partial require state is not representative for production.

> When you say "use a more general require entrypoint," do you mean to use -r level1 or -r level1/level2? 

I mean that you should have one require that requires all the classes at once. Instead to do partial requires. For the reson above. So instead `require 'my-project/class1'` you should have an `require 'my-project' that does all the class specific requires for you. And from all your tooling (including mutant) you only do the `require 'my-project`.

**Comment by mbj** [comment]
I'm closing this issue now as all questions where answered. Feel free to continue discussion.
