### ISSUE TITLE
Verify / Test compatibility with rspec 3.2

### ISSUE THREAD

**Issue by mbj** [mbj/mutant#294]
Mutant right now does not allow to use rspec-3.2 because of limitations intentionally placed in the `mutant-rspec.gemspec`. We are using unofficial APIs in rspec that are subjected to change in each bigger release, so we need to followup each bigger change manually.

This ticket can be closed when:

* [x] Rspec 3.2 is known to work
* [x] An project ported to rspec 3.2 passes the corpus test
* [x] The rspec 3.2 integration spasses integration tests
* [x] `mutant-rspec.gemspec` declares compatbility in with `3.2`

**Comment by solnic** [comment]
Any progress on this? I bumped rspec in ROM and noticed I can't use mutant anymore :weary:

**Comment by mbj** [comment]
@solnic I got positive reports by people that moved to `3.2` already. But I could not verify this yet due lack of **any** OSS time in the recent weeks.

**Comment by mbj** [comment]
@solnic Those people forked and bumped the dep. But to release something I think all the points above should be done. Maybe we can do a quick `.beta` to workaround my do not have time for OSS issue.

**Comment by solnic** [comment]
OK I'll check it out using a fork and report back

**Comment by mbj** [comment]
@solnic Actually I'm just creating `rspec-3-2` branches of devtools/mutant/auom. When everything works out you'll get an rspec-3.2 compatible release the next hour.

**Comment by mbj** [comment]
@solnic Waiting for CI than will merge: #295

**Comment by mbj** [comment]
@solnic Just released `0.7.7` with `rspec-3.2` support. Closing this issue.

**Comment by solnic** [comment]
hah! thanks!
