### ISSUE TITLE
How to run database tests?

### ISSUE THREAD

**Issue by knovoselic** [mbj/mutant#304]
Hi,

I have a class which deals with low-level database stuff and I have to read/write from/to the database in my tests. How should I write my tests so that they work correctly with mutant? Is there a way to turn off the parallelization in mutant, i.e. test mutants sequentially?

**Comment by knovoselic** [comment]
So I've been trying to figure something out, and I've come up with this (goes into rails_helper.rb):

    if ENV['db_safe']
      config.before(:suite) do
        $used_databases = Set.new
      end
  
      config.before(:each) do
        database_name = "test_db_#{Thread.current.object_id.to_s(36)}"
        $used_databases << database_name
        Mongoid.override_database database_name
      end
  
      config.after(:each) do
        Mongoid.override_database nil
      end
  
      config.after(:suite) do
        $used_databases.each do |database|
          Mongoid.default_session.with(database: database).drop
        end
      end
    end

It's far from ideal, but at least mutant works as expected. It slows down the tests considerably (because it constantly creates/drops the DB), that's why it's only activated if env variable is set. Let me know if there's a way to improve this. Are there any callbacks in mutant so that I can create/drop DB only when thread is started/terminated? Right now it's dropping the DB after each mutant runs.

I'm open to any suggestions. Is there a better way to do this?

**Comment by mbj** [comment]
> Is there a way to turn off the parallelization in mutant, i.e. test mutants sequentially?

Use the `-j 1` flag.

> I have a class which deals with low-level database stuff and I have to read/write from/to the database in my tests. How should I write my tests so that they work correctly with mutant?

Mutant expects a pristine state the tests run against. For in-memory (unit tests) mutant archives this via running the mutations in a dedicated kill-fork, so any potential state change from the killing does not leak into other concurrently or sequentially executed tests.

In case you use a foreign state (Database, or generally anything that is reachable via RPC) you need to isolate the state by yourself. On RDBMS when I (mostly for legacy reasons) have to use the database from tests I isolate via a serializable transaction I do not commit.

For a database like MongoDB without strong transaction / isolation the only viable solution I see is namespaceing, like you did. So you need to look for a "good" namespace strategy. A strategy that creates a namespace per mutation.

Mutant right now does not give you access to the current mutation, so you can namespace against mutant implementation details. Using the `Thread#object_id` should mostly work. But I think that using `Process.pid` might be a nicer unique identifier.

I think you could open a feature request to expose some metadata, like the index of the current mutation. Exposing this in the `ENV` might be an option.

As I think I answered the question, I'm gonna close this issue. Feel free to continue discussion.
