### ISSUE TITLE
Ability to ignore part of the code (log/debug statements)

### ISSUE THREAD

**Issue by adrienkohlbecker** [mbj/mutant#307]
Hello,

I've been using mutant for a while, and it's really useful, thanks for the hard work :)

Would it be possible to ignore specific code in the mutations ?
I'd rather not add detailed specs for these kind of statements:

```
ErrorService.report_error("some error happened", arg1, arg2)
Rails.logger.debug "test"
...
```

For example it could ignore lines matching a regex?
Cheers

**Comment by mbj** [comment]
> I've been using mutant for a while, and it's really useful, thanks for the hard work :)

Thx.

> I'd rather not add detailed specs for these kind of statements:

I'm generally in the favor to specify *everything*. And in case this is hard reduce what the code does instead to maintain a whitelist.

So in case you check-in debug statements and run into mutant wanting you to cover them ask yourself: Why you have debug statements in your code at the first place?

If you have a dedicated `ErrorService` its IMO part of your domain and *should* have specs. In case it is hard to spec, develop some cool rspec helpers that reduce the pain. Mutant causes architectural backpressure here, listen to it was always the best option.

> For example it could ignore lines matching a regex?

Mutant is an AST based tool. I do not see the source represented as a sequence of lines. So excluding an AST subtree based on a source based filter (regexp) might not be the best idea.

Writing an AST based filter might be possible.

```
ruby-parse -e 'Rails.logger.debug "test"' 
(send
  (send
    (const nil :Rails) :logger) :debug
  (str "test"))
```

The pattern to send `:debug` to an object returned by sending `:logger` to the constant `Rails` is identifiable and *could* be excluded by the mutation emitter.

As I do not want to bound mutant to rails in any way, I think I could look into providing a filter architecture a `mutant-rails` plugin could use to filter out this stuff.

But I think that such a filtering is only a workaround for non disciplined development, so I'll not do it by myself. PRs welcome through.

**Comment by mockdeep** [comment]
It might make sense to have a more generic configurable filter not specific to rails. If you had some sort of `mutant.yml` config you could do something like:

```yml
ignore:
  - Rails.logger
```

**Comment by mbj** [comment]
> It might make sense to have a more generic configurable filter not specific to rails.

This is something I'd build.

**Comment by mbj** [comment]
>  If you had some sort of mutant.yml

In the works for a while now: https://github.com/mbj/mutant/pull/247 no OSS time to finish it through.

**Comment by adrienkohlbecker** [comment]
I expected this response regarding the philosophy :)
Sure, I guess it's not as rigorous as it could be, but I don't consider log statements to be part of the critical domain code. Maybe my example of an `ErrorService` was not the best, though, I agree.

I agree on the non-rails-specific part, this should be generic, the idea of an `ignore` key in a `mutant.yml` is perfect.

**Comment by mbj** [comment]
> I expected this response regarding the philosophy :)

heh

> Sure, I guess it's not as rigorous as it could be, but I don't consider log statements to be part of the critical domain code. Maybe my example of an ErrorService was not the best, though, I agree.

> I agree on the non-rails-specific part, this should be generic, the idea of an ignore key in a mutant.yml is perfect.

So filtering on the parsed string `Rails.logger` might be possible in a generic manner. I'm happy to provide the infrastructure for this. But my OSS time is too limited currently, I'll focus on the issues that concern me. Hope some company will sponsor some features in future. Or I get more time for OSS.

**Comment by mbj** [comment]
I like the idea, but I do not have a need to do it for my projects. So tagging as not-on-authors-free-time to encourage funding or (preferred) outside contribution.

**Comment by mbj** [comment]
This was implemented (only 7y passed) in: https://github.com/mbj/mutant/blob/main/Changelog.md#v01112-2022-06-27.

Closing.
