### ISSUE TITLE
Add mutation from `super` to `super()`

### ISSUE THREAD

**Issue by mbj** [mbj/mutant#309]
To quote @dkubb:

> At first I was going to say no, that super is more primitive than super() but I'm not so sure now.

> I mean, super basically allows you to delegate to the caller what arguments to pass up to the parent method. When you use super() you allow the parent method's own defaults to kick in. If you have no specs that assert different behaviour from the defaults is expected, then I think super() is a perfectly valid mutation -- if you want to use super then you should have specs to assert that giving up control to the caller is expected behaviour.

**Comment by backus** [comment]
a0dd3c9 removed this mutation.  Was the issue then just something to do with rubinius?

**Comment by mbj** [comment]
> a0dd3c9 removed this mutation. Was the issue then just something to do with rubinius?

TBH I do not recall. Lets add it again and find out.

**Comment by mvz** [comment]
@mbj Is this mutation supposed to occur when the current method has no arguments?

**Comment by backus** [comment]
@mvz I can't answer for @mbj here but I'm going to guess that his answer might be something like "the `(super)` node is always more strict than the `(zsuper)` node so you should always use `(super)` unless you want to depend on the more dynamic behavior of `(zsuper)`."

On an unrelated note: you should join our slack channel. Can I invite your email listed on your personal website?

**Comment by mvz** [comment]
> Can I invite your email listed on your personal website?

Yes, please.

**Comment by mbj** [comment]
> @mbj Is this mutation supposed to occur when the current method has no arguments?

I think that there is right now no conditional behavior.

**Comment by backus** [comment]
> > Can I invite your email listed on your personal website?
>
> Yes, please.

Sent!
