### ISSUE TITLE
Possible parser issue on 2.0.0

### ISSUE THREAD

**Issue by crimsonknave** [mbj/mutant#311]
One of my travis runs seems to have run into a mutant issue. The run runs my tests and then runs mutant. However, mutant says that my tests either failed or I found a mutant parser bug.

The run in question is using 2.0.0 (at whatever the default travis-ci patch is). The same run passed on ruby 2.1.5 and 2.2.0

Here's the text of the error
```
Original code was inserted unmutated. And the test did NOT PASS.
Your tests do not pass initially or you found a bug in mutant / unparser.
Subject AST:
(def :changed?
  (args)
  (send
    (send nil :map
      (block-pass
        (sym :changed?))) :include?
    (true)))
Unparsed Source:
def changed?
  map(&:changed?).include?(true)
end
```

And here's a link to the run https://travis-ci.org/crimsonknave/cot/jobs/56164332

The class this is running on inherits from simple delegator and delegates to an array.

**Comment by mbj** [comment]
Thx for that report. I'll look into it when I have the time. Warning: My OSS time is very limited these days.

**Comment by mbj** [comment]
@crimsonknave I could not reproduce this, yet. But these lines:

`Coverage report generated for RSpec to /home/travis/build/crimsonknave/cot/coverage. 0.0 / 0.0 LOC (100.0%) covered.`

Scattered throughout your mutant progress report indicate something is wrong with your spec setup. Can you change simplecov NOT to run when mutant is running, it might inference with mutants analysis. 

Also is the behavior reproducible? Are your specs passing deterministically, or sporadically failing?

Note the error message mutant gives:

> Your tests do **not pass** initially **or** you found a bug in mutant / unparser.

In case your spec is not passing for *real* under 2.0 mutant detected this. Or it might not pass just under the way mutant invokes it. Given the fact that simplecov has a history to mangle [exit codes](https://github.com/colszowka/simplecov/issues/281) I think you should first fix simplecov NOT to run under mutant.

Than check if the error happens deterministic (always a noop fail under 2.0?), and or if your specs are deterministically passing when executed in separation (like mutant does).

Unless I get that questions / reports answered there is nothing I can do right now.

Noop tests where especially added to mutant to double check for integration issues like these.

**Comment by crimsonknave** [comment]
I was not running the tests individually. When I do, I'm able to find the test that's failing. I'll also have simplecov not run during mutant. Thanks for helping me track this down.

**Comment by mbj** [comment]
Thats cool. I'll change the message to make it clear that these days 99% the users specs are not deterministic and the source of noop errors being reported. I actually never saw a "mutants fault" noop during the last 12 month.
