### ISSUE TITLE
Spec fails ./spec/unit/mutant/reporter/cli_spec.rb:59 - Tput::INSTANCE is not available

### ISSUE THREAD

**Issue by kbrock** [mbj/mutant#313]
using ruby 2.1.5 (not sure if this matters)

```
bundle exec rspec ./spec/unit/mutant/reporter/cli_spec.rb:59
```
failure:
```
  1) Mutant::Reporter::CLI.build when not on CI and on a tty should eql #<Mutant::Reporter::CLI output=#<RSpec::Mocks::Double:0x3fe3cde540e8 @name="Output"> format=#<Mutant::Reporter::CLI::Format::Framed tty=true tput=#<Mutant::Reporter::CLI::Tput available=false prepare=nil restore=nil>>>
```
want to add something like this to 52:
```ruby
      expect(described_class::Tput::INSTANCE).to receive(:available).and_return(true)
```

but it wasn't working for me

thanks

**Comment by mbj** [comment]
@kbrock Can you get me the output of?

```
whereis tput
uname -a
``` 

Of your system? I never ran the specs on macosx by myself so far, so I *think* its a macosx specific issue we want to fix.

```
Mutant::Tput::INSTANCE
```

Is frozen, so you cannot add message expectations on it. We probably want to make this spec pass on non linux/tput-available via changing the expectations on that system.

Ideally we also find a `tput` equivalent, or fix the `tput` usage in case Macosx provides `tput` but with different options.

**Comment by mbj** [comment]
BTW thx for the report.

**Comment by kbrock** [comment]
cool. I felt guilty for submitting and not fixing, but I'm off on other stuff right now.

tput: `/usr/bin/tput`
uname: `Darwin Kernel Version 14.1.0: Thu Feb 26 19:26:47 PST 2015; root:xnu-2782.10.73~1/RELEASE_X86_64 x86_64`

not sure if helpful, but trollop also uses tput: [here](https://github.com/ManageIQ/trollop/blob/master/lib/trollop.rb#L520-L552)

**Comment by mbj** [comment]
> not sure if helpful, but trollop also uses tput: here

It uses a more common subset of the tput API. Mutant probably does some linux specific things.

Can you get me the full rspec error message? what you posted is only the full rspec example description (the one mutant parses subject mapping from), NOT the actual error message.

I do not have access to a macosx machine, if you are blocked by this issue, simple set the spec to pending in your branch. It only affects automatic choose of progress reporters, nothing in the "core" of mutants domain.

Meanwhile I'll hope to get the chance to run mutants specs on macosx by myself to figure out a sane way to write this spec.

**Comment by mbj** [comment]
> cool. I felt guilty for submitting and not fixing,

Thats totally fine. I felt guilty not to have an environment that runs macosx as part of my CI setup.
Once CircleCI supports a text matrix, I'll probably use their Macosx support to include it.
