### ISSUE TITLE
3rd party lib unable to emit subject - what action?

### ISSUE THREAD

**Issue by tjchambers** [mbj/mutant#337]
On certain classes I am getting: 

```
{Module,Class}#name should return resolvable constant name as String or nil
#<UnboundMethod: CollaborativeDesign#belongs_to_counter_cache_after_update> is defined from a 3rd party lib unable to emit subject
```

I infer that there is a module I am including from a gem that is causing this. What action is suggested here? What is the impact of this "condition"?

**Comment by mbj** [comment]
I believe the first line of your message is related to a warning from: https://github.com/mbj/mutant/issues/338

The 2nd line is just telling you that your match expression included the method `CollaborativeDesign#belongs_to_counter_cache_after_update`, but that method does not have a source location, this most likely means it was metaprogrammed in by a 3rd party library. Mutant cannot emit a subject for that case. So it will not get mutated.

The message exists so you know the reason on why this method will not have mutations. Do you think the message can be improved to be more clear?

**Comment by tjchambers** [comment]
Please forgive my ignorance. 

You stated that "your match expression included the method CollaborativeDesign#belongs_to_counter_cache_after_update" but nowhere in MY specs nor MY code do I refer to this method. I understand the method could be injected by a 3rd party library as a method on my described class = CollaborativeDesign. But my inference is that mutant believes I am somehow explicitly referring to #belongs_to_counter_cache_after_update - which I am not - at least explicitly not. 

If it feels it is part of a match expression, which I interpret to be a rspec matcher, then it would help to locate WHERE (aka what line?) this occurred.

**Comment by tjchambers** [comment]
This appears to be Rails injected. 

Closing this.

**Comment by mbj** [comment]
> This appears to be Rails injected.

Yeah, its rails injected. And mutant warns about this as it is not able to deterministic find the source location for a method in your selection. This warning is made to make people aware about this and in case they explicitly target for this method they can realize why there cannot be mutations emitted for this method.
