### ISSUE TITLE
XPATH warning - what action?

### ISSUE THREAD

**Issue by tjchambers** [mbj/mutant#338]
I am almost always getting this from mutant when I begin mutating a class:

```
Module#name from: XPath::HTML returned #<XPath::Expression:0x007fa469634f10 @expression=:node_name, @arguments=[#<XPath::Expression:0x007fa4696350a0 @expression=:this_node, @arguments=[]>]>. Fix your lib to follow normal ruby semantics!
{Module,Class}#name should return resolvable constant name as String or nil
Module#name from: XPath returned #<XPath::Expression:0x007fa46d1d0970 @expression=:node_name, @arguments=[#<XPath::Expression:0x007fa46d1d0ad8 @expression=:this_node, @arguments=[]>]>. Fix your lib to follow normal ruby semantics!
```

I am using predominantly Nokogiri (not everyone's favorite) for my XML processing, although most of my code is not XML processing. 

What action should I be taking? And how is this impacting the ability to mutate?

**Comment by mbj** [comment]
This is a warning mutant emits when it tries to expand your match expression into subjects to mutate.

There are 2 cases:

A) This warning gets emitted on your code. Solution: Fix your code to NOT violate `{Module,Class}#name` contract.
B) This warning gets emitted on 3rd party code. Solution: Complain upstream about the violation and get it fixed.

Mutant cannot know if an affected Class or Module is of type A) or B).

Do you think the message that led you to opening this issue, should include a reference to this explanation?

**Comment by tjchambers** [comment]
I think that a reference would help. If I understand it correctly the above XPATH::HTML.name should return a String and it is obviously not. What is still a bit unclear is whether this inhibits the ability for mutant to mutate or whether it is a reporting issue only.

**Comment by mbj** [comment]
> What is still a bit unclear is whether this inhibits the ability for mutant to mutate or whether it is a reporting issue only.

In case you want to run mutant against a namespace where such a warning gets emitted: Better fix the warning. I assume you are not mutating `XPATH` so you should be fine on your project.

Still nokogiri should be fixed.

**Comment by tjchambers** [comment]
You are correct - not mutating XPATH class. And nokogiri has a multitude of things in line to be fixed. 

Thanks for the explanation.

**Comment by mbj** [comment]
> And nokogiri has a multitude of things in line to be fixed.

I saw some of the warnings going away in more recent nokogiri releases. Maybe give an upgrade a try.

**Comment by tjchambers** [comment]
I will see what my dependencies allow and give that a try - thanks.

**Comment by mbj** [comment]
I'm closing this issue as I feel the question was correctly answered.

**Comment by tjchambers** [comment]
Agree - thanks for the response.

**Comment by betesh** [comment]
> B) This warning gets emitted on 3rd party code. Solution: Complain upstream about the violation and get it fixed.

I opened sparklemotion/nokogiri#1635 and got this response from @flavorjones:

```
I'm sorry, but I don't what mutant is, nor why it expects this, nor what it expects this method to return for these objects. Some people have told me I'm pretty ignorant, but this seems to me like a silly thing for a gem to expect of the universe.
```

I don't feel that I am equipped to answer these questions.  Is there anyone here who thinks they could do a good job of answering these questions and starting a constructive dialog between the nokogiri team and the mutant team?

**Comment by flavorjones** [comment]
See my comment at https://github.com/sparklemotion/nokogiri/issues/1635#issuecomment-299855319 for a more complete explanation of why I don't understand @betesh's request.

**Comment by mbj** [comment]
@flavorjones I've replied also.

You can see this as an LSP violation. You overwrite the native `Class#name` with a method that has a totally different implementation, a domain specific one.

A bit more formal: `Class` descends from `Module` and `Module#name` is [defined](http://ruby-doc.org/core-2.3.0/Module.html#method-i-name) as this:

> Returns the name of the module mod. Returns nil for anonymous modules.

As you are effectively creating an instance of class where `#name` behaves differently you are using core ruby reflection APIs in an incompatible way. An LSP violation.

This is like overwriting `Object#{send,method,...}` with something that is no real replacement for the original behavior. Just the fact that it happens at singleton level is no "excuse" to mess with core reflection APIs.

I suggest you rename your `#name` on singleton to not clash with the Ruby methods. As tools (like mutant) rely on them to behave correctly.

There are cases where overwriting `#name` on the class singleton does make sense, example here is `rspec`, but they do honor the original API in returning a String (that maps back to a constant) or `nil` for their objects. Hence LSP compatible.
