### ISSUE TITLE
Advice on how to kill eager loading mutations

### ISSUE THREAD

**Issue by tjchambers** [mbj/mutant#341]
Besides removing the eager loading 'includes(:xxx)' in the following what guidance should I have in order to kill those mutations? Obviously there are an exponentially growing number of possible mutations for each additional include. 

```
evil:SubclassStatisticsMaintainer#update_respondent_totals:/Users/tj/projects/AOT/aotv2/app/lib/subclass_statistics_maintainer.rb:20:90284
@@ -1,7 +1,7 @@
 def update_respondent_totals
-  subclass_statistics.includes(:assessment, :subclass).each do |stats|
+  subclass_statistics.each do |stats|
     stats.total_respondents = stats.sufficient_respondents.size
     stats.save!
   end
 end
-----------------------
evil:SubclassStatisticsMaintainer#update_respondent_totals:/Users/tj/projects/AOT/aotv2/app/lib/subclass_statistics_maintainer.rb:20:47aae
@@ -1,7 +1,7 @@
 def update_respondent_totals
-  subclass_statistics.includes(:assessment, :subclass).each do |stats|
+  subclass_statistics.includes(nil, :subclass).each do |stats|
     stats.total_respondents = stats.sufficient_respondents.size
     stats.save!
   end
 end
-----------------------
evil:SubclassStatisticsMaintainer#update_respondent_totals:/Users/tj/projects/AOT/aotv2/app/lib/subclass_statistics_maintainer.rb:20:df617
@@ -1,7 +1,7 @@
 def update_respondent_totals
-  subclass_statistics.includes(:assessment, :subclass).each do |stats|
+  subclass_statistics.includes(:subclass).each do |stats|
     stats.total_respondents = stats.sufficient_respondents.size
     stats.save!
   end
 end
-----------------------
evil:SubclassStatisticsMaintainer#update_respondent_totals:/Users/tj/projects/AOT/aotv2/app/lib/subclass_statistics_maintainer.rb:20:53845
@@ -1,7 +1,7 @@
 def update_respondent_totals
-  subclass_statistics.includes(:assessment, :subclass).each do |stats|
+  subclass_statistics.includes(:assessment, nil).each do |stats|
     stats.total_respondents = stats.sufficient_respondents.size
     stats.save!
   end
 end
-----------------------
evil:SubclassStatisticsMaintainer#update_respondent_totals:/Users/tj/projects/AOT/aotv2/app/lib/subclass_statistics_maintainer.rb:20:5148b
@@ -1,7 +1,7 @@
 def update_respondent_totals
-  subclass_statistics.includes(:assessment, :subclass).each do |stats|
+  subclass_statistics.includes(:assessment).each do |stats|
     stats.total_respondents = stats.sufficient_respondents.size
     stats.save!
   end
 end
```

**Comment by mbj** [comment]
I think that there are many possible ways to handle this mutation, all with down / upsides:

* You could add a dedicated message expectation on the receiver of `#include`, specifying argument expectations. Upside: Looks easy, Downside: Is not, and it does not scale very well, also couples your spec closely to the implementation
* You could hack AR to forbid lazy loads, raising an exception when triggered
* You could hack AR to count the number of reads per example, and place an expectation against that number
* You could ignore that mutation, and accept AR API is hard to test, due the absence of easy way to observe record load order

What I did in my commercial project that *have* to use AR:

I placed a method expectation on the relation that receives `#include`. But I plan to disable lazy loads via an AR hack, that might first only be active on specs, but later also in production.

This method couples the implementation closely to the spec, but has the positive backpressure to organize the AR queries in a centralized way, to minimize the impact.

I *think* this question make be exhaustively answered. Closing this issue now. Feel free to continue discussion.
