### ISSUE TITLE
Execution Sequence of Example Groups 

### ISSUE THREAD

**Issue by tjchambers** [mbj/mutant#353]
Apologies if this has been asked before - I did not find it. 

Context: I am dealing with classes that have a high ratio of code in private methods not exposed publicly on purpose. Hence my specs have few example groups. 

I believe it is correct (still) to say that currently mutant will run all example groups when mutating private methods. If that is the case does it run the examples in my specs in the order that they appear? 

My goal is to sequence them such that the specs that kill highest number of mutants quickly, or are the least expense in terms of computation, appear first, and correspondingly those with low kill potential or high cost appear last, since the example group naming is irrelevant when mutating private methods.

Any guidance or correction would be beneficial to speed up kill rate.

**Comment by mbj** [comment]
> I believe it is correct (still) to say that currently mutant will run all example groups when mutating private methods. If that is the case does it run the examples in my specs in the order that they appear?

Not *all* example groups. The next higher subset of example groups by parent expression.

So given code like this:

```
module Foo
  module Bar
    module Baz
    private
      def method_a
      end
   end
  end
end
```

Test selection by the subject matched by expression `Foo::Bar::Baz#method_a` is done as the following:

Find tests matching:

```
Foo::Baz::Baz#method_a
```

If tests found, use them, if not use the parent expression to find tests:

```
Foo::Bar::Baz*`
```

If tests found, use them if not use the parent expression to find tests:

```
Foo::Bar*
```

If tests found use them if not use the parent expression to find tests:

```
Foo*
```

If tests found use them if not use the parent expression to find tests:

```
*
```

Now *all* examples would be eligible, unlikely this happens but on test suites with low selectivity it might happen.

**Comment by tjchambers** [comment]
@mbj - yes I think I was clear about the selection mechanism which you reiterated above, but thanks for confirming that. My question centered around the sequence once the selection was accomplished. I am going to infer that whether example groups ARE selected that the sequence is as ordered in my spec. Let me know if I am incorrect.

**Comment by mbj** [comment]
@tjchambers The examples (note NOT Example groups) that are selected are printed above alive mutations via their `Example#description` allowing you to identify the examples used to kill mutations on a specific subject. Its easy to do a mistake like misnesting of describe blocks resulting un unselectable tests, as they do not match the expression mechanism.

**Comment by tjchambers** [comment]
thanks - yet again I am learning something.
