### ISSUE TITLE
Mutation of #initialize?

### ISSUE THREAD

**Issue by tjchambers** [mbj/mutant#354]
Apologies if this has been asked. 

I am wondering if mutant mutates the initialize method. If not fine. 

If so do I use ".new" or "#initialize" as an example group to target mutants. 

My context is Rails models that have validations that are explicit and sometimes as private methods. My specs validate that my factories can create VALID new instances under a variety of off-nominal conditions.

**Comment by mbj** [comment]
> I am wondering if mutant mutates the initialize method

It mutates the `#initialize` method in case it was defined by yourself within a `def` node. If your initialize method was metaprogrammed via `define_method` or other strategies (module include etc) it'll NOT be mutated. Its assumed the metaprogramming call side does the tests for correct meta programmed semantics.

**Comment by tjchambers** [comment]
@mbj thanks. 

Follow up question is then I presume I should use #initialize as my example group then to target mutations. Correct?

**Comment by mbj** [comment]
`#initialize` is usually private. So mutations should be killed via the public interfacing methods.

**Comment by tjchambers** [comment]
@mbj - thanks - will use '.new' as the example group.

**Comment by mbj** [comment]
@tjchambers Yeah, when initialize is private, and does not have tests, mutant will select the next higher parent expression for test selection, that will include your `.new` example. I personally prefer NOT to write examples for `.new` and kill everything through the instances public methods. BUT that only works if `#initialize` does not have side effects outside the instance.

**Comment by mbj** [comment]
I think this was exhaustively answered, closing.

**Comment by tjchambers** [comment]
I concur - thanks for the additional explanation.
