### ISSUE TITLE
Targeting private method mutation kills in example groups

### ISSUE THREAD

**Issue by tjchambers** [mbj/mutant#355]
In a previous issue I asked about what specs are run when private methods are mutated. The answer was all of them. I take this still to be correct.

I want to be certain however that if in the case where I have private method #foo, and while I don't refer to #foo directly in my expectations, that mutant will still run all the tests even if I put "describe '#foo' do" as my example group specification around specs targeted at #foo.

My inference is referring to a private method name in example group names is fruitless. Just trying to confirm as if that had a focusing impact it could drastically increase my kill rate.

**Comment by mbj** [comment]
@tjchambers I think you want to read the [test selector code](https://github.com/mbj/mutant/blob/3b2a01046cf41a97bf090a116be740da3c6ce8e7/lib/mutant/selector/expression.rb#L7-L24).

**Comment by mbj** [comment]
@tjchambers Is this question answered, can we close the issue?

**Comment by tjchambers** [comment]
This code proves that mutant will execute a subset of tests targeted at the private method if the example specification is associated specifically with that private method (as I suspected). I have further confirmed that through testing. 

The side-effect - a big one - is that when specify a fine-grained test for the private method which exercises the public API, that the set of tests under that example must be comprehensive.
