### ISSUE TITLE
Question: reason for String '.' to #{nil} mutation

### ISSUE THREAD

**Issue by tjchambers** [mbj/mutant#362]
I have a mutation: 

```
 def survey_responded_eval
   targeted_points = @participant.respondable_points.size
   responded_points = @participant.respondent_details.count do |r|
     (r.value > Responses::NO_RESPONSE) || r.rtext_response.present?
   end
   if (responded_points >= targeted_points)
-    "#{@you} responded to ALL of the points on the #{opinion_survey_link}.".html_safe
+    "#{@you} responded to ALL of the points on the #{opinion_survey_link}#{nil}".html_safe
   else
     "#{@you} responded to #{responded_points} out of the #{targeted_points} statements on the #{opinion_survey_link}.".html_safe
   end
 end
```

I am trying to understand the reasoning behind the mutation of a period inside a string to what is essentially a nil (dropping the period). Just curious. Seems like a bit of a strange thing to have to make a spec for.

**Comment by tjchambers** [comment]
Also seems to mutate the period to #{self} as well?

```
-    "#{@you} responded to ALL of the points on the #{opinion_survey_link}.".html_safe
+    "#{@you} responded to ALL of the points on the #{opinion_survey_link}#{self}".html_safe
```

**Comment by dkubb** [comment]
@tjchambers mutant transforms the AST. A string like that would be broken up into chunks in the AST, with the latter chunk being '.'. Mutant transformed the node for '.' into `nil`.

To fix this you will want to write some code that asserts what the output string will be, including that last character. I don't know what your specs look like now, but maybe you're using a regexp pattern that doesn't use the `\A` and `\z` anchors?

**Comment by dkubb** [comment]
In general if I was writing specs to assert some string output I would use the strongest possible assertion, like:

```ruby
expect(subject.survey_responded_eval).to eql('...')
```

If I was going to use a regexp I would make sure to assert the start *and* end of the string:

```ruby
expect(subject.survey_responded_eval).to match(/\A...\z/)
```

**Comment by tjchambers** [comment]
@dkubb Yes I added a RegExp matcher for that. Just was wondering what the purpose of the conversion was. Is the transform of node '.' to nil or self for eval mutations?

**Comment by dkubb** [comment]
@tjchambers from the pov of mutant the string `'.'` isn't special. It's no different from mutating `[1, 2, 3]` into `[1, 2, nil]` or `[1, 2, self]`.

The `nil` replacement is a simple way of identifying cases where the output wasn't being asserted strongly enough. The `self` mutation helps identify cases where a method was using something exactly equivalent to the current object, eg: (this is a stupid example but I hope you get the idea)

```ruby
class Customer
  def create_order
    customer = self
    Order.create(customer)
  end
end
```

Or:

```ruby
class Customer
  def create_order
    Order.create(Customer.new)
  end
end
```

In this latter example, maybe there's only one test on `#create_order` using a new customer. Maybe the intention of the developer *is* that the order always be created with a new customer; by swapping in `self` in place for `Customer.new` it highlights a missing spec needed where `self` is *not* equal to `Customer.new`.

**Comment by tjchambers** [comment]
@dkubb thanks.

My inference is then that if I had a string such as ".#{xyz}" that It would mutate to "#{nil}#{xyz}" requiring me to spec the leading '.' as well.

**Comment by dkubb** [comment]
> My inference is then that if I had a string such as ".#{xyz}" that It would mutate to "#{nil}#{xyz}" requiring me to spec the leading '.' as well.

Yes, it should. If you're not seeing this kind of failure but you are seeing the other, is it possible that you specified the prefix of the string only?

**Comment by tjchambers** [comment]
@dkubb I was just conjecturing what to expect - I don't have such an example in my app. Just trying to grok the meaning in a broader sense.

**Comment by mbj** [comment]
@tjchambers I think this question was fully answered.

In summary: ``"foo#{bar}baz"` is AST wise: `(dstr (str "foo") (begin (send nil :bar)) (str "baz"))`, 2 literal strings around a method call. Mutant replaces the literal components of the dstr.

If you want to kill such mutations a simple example that contains expectations for the literal components will kill all these.

```ruby
def format(bar)
  "foo#{bar}baz"
end
```

```ruby
it 'formats correctly' do
  expect(format("bar")).to eql("foobarbaz")
end
```

I'll close this issue for now.
