### ISSUE TITLE
Question: Mutating Unnecessary Namespacing

### ISSUE THREAD

**Issue by tjchambers** [mbj/mutant#367]
I have a number of modules I have been converting to a different namespace, and have noticed I have some overspecified namespacing as a result. Example:

```
module X
   BAZ ||= 1

   class Y
     def foo
        bar == X::BAZ
     end
  end
end
```

My question is does mutant attempt to remove the X:: and test that the namespace is really needed?

I am not sure what the AST exposes, or whether this is prudent, so I am open to this being silly and idiotic or error-prone.

**Comment by mbj** [comment]
> My question is does mutant attempt to remove the X:: and test that the namespace is really needed?

Yes it does. See the specification: https://github.com/mbj/mutant/blob/master/meta/const.rb#L5-L6

**Comment by mbj** [comment]
> I am not sure what the AST exposes, or whether this is prudent, so I am open to this being silly and idiotic or error-prone.

The AST exposes:

```
Foo::Bar
(const
  (const nil :Foo) :Bar)
```

**Comment by mbj** [comment]
I think this question is fully answered, closing this issue.

**Comment by tjchambers** [comment]
Sounds like I should have tested it more thoroughly. Sorry for the inquiry.

**Comment by mbj** [comment]
> Sounds like I should have tested it more thoroughly. Sorry for the inquiry.

Mutant does not mutate code outside instance methods and singleton methods. You might tested it there?

**Comment by mbj** [comment]
> Sorry for the inquiry.

Never say that again please, I'm totally fine to answer this questions. Also it helps me to finally write better documentation.

**Comment by digitalronin** [comment]
I think I have a related issue. In my project, mutant is telling me that my namespace is unnecessary, like this;
```
-    RepoAudit::ChecksFactory.build(c.type, c.metadata, c.arguments)
+    ChecksFactory.build(c.type, c.metadata, c.arguments)
```
But, if I remove the `RepoAudit::` from that statement, my specs fail.

Can anyone point me in the right direction for how to investigate this?

**Comment by mbj** [comment]
@digitalronin Its very likely that the specs mutant uses to kill this mutations are not covering the specs that fail on manual mutation application.

Which likely indicates your tests for this are in the wrong location.

**Comment by digitalronin** [comment]
Of course. I should have thought of that. Thanks, I'll look into it.

**Comment by mbj** [comment]
@digitalronin Note that mutant prints next to each subject (and the N alive mutations) the effectively selected specs. You can diff these against your assumption.

Also feel free to join the mutation testing slack channel to discuss your case in more detail.

**Comment by digitalronin** [comment]
OK, in case someone else has a similar problem, in my case it went away when I replaced this;
```
module A::B
    ...
```
...with this;
```
module A
  module B
    ...
```
After I did that, the namespace really was unnecessary.
So, rspec was wrong, mutant was right, and the module declaration was introducing ambiguity.

**Comment by mbj** [comment]
@digitalronin Yeah, in general

```
module A::B
  body
```

Is "not" what people think. Its not a short form for:

```
module A
  module B
     body
```

**Comment by digitalronin** [comment]
That's really interesting. Could you clarify that a little? What's the difference between the two?

**Comment by mbj** [comment]
@digitalronin The constant scope.

```
irb(main):001:0> module A
irb(main):002:1>   CONST_IN_A = :CONST_IN_A
irb(main):003:1> end
=> :CONST_IN_A
irb(main):004:0> module A::B
irb(main):005:1>   p CONST_IN_A
irb(main):006:1> end
NameError: uninitialized constant A::B::CONST_IN_A
Did you mean?  A::CONST_IN_A
        from (irb):5:in `<module:B>'
        from (irb):4
        from /usr/bin/irb:11:in `<main>'
irb(main):007:0> module A
irb(main):008:1>   module B
irb(main):009:2>     p CONST_IN_A
irb(main):010:2>   end
irb(main):011:1> end
:CONST_IN_A
=> :CONST_IN_A
```

**Comment by digitalronin** [comment]
Got it. Thank you.
