### ISSUE TITLE
Question: Mutated code recursive

### ISSUE THREAD

**Issue by tjchambers** [mbj/mutant#368]
I wanted to make you aware of an experience. I have a code snippet:

```
def title
    "#{subclass} - #{guba_category}"
  end

  alias_method :to_s, :title
```

which during mutation is mutated to:

```
def title
- "#{subclass} - #{guba_category}"
+ "#{self} - #{guba_category}"
  end
```

making it implicitly recursive. 

I cannot kill this mutant even by specifying the exact string I expect because during execution to test the altered code, the self reference causes some complete run time failure or crash. If I alter my code as mutated and execute in rspec the response is "Process finished with exit code 0".

Mutant reports this module as 2 unkilled mutations (correctly) and proceeds to exit normally. 

If I modify the code to eliminate the alias_method...

```
def title
    "#{subclass} - #{guba_category}"
  end

def to_s
  title
end
```

Then when tested with the mutated code the end result is a more controlled failure:

```
SystemStackError: stack level too deep
./app/models/align/analytics/pairs/subclass_guba_category_pair.rb:16:in `to_s'
./app/models/align/analytics/pairs/subclass_guba_category_pair.rb:12:in `title'
./app/models/align/analytics/pairs/subclass_guba_category_pair.rb:16:in `to_s'
./app/models/align/analytics/pairs/subclass_guba_category_pair.rb:12:in `title'
```

In this case I can add an equivalent example for #to_s duplicating #title example then I achieve 100% coverage.

As I stated above the process seems to fail in the case of using alias_method, whereas when explicit the recursion seems to be caught. This occurs outside of mutant. I didn't see this as an improper use of alias_method, so I expected that either way my example would kill the mutation, but inside a mutant run the exit 0 code seems to be swallowed by mutant and leaves me with an alive mutation, whereas the stack level error seems to be treated as a killed mutation. I am unsure that my assumption in that last statement is well founded. I did expect that an explicit #to_s method vs. alias_method approach in this case would not be any different (i.e. I expected the mutation to drive a Stack Level too deep error).

Thoughts?

**Comment by mbj** [comment]
> I cannot kill this mutant even by specifying the exact string I expect because during execution to test the altered code, the self reference causes some complete run time failure or crash.

That should kill the mutant. If it does not you might found a bug in mutant itself.

Can you create a small reproduction repo I can clone and run for myself? That would make debugging easier.

**Comment by tjchambers** [comment]
I would be happy to do so. Will be done in a couple hours after I clear out some support tickets.

**Comment by mbj** [comment]
Make sure you use the most recent mutant version, I know some very old mutant versions have problems in signalling with crashed children.

**Comment by tjchambers** [comment]
I was using 0.7.8 for this test. I believe latest is 0.8.0. I will upgrade and retest, unless you want me to use a different version.

**Comment by tjchambers** [comment]
My bad. I was actually using 0.8.0.

**Comment by mbj** [comment]
> I was using 0.7.8 for this test. I believe latest is 0.8.0. I will upgrade and retest, unless you want me to use a different version.

I think both `0.7.8` and `0.8.0` are "free" from known signalling issues. `0.8.0` is most recent. So both would be fine for a reproduction.

**Comment by tjchambers** [comment]
OT - I have been thinking that since I am accumulating logs of mutant runs for all my modules putting the mutant version number AND a timestamp in the final coverage output would be very handy for reference.

**Comment by mbj** [comment]
> OT - I have been thinking that since I am accumulating logs of mutant runs for all my modules putting the mutant version number AND a timestamp in the final coverage output would be very handy for reference.

Good idea, can you open an issue for that. Its easy to add.

**Comment by tjchambers** [comment]
will do.

**Comment by mbj** [comment]
Related feature requests where added in #369 and #370.

**Comment by tjchambers** [comment]
Here is the repo: https://github.com/tjchambers/alias_method_recursion_test

**Comment by mbj** [comment]
@tjchambers Can you get me the exact CLI you used? Also: The crash.txt does not include the full report, can you get me that also.

I want to make sure I can reproduce your case exactly.

**Comment by tjchambers** [comment]
CLI? Sorry.

**Comment by mbj** [comment]
@tjchambers The exact mutant command you used.

**Comment by tjchambers** [comment]
Sorry.

```
mutant --include lib/foo.rb --use rspec --require ~/projects/alias_method_recursion_test/lib/foo.rb Foo
```

**Comment by mbj** [comment]
thx, I'll look into it the next OSS cycle.

**Comment by tjchambers** [comment]
Added crashdump.txt to the repo with the actual SIGABRT.

**Comment by mbj** [comment]
@tjchambers Is this still a problem? If not, lets close this issue!

**Comment by mbj** [comment]
@tjchambers I just realized you have a debug repository attached, I'll find some time and re-test your scenario. Sorry this takes so long and this issue was forgotten by me.

I do not have much OSS time these days.

**Comment by tjchambers** [comment]
Let me re-validate the issue. I took a quick look at recent logs for the same situation and I am not seeing this issue represented in the log. So I will take my time to revalidate and close or indicate it is reproducible.

**Comment by mbj** [comment]
Lets close this for now as it was not reproduced in 3y.
