### ISSUE TITLE
Question: Purpose of negation of *conditional*

### ISSUE THREAD

**Issue by tjchambers** [mbj/mutant#378]
I have the following mutation:

```
evil:Aoth8#establish:/Users/tj/projects/AOT/aotv2/app/models/perform/aop/details/aoth8.rb:23:e028f
@@ -1,16 +1,16 @@
 def establish
-  aop.aoev3 || aop.create_aoev3
+  !(aop.aoev3 || aop.create_aoev3)
   self
 end
```

Two thoughts: 

- Not sure I understand what the value of this mutation is given it is not the final line in my method (not the return value). It would seem that both the unmutated and mutated code would execute similarly
- Leaving my second question to be HOW to kill this mutation?

My inference is that it is a mutation without the context(i.e. it doesn't know this is not the last line in the AST).

Thoughts?

**Comment by mbj** [comment]
@tjchambers This is a known problematic mutation, we have a ticket for this here: https://github.com/mbj/mutant/issues/287

Till I have the time to do this, you can try to formulate your code via `if/unless` control flow modifiers.

```ruby
def establish
  aop.create_aoev3 unless aop.aoev3
  self
end
```

Is semantically equivalent, but will be mutated properly.

**Comment by mbj** [comment]
@tjchambers This mutation was removed in #287, you might be interested in the additional discussion in this ticket.

**Comment by tjchambers** [comment]
Thanks - I see the discussion - illuminating.
