### ISSUE TITLE
Learning: Using constants in Spec Examples

### ISSUE THREAD

**Issue by tjchambers** [mbj/mutant#379]
Just wanted to record this learning I experienced today for posterity. 

I was getting an alive mutation: 

```
 def indication_value(property, target = "")
-  if property.eql?(OeTag::AI_OPTION)
+  if property.equal?(OeTag::AI_OPTION)
     return aiconverged
   end
 ...
 end
```

... which at first was very unusual given it was comparing string values with `equal?` . My spec test was:

```
 it 'returns the appropriate ai' do 
      expect(a.indication_value(OeTag::AI_OPTION).to_f).to equal(66.2)
 end
```

where the constant I passed was defined as: 

```
AI_OPTION ||= 'ai'.freeze
```

It took me a couple minutes of head scratching to realize that I was passing a string constant in the example to a method that was comparing to that same exact constant, and even though it was a string it was the exact same string Object. 

So I changed my spec to add `.dup` : 
```
 it 'returns the appropriate ai' do 
      expect(a.indication_value(OeTag::AI_OPTION.dup).to_f).to equal(66.2)
 end
```
which eliminates the alive mutation.

**Comment by mbj** [comment]
You *could* also change your code to use `Object#equal?` because you might *want* that people only use *this specific string instance* when driving your API.

But as string is a core primitive I do not see a reason to do so.

**Comment by tjchambers** [comment]
The property is as you might infer from a database field. So it in this case requires a string comparison unless I change it to a numeric value in the database.

**Comment by mbj** [comment]
Than your solution will be fine. 

Just to make it clear: your spec verifies behavior on use of equivalent strings, NOT what the string that triggers special behavior actually *is*.

For that reason, I sometimes tend to repeat literals in specs.

**Comment by tjchambers** [comment]
By repeat do you mean you duplicate the string in the spec and NOT use the constant? I have avoided that to avoid "fragility"?

**Comment by mbj** [comment]
@tjchambers Sometimes I prefer to repeat the literal value of the constant in the spec. For "spec as documentation proposes".
