### ISSUE TITLE
Out of repository subjects under incremental mutation run

### ISSUE THREAD

**Issue by dkubb** [mbj/mutant#382]
When running with the `--since` flag subjects outside the repository are being flagged as changed.

For example, when running against spree, the `/home/ubuntu/spree/vendor/bundle/ruby/2.1.0/gems/paranoia-2.1.3/lib/paranoia.rb` file is being identified as changed, which is causing an error since it's outside the git repo.

**Comment by mbj** [comment]
> /home/ubuntu/spree/

Actually I think this *is* the git repo. To be clear we are talking about untracked objects *inside* the git repo.

**Comment by dkubb** [comment]
I think it's underneath the git repo path, but not *part* of the git repo itself. The `vendor/bundle` path is likely git ignored.

**Comment by mbj** [comment]
True, but still inside the repository, I doubt that matters, just wanted to be clear on it.

**Comment by dkubb** [comment]
@mbj I wouldn't be surprised if there was a generic command to test if a specific file was being tracked by git. This would filter out files that are explicitly git ignored, as well as files outside the repository (assuming it were even possible for them to be selected in the first place).

**Comment by mbj** [comment]
@dkubb there is. I just wounder if I can avoid shelling out 2 times per subject.

**Comment by dkubb** [comment]
> I just wounder if I can avoid shelling out 2 times per subject.

I suppose it would be possible to chain together a few bash commands using `&&` and `||` so you can run git log only if `git ls-files --error-unmatch -- <filename>` returns true.

**Comment by mbj** [comment]
> I suppose it would be possible to chain together a few bash commands using && and || so you can run git log only if git ls-files --error-unmatch -- <filename> returns true.

Thats true, but I effectively shell out 3 times than (1 shell + 2 subcommands), and also need to construct a shell CLI, that means I've to do escaping. Right now I'm using internally 2 times execve that is save from escaping issues.
