### ISSUE TITLE
AR Savepoint missing when running parallel mutations

### ISSUE THREAD

**Issue by tjchambers** [mbj/mutant#390]
I just wanted to record this highly reproducible behavior for others should they encounter it. 

My context is I am running mutant in -j8 mode (8 parallel jobs) with rspec against a Rails app with FactoryGirl creating some of my test data. On certain modules I get:

```
WorkbookTemplate
  #effects
    connects the effects (FAILED - 1)

Failures:

  1) WorkbookTemplate#effects connects the effects
     Failure/Error: let(:workbook_template) { create(:docx_template, tenant_id: 3608) }
     ActiveRecord::StatementInvalid:
       Mysql2::Error: SAVEPOINT active_record_1 does not exist: ROLLBACK TO SAVEPOINT active_record_1
```

ActiveRecord (and RSpec) mutations for this module work fine in -j1 (non parallel) mode. The situation above reports itself as a potential mutant bug or unparser bug but it is NOT. It is a condition where AR creates a savepoint and then inserts a record in the database and releases the savepoint. In a second parallel mutation worker AT THE SAME time (race condition) AR creates the savepoint, attempts to insert the record and FAILS due to a DB constraint violation (the other processes record conflicts on a unique key). Since the first process has released the savepoint already, when the second process attempts to rollback due to the constraint error from the DB it fails to find the savepoint. 

This is unique to MySQL (I believe) and also to activerecord processing. I believe this could occur in any normal operation (even in production) should these 2 operations occur in close timing proximity, but it is exacerbated in mutation testing with a highly active set of parallel workers. 

In my particular situation I thought of a number of possible workarounds which all involve avoiding the DB constraint violation:

- Make the content of the created FactoryGirl factory for this model unique (eliminate the duplication)
- Do not save the record (use build or build_stubbed)
- add db locking to the test (yuk!)
- add db locking to the method under test (double yuk!)

For my purposes option 2 was sufficient, and had it not been I would have attempted to use option 1 and change the factory definition.

**Comment by mbj** [comment]
The only generic known way around concurrency issues of shared mutable state (the DB is nothing more than a global variable of high complexity) is using a database that supports serializable transactions, and opening such a transaction for each example that touches the DB, while NOT committing it after the example finishes.

We use this successfully on a commercial project to run mutant under concurrency while touching the DB.

I consider to find the time to opensource this component. //cc @andrzejkrzywda - we talked about that one in our podcast recording.

I'll close this issue, as its not a mutant bug, nor a clear feature request and was meant as a starting point for a discussion. Feel free to continue discussion.

**Comment by tjchambers** [comment]
@mbj Thanks for your comments. I hope you approve of my capturing my "experiences" for you and others to discuss. As you can see I opted for NOT committing the data to the DB as my alternative. I suspect there are other possible ActiveRecord options I did not consider - like declaring a transaction.

Thanks for your insights.

**Comment by mbj** [comment]
> As you can see I opted for NOT committing the data to the DB as my alternative

That is what I prefer, through there are legacy libs I need to work with that require DB interaction, here the strategy I outlined is an alternative.

**Comment by tjchambers** [comment]
@mbj My unit tests are a bit more than that due to ActiveRecord and DB requirements. I very much appreciate your external viewpoint on these issues as it helps me expand my thinking. I avoid as much as possible the use of the DB in the tests for obvious performance reasons. I do have 100% control over the app which is the good part.
