### ISSUE TITLE
Infinite test run w/ a group of sequences

### ISSUE THREAD

**Issue by dgollahon** [mbj/mutant#392]
In a gem i released called identified I have a file where I create an array with a very specific sequence of numbers using the line below:

```ruby
[*(1..9).step(2), *(10..98).step(2), *(2..8).step(2), *(11..99).step(2)]
```

Mutant hangs and never shows any useful output when the method is covered by the mutant selector. It's currently just ignored in my mutant.yml. The context of the source can be found here: https://github.com/dgollahon/identified/blob/master/lib/identified/ssn/sequential_group_number.rb

@mbj, this is what i showed you on the hangout w/ @backus.

Would be interested to know why it fails.

**Comment by mbj** [comment]
Thx for the report. I'll look into this the next OSS cycle.

**Comment by mbj** [comment]
I did not forgot the issue, but I did not had a pure OSS cycle for month. Just a heads up I still plan to look into this reporoduction.
