### ISSUE TITLE
Difference between noop and neutral mutation?

### ISSUE THREAD

**Issue by backus** [mbj/mutant#403]
I'm adding some explanation to the README right now on reading mutant's output and I wanted to make sure I have it right regarding the different mutation cases:

- `evil` - a mutation of your source was not killed by your tests
- `neutral` your original source was injected and one or more tests failed
- `noop` your unparsed source was injected and one or more tests failed
   + You should not encounter this flag often. Consider opening an issue if you encounter a `noop` mutation

is this correct?

**Comment by mbj** [comment]
Mostly. Right now mutant does not produce `noop` mutations. They are intend for equivalent expansions. Example for a `noop`: Expanding `a += b` in domains where it *should* be equivalent for `a = a + b`. These are not yet implememented.

I wounder if we should swtich the names `neutral` and `noop`. Noop would IMO be the better name for "do nothing to the source self test", where `neutral` would be such an expansion above.

**Comment by backus** [comment]
Shall I just not document noop mutations then?

**Comment by mbj** [comment]
@backus Yeah, lets ignore them. They are defined in the source but not produced. When we switch the naming a simple gsub will keep the docs upto date.

**Comment by backus** [comment]
:thumbsup:
