### ISSUE TITLE
Question: how to kill Time-related mutations?

### ISSUE THREAD

**Issue by tjchambers** [mbj/mutant#409]
Looking for a suggestion on how to kill the following mutation:

```
@@ -1,8 +1,8 @@
 def expired?
   if expires_at
-    expires_at < Time.now
+    expires_at <= Time.now
   else
     false
   end
 end
```

Obviously I need to compare quality with a Time that is in *motion*. Would appreciate any guidance. I have tried using TimeCop in the past, but if I recall it caused issues in mutant. I can try that gem again if it is suggested.

**Comment by dkubb** [comment]
You could do something like this to freeze time:

```ruby
before do
  expect(Time).to receive_messages(now: Time.now)
end
```

Often, if the time value itself isn't important, just that it be a Time object, I will set the time to a known value using `Time.at(0)`.

**Comment by mbj** [comment]
I agree with @dkubb, `Time.now` is effectively an IO operation with indeterministic results. To run MA against it you need to control the IO operation.

**Comment by tjchambers** [comment]
@dkubb Thanks - worked perfectly.
