### ISSUE TITLE
Enhancement: AR Relations.none to []

### ISSUE THREAD

**Issue by tjchambers** [mbj/mutant#410]
Based on the following output:

```
evil:SubclassStatistic#partial_respondents:/Users/tj/projects/AOT/aotv2/app/models/align/subclass_statistic.rb:23:2e0aa
@@ -1,6 +1,6 @@
 def partial_respondents
   subclass.try do
     partial_respondents(assessment)
-  end || Respondent.none
+  end || self
 end
-----------------------
evil:SubclassStatistic#partial_respondents:/Users/tj/projects/AOT/aotv2/app/models/align/subclass_statistic.rb:23:af00e
@@ -1,6 +1,6 @@
 def partial_respondents
   subclass.try do
     partial_respondents(assessment)
-  end || Respondent.none
+  end || Respondent
 end
-----------------------
evil:SubclassStatistic#partial_respondents:/Users/tj/projects/AOT/aotv2/app/models/align/subclass_statistic.rb:23:a89e7
@@ -1,6 +1,6 @@
 def partial_respondents
   subclass.try do
     partial_respondents(assessment)
-  end || Respondent.none
+  end || self.none
 end
```

there is mutation of ActiveRecord_Relation types going on. It is my inference that this is PORO manipulation (although the last mutation would only be workable on an object that responded to #none). 

By that I mean I do not infer mutant recognizes these specifically as ActiveRecord relations. 

Because the relations behave so differently than standard enumerables, I was wondering if a mutation of 

XYZ.none -> [] 

would make sense? Or even be possible? I may be mistaken as this is *downgrading* the type rather than upgrading it. I am thinking that relations have many methods normal enumerables do not, and the ones that they share are often implemented differently. Also enumerables have additional methods not found on AR relations. 

Thoughts?

**Comment by mbj** [comment]
In general: I'm a bit reluctant to add rails specific mutations. I always wanted mutant to be generic.

Specific to this mutation: I think its a bad idea. Because the proposed mutation would change the type of the expression very drastically. And `Array` instances are not a clean semantic reduction from `Relation` instances.

They have a huge API intersect, but its disjunctive.

I'll close this issue, and I'd be very happy to see the above argument challenged with arguments I'm not aware off.

**Comment by tjchambers** [comment]
I know of your love for Rails :).

I do believe that choosing NOT to add this mutation IS the correct option for all my reasons above. Just wanted to have open discussion about it.
