### ISSUE TITLE
Strange sequence of reporting mutation progress

### ISSUE THREAD

**Issue by tjchambers** [mbj/mutant#411]
Please feel free to close this, but I wanted to report that I have one module where the mutations processed does not monotonically increase:

```
Requires:        ["./config/environment.rb", "point_theme.rb"]
(00/75)   0% - killtime: 0.00s runtime: 0.00s overhead: 0.00s
(00/75)   0% - killtime: 0.00s runtime: 1.01s overhead: 1.01s
(07/75) 100% - killtime: 5.02s runtime: 2.04s overhead: -2.98s
(00/75)   0% - killtime: 0.00s runtime: 0.00s overhead: 0.00s
(13/75) 100% - killtime: 9.03s runtime: 3.04s overhead: -5.99s
(21/75) 100% - killtime: 17.81s runtime: 4.05s overhead: -13.75s
(28/75) 100% - killtime: 21.97s runtime: 5.07s overhead: -16.90s
(34/75) 100% - killtime: 25.56s runtime: 6.08s overhead: -19.48s
(40/75)  97% - killtime: 31.90s runtime: 7.10s overhead: -24.80s
(47/75)  97% - killtime: 38.18s runtime: 8.12s overhead: -30.06s
(55/75)  98% - killtime: 43.12s runtime: 9.12s overhead: -34.00s
(61/75)  98% - killtime: 46.72s runtime: 10.14s overhead: -36.58s
(68/75)  98% - killtime: 50.96s runtime: 11.16s overhead: -39.80s
(74/75)  98% - killtime: 56.70s runtime: 12.16s overhead: -44.54s
```

Note the 4th entry is reporting 00/75 after having already advanced to 07/75. It varies slightly but this is the first module where that reporting has that behavior. This seems to be reproducible with this module, but only with this module.

**Comment by tjchambers** [comment]
For context this is an unusual module that has only private methods - no public methods.

**Comment by mbj** [comment]
Can you post a stable reproduction?

**Comment by tjchambers** [comment]
I will try to do so - since it is an AR model and complex I will have to play with it to try and maintain reproduction while simplifying it.

**Comment by mbj** [comment]
@tjchambers I can also offer to sign an NDA and check your project out.

**Comment by tjchambers** [comment]
I tried running it a few more times and now it is not showing that behavior any longer. It showed similar to the above at least 3 times. I am running on a 4 core processor with hyperthreading so it is running 8 jobs. I suspect it is sensitive to the timing of completion of those 8 concurrent workers.

**Comment by mbj** [comment]
I think that the 2nd occurence of this line:

```
(00/75)   0% - killtime: 0.00s runtime: 0.00s overhead: 0.00s
```

Is a duplicate, that I suspect:

* a) gets emit by mutant twice because of a bug
* b) your console generated because the console emulator is buggy (saw that once), especially with scrollback buffer handling

**Comment by tjchambers** [comment]
Re: b) These are being appended to a log file - not in console window.

**Comment by tjchambers** [comment]
I tried again and it showed failure:

```
Requires:        ["./config/environment.rb", "point_theme.rb"]
(00/75)   0% - killtime: 0.00s runtime: 0.00s overhead: 0.00s
(02/75) 100% - killtime: 1.13s runtime: 1.01s overhead: -0.12s
(00/75)   0% - killtime: 0.00s runtime: 0.00s overhead: 0.00s
(08/75) 100% - killtime: 6.49s runtime: 2.01s overhead: -4.48s
(14/75) 100% - killtime: 11.90s runtime: 3.03s overhead: -8.86s
(21/75) 100% - killtime: 18.30s runtime: 4.05s overhead: -14.26s
(28/75) 100% - killtime: 23.74s runtime: 5.06s overhead: -18.68s
(33/75) 100% - killtime: 26.56s runtime: 6.08s overhead: -20.48s
(37/75)  97% - killtime: 32.20s runtime: 7.08s overhead: -25.12s
(45/75)  97% - killtime: 39.62s runtime: 8.10s overhead: -31.52s
(52/75)  98% - killtime: 43.83s runtime: 9.11s overhead: -34.72s
(59/75)  98% - killtime: 47.98s runtime: 10.11s overhead: -37.87s
(65/75)  98% - killtime: 51.89s runtime: 11.13s overhead: -40.77s
(69/75)  98% - killtime: 56.07s runtime: 12.14s overhead: -43.93s
(74/75)  98% - killtime: 63.46s runtime: 13.14s overhead: -50.31s
```

**Comment by mbj** [comment]
k, so lets refute b).

I "hand wrote" all the concurrency primitives at use in mutant. There is only one thread at a time that should write into the stdout. So there must be a bug somewhere. I'd love to reproduce & fix this one.

**Comment by tjchambers** [comment]
I suspect it is extremely timing sensitive. And the specs are heavily AR involved so deeply db timing dependent. Let me think about this a bit.

**Comment by mbj** [comment]
The first thing I do on this kind of bugs, I try to increase the occurency of the bug. While reducing the amount of code hit.

**Comment by tjchambers** [comment]
I have only ever noticed this happening on startup, i.e. before the first N workers report where N = number of workers. Since I have 8 workers the 00/ always appears before 09/xx appears. So it feels like the initialization of the first run of workers starting may be at play. Just thinking out loud.

**Comment by mbj** [comment]
@tjchambers You could run with `-j1` to check if this duplicate still occurs. And maybe even `-j0` (here no actual work will ever be done).

**Comment by tjchambers** [comment]
@mbj I hear you about the way to encourage it, but there really is only one method I am specing. I will try first to reduce the specs.

**Comment by tjchambers** [comment]
@mbj I will try altering the -j parameter. I also have another system with 8 cores so I can exacerbate it there.

**Comment by mbj** [comment]
@tjchambers OT: Mutant scales to ~16cores, than the concurrency the MRI provides does not allow any more speedup. The GIL than begins to be the limiting factor with the concurrency primitive I use.

**Comment by mbj** [comment]
With faster tests the GIL also begins to hurt at 10cores. The more time the specs take the longer the GIL is not an issue. I suspect an AR heavy code base to scale much better.

**Comment by mbj** [comment]
Where than the DB concurrency is the bottleneck :P

**Comment by tjchambers** [comment]
OT but my experience with the 8 core (16 workers) is it scales quite well. The overall run times for the short modules are almost all the same - they bottom at about 15 secs (startup time).

**Comment by tjchambers** [comment]
I tested it 5 times with -j1 and no failures (and it is slooowww). 

I tested it with -j0 but since that does nothing it is not easy to tell anything. 

I then tried retesting it over and over outside my Rake environment. Still no failure. 

So I retested inside my rake environment and it is so much faster (it is the one where I specify the --pattern) and it fails about 50% of the time. SO it may be that because of the pattern it is accelerating the execution to the point of displaying the behavior. Bottom line is it hasn't failed except when I run it inside my rake environment:

```
File.write('/Users/tj/.rspec', "--pattern '#{spec}'")
cmd = 'RAILS_ENV=test bundle exec mutant ' + parms.join(' ')
puts "[#{Time.now.iso8601}] #{cmd}"
`#{cmd}`
```
Inside my rake env it runs at least 2x - perhaps 4x as fast as outside it. 

So I am going to try and push it to 8 cores inside rake env on the other machine, and also run it -j1 inside Rake env. to see if I can get a consistent repro.

**Comment by tjchambers** [comment]
Am only able to reproduce about 50% of time and ONLY when using -j8 with 4 cores (8 workers). -j1 always is monotonic. and pushing beyond 8 cores does not exhibit the behavior (probably due to  natural Rails/Ruby/Db bottlenecks). 

Suggestions? Is there anything I can do to provide more info?

**Comment by tjchambers** [comment]
This is not high priority so I need to do some other work. This thread is for your awareness. No untoward behavior outside of reporting seems to occur - all the mutations look consistently the same.

**Comment by mbj** [comment]
> This is not high priority so I need to do some other work. This thread is for your awareness. No untoward behavior outside of reporting seems to occur - all the mutations look consistently the same.

I'd simply put some debug statements into mutant than to find out where the duplicate print (and what state!) its originating from. I could show you how to do that in a paring / hangout with screenshare.

**Comment by tjchambers** [comment]
I don't have time at present to spend on this further, so if you could shoot my the name of the mutant module and what you would want to see re: state than I would be happy to take a shot at it when time permits. I want to be cognizant of both our time while recognizing this is a problem I will likely be the sole person able to reproduce. I am leaving this module alone for now so as not to change the conditions.

**Comment by tjchambers** [comment]
I must be doing something right (or wrong). Just had another module do this.

```
Requires:        ["./config/environment.rb", "monitor_os_task.rb"]
(00/105)   0% - killtime: 0.00s runtime: 0.00s overhead: 0.00s
(01/105) 100% - killtime: 0.33s runtime: 1.01s overhead: 0.68s
(03/105) 100% - killtime: 1.83s runtime: 2.01s overhead: 0.18s
(06/105) 100% - killtime: 6.31s runtime: 3.02s overhead: -3.29s
(00/105)   0% - killtime: 0.00s runtime: 0.00s overhead: 0.00s
(10/105)  90% - killtime: 16.34s runtime: 4.03s overhead: -12.31s
(12/105)  92% - killtime: 18.50s runtime: 5.04s overhead: -13.45s
(14/105)  93% - killtime: 20.09s runtime: 6.07s overhead: -14.03s
(21/105)  95% - killtime: 32.31s runtime: 7.07s overhead: -25.24s
(23/105)  92% - killtime: 37.69s runtime: 8.07s overhead: -29.62s
(25/105)  92% - killtime: 40.31s runtime: 9.08s overhead: -31.23s
(32/105)  91% - killtime: 52.59s runtime: 10.09s overhead: -42.50s
(36/105)  87% - killtime: 56.93s runtime: 11.09s overhead: -45.83s
(38/105)  82% - killtime: 60.65s runtime: 12.11s overhead: -48.54s
(43/105)  82% - killtime: 65.22s runtime: 13.11s overhead: -52.11s
(44/105)  83% - killtime: 66.08s runtime: 14.12s overhead: -51.96s
(44/105)  83% - killtime: 66.08s runtime: 15.12s overhead: -50.96s
(44/105)  83% - killtime: 66.08s runtime: 16.12s overhead: -49.96s
(44/105)  83% - killtime: 66.08s runtime: 17.13s overhead: -48.95s
```

**Comment by mbj** [comment]
@tjchambers As long I cannot repro this its very ineffective to help you here. I can offer to repro / fix it on your code base, or do a screenshare with you instructing you where to place the debug statements.

**Comment by tjchambers** [comment]
Please don't infer that my reporting additional occurrences is a complaint. I am just seeing it more often now on this faster processing loop - which gives me hope that I can locate the root cause. It's less intermittent than I inferred. I will take it upon myself when time permits to debug this as it is good experience and this issue doesn't seem to hurt anything. Consider it an investment in my self education.

**Comment by mbj** [comment]
I'm totally fine you hunt this down. Just wanted to state: There is right now nothing more I can tell you to help. I *could* point you to the debug statements I would add, but these would lead to more questions, feedback we'd have to serialized through this channel. And feedback time in an async medium such as GH issues is slow => Non efficient.

If you want to go on posting your findings: Please do. I'll read them and maybe I get another debug vector idea you could run through.

BTW: Can you confirm you are on the latest release? 0.8.2?

**Comment by tjchambers** [comment]
We're good. And I am NOT on 0.8.2 - still on 0.8.0. 

I was going to switch to that after I get about 60 more of these modules mutation tested since they will all need to be rerun again. I am about 300 done and 60 to go. I promise to debug this (after reproduction) on the latest at the time. Will not waste time on a old version.

**Comment by mbj** [comment]
There are some reporter changes between 0.8.0 and 0.8.2.

**Comment by tjchambers** [comment]
Thanks for the reminder - I have been monitoring those changes as well.

**Comment by mbj** [comment]
I'll close this issue for inactivity, and non reproducability in my environemnt.

@tjchambers If you have new information, feel free to re-open this issue.

**Comment by tjchambers** [comment]
I have seen it - including some cases where it is beyond the initial job size, but closing it is prudent until I can get something to reproduce.

**Comment by mbj** [comment]
> I have seen it - including some cases where it is beyond the initial job size, but closing it is prudent until I can get something to reproduce.

Yeah, the issue tracker should be for "eligible to work on issues".
