### ISSUE TITLE
Remove mutation super() -> super

### ISSUE THREAD

**Issue by backus** [mbj/mutant#414]
Right now we have both mutations `super` -> `super()` and `super()` -> `super`. Since (according to #309) we view `super()` as the more primitive option we should remove `super()` -> `super`.

**Comment by backus** [comment]
With this said, I think it still makes sense to mutate `super(foo, bar)` -> `super()` and `super`, so I guess the `super()` -> `super` implementation should depend on whether it was given arguments.  Would like to hear your input here @dkubb and @mbj

**Comment by mbj** [comment]
Ack. Interesting we did not spotted this on #309.

**Comment by mbj** [comment]
This was fixed with https://github.com/mbj/mutant/pull/418.
