### ISSUE TITLE
Blind spot on the rhs of op assigns

### ISSUE THREAD

**Issue by tjchambers** [mbj/mutant#421]
I am seeing this mutation of my code (please no chiding for use of class variable - I am working through that):

```
 def self.background_user
-  @@bgu ||= self.find_by(email: BACKGROUND_USER)
+  @@bgu__mutant__ ||= self.find_by(email: BACKGROUND_USER)
 end
```

That is the only mutation left alive for this method.

For a separate method I see (and expected) a mutation of "self." to drop it as unnecessary:

```
 def self.current
   (Thread.current[:user] || if respond_to?(:current_user)
     current_user
-  end) || self.background_user
+  end) || background_user
 end
```

I was expecting a similar mutation of the former code but didn't see one. What makes these two examples different? I expected to see:

```
 def self.background_user
-  @@bgu ||= self.find_by(email: BACKGROUND_USER)
+  @@bgu ||= find_by(email: BACKGROUND_USER)
 end
```

**Comment by mbj** [comment]
All the op assign nodes `||=`, `&&=` and friends right now are badly implemented. And might not recurse into the right hand side. This is known but I think there is no ticket for this currently.

**Comment by tjchambers** [comment]
Ahh - ok. I am finding a significant number of these unnecessary "self." in my code as I review code I wrote when I was learning Ruby. Thanks for the explanation.

**Comment by backus** [comment]
I have a branch with failing specs for this issue here: [backus/mutant:fix/or-asgn-rhs-blindspot](https://github.com/backus/mutant/blob/fix/or-asgn-rhs-blindspot).  The implicit self is not emitted because of the condition here: [lib/mutant/mutator/node/send.rb#L161](https://github.com/backus/mutant/blob/fix/or-asgn-rhs-blindspot/lib/mutant/mutator/node/send.rb#L161)

**Comment by backus** [comment]
I'm not exactly sure why `OP_ASSIGN`s were excluded, but the commit introducing the condition mentions generating invalid ASTs: https://github.com/mbj/mutant/commit/3d94003616cfbca9e1d81bb047fbd19c0d9c217e.  Specs still pass dropping the condition, so I can open a PR with these changes if that makes sense @mbj

**Comment by mbj** [comment]
@backus The guard is to restrictive. But includes a prevention for invalid ASTs in another case. Simply remove that guard and see specs failing to see those cases.

**Comment by mbj** [comment]
The solution is to be more precise in guarding against invalid AST.

**Comment by backus** [comment]
Removed the guard and specs passed when I ran them on my fork: https://circleci.com/gh/backus/mutant/2

**Comment by mbj** [comment]
could also be another leftover from before the state we switched the "tricky" sends into dedicated sub-classes.

**Comment by backus** [comment]
Opened a PR if you want to take a look

**Comment by mbj** [comment]
> Opened a PR if you want to take a look

Thx. But I'm too busy for today and probably the next days. Sorry for that.

**Comment by mbj** [comment]
@backus I'm very happy your contribution activities exceed my OSS budget, even when I dedicate it to reviews :P

**Comment by backus** [comment]
:smile: I'll slow down a lot once my vacation is over.  Always happy to help when I'm free though.

**Comment by mbj** [comment]
@backus I do not ask you to slow down. Just to accept low quality comments of mine, and very late reviews :P

**Comment by backus** [comment]
Yup I understand. You do a good job maintaining mutant I have no complaints
