### ISSUE TITLE
Mutate `receiver.const_get(:LITERAL)` into `receiver::LITERAL`.

### ISSUE THREAD

**Issue by tjchambers** [mbj/mutant#422]
In my code I have used two variations of access to class constants where I am referring inside a module:

```ruby
self.class.const_get(:ADMIN_ROLE)
```

and...

```ruby
self.class::ADMIN_ROLE
```

My question is are these entirely equivalent? Is one better than another for any reason? Is there an opportunity for a mutation here that would be constructive? Is the most succinct way better?

**Comment by mbj** [comment]
Using `.const_get` IMO only makes sense when the constant name is dynamically computed. In all cases where a constant name is given literally almost always, unless you reflect private constants for documentation generation proposes, the literal form (example `self.class::ADMIN_ROLE`) is to prefer.

And yes, I think we could turn this into a mutation. One that is triggered when the argument to const get is a non interpolated symbol or string literal.

This will be a valid mutation with and without explicit receiver.

**Comment by tjchambers** [comment]
@mbj Thanks, I will settle with the ::LITERAL usage in my code.

**Comment by tjchambers** [comment]
I would add that mutating self.class::LITERAL to LITERAL would be a nice test in places in my code!

**Comment by mbj** [comment]
@tjchambers This is already being done: https://github.com/mbj/mutant/blob/master/meta/const.rb

**Comment by tjchambers** [comment]
I seem to recall having this conversation before, but I also feel like self.class::LITERAL is not mutating in my code. I will have to find an example to confirm or deny that statement! Thanks.
