### ISSUE TITLE
Class/Module mutator?

### ISSUE THREAD

**Issue by backus** [mbj/mutant#429]
I'd like to implement #17 and in order to do so I'm thinking we need a mutator class for `Class` and `Module`.  Any reason this doesn't exist currently / any opposition to adding it?

**Comment by mbj** [comment]
@backus I think that the public / private visibility mutations for instance and singleton methods are best done as part of the `Mutant::Subject::Method` classes.

**Comment by backus** [comment]
Ah alright.  I wasn't sure if the `Mutator` namespace is / is supposed to be fully decoupled from things like `Subject::Method`.

**Comment by mbj** [comment]
@backus The visibility cannot be seen from the AST nodes. I'm fine to inject some "special" not very AST specific mutations from the subjects.

**Comment by mbj** [comment]
@backus I think we can close this question, as I think it was answered. If you disagree feel free to reopen and expand your question.
