### ISSUE TITLE
Add mutation `Date.parse` → `Date.iso8601`

### ISSUE THREAD

**Issue by backus** [mbj/mutant#432]
`Date.parse` is extremely liberal with what it will try to parse:

```ruby
> ['2015-01-01', '10001', 'September', 'I may be a false positive'].map(&Date.method(:parse))
 => [
  #<Date: 2015-01-01 ((2457024j,0s,0n),+0s,2299161j)>,
  #<Date: 2010-01-01 ((2455198j,0s,0n),+0s,2299161j)>,
  #<Date: 2015-09-01 ((2457267j,0s,0n),+0s,2299161j)>,
  #<Date: 2015-05-01 ((2457144j,0s,0n),+0s,2299161j)>
]
```

and it exposes a lot of more conservative parsing methods: `[:jd, :civil, :strptime, :iso8601, :rfc3339, :xmlschema, :rfc2822, :rfc822, :httpdate, :jisx0301]`

**Comment by mbj** [comment]
@backus, good idea. I think we need to mutate to each of the specialized parsers. If you *really* wanna use `Date.parse` you should be able to provide inputs for supersets of the specific parsing cases.
