### ISSUE TITLE
Mutating #to_i to #to_int seems odd

### ISSUE THREAD

**Issue by dogweather** [mbj/mutant#447]
I have this report of a successful found mutant:

``` ruby
 def self.dollar_string_to_int(a_string)
-  (a_string.to_f * 100).to_i
+  (a_string.to_f * 100).to_int
 end
```

I'm not really sure what to make of this; my first thought is that this isn't a mutation which should be run. (?)

**Comment by mbj** [comment]
Mutation operators in ruby are derived from 2 core axioms:

* Orthogonal replacment
* Reduction of semantics

This one is derived from the reduction of semantics one .`#to_i` includes `#to_int` by definition. But not vice versa.

* `#to_i` is for objects that have a unique (maybe injective) representation as Integer.
* `#to_int` is for objects that have are effectively an Integer

So `#to_int` is the more primitive (less powerful) API, if supported.

Types in ruby are "omniversal polymorphic": AKA each object is its own type. Right now your code states: I work on every object (returned by `(a_string.to_f * 100)`) that offers `#to_i`. Mutant sees that any object that offers `#to_i` should also offer `#to_int` (but not vice versa) and with this, currently alive, mutation asks you:

Can you provide an example where your object only (in form of test) that you can have an input where `#to_int` is not provided by the interface. If you cannot: Use the less powerful `#to_int` interface as you have no reason to provide support for the more wider (and implemented by much more objects) `#to_i` interface.

I'll close this issue as I think the question was answered. Feel free to continue discussion on the closed issue.

**Comment by dogweather** [comment]
Very very interesting. I'll need to think about this!

**Comment by mbj** [comment]
@dogweather There are many other inhabitants of the reduction operators. `#==` to `#eql?` to `#equal?` etc. `a; b` => `a`. Feel free to post the results of your thoughts here. I like my assumptions challenged.

**Comment by dogweather** [comment]
Is it possible that this philosophy conflicts with the Ruby API design & style? Not a bad thing per se. I understand you to be saying that (e.g.) `#to_int` has a smaller input domain, yet it can still pass the test. Therefore, it should be prefered over `#to_i`.

This seems to conflict with the intent of `#to_int`, `#to_str`, and others: they serve as [duck type markers](http://www.rubyfleebie.com/to_i-vs-to_int/). But that blog post is unsourced, and [the Ruby API only describes the implementation](http://ruby-doc.org/core-2.2.0/Float.html#method-i-to_int) of `#to_i` vs. `#to_int`, not it's intended use. (!)  So this duck-type-marker-purpose might be a minority view.

Back to my code, the best option is actually for me to re-write it as,

```ruby
(a_string.to_f * 100).round
```

...and I also see that all mutants are killed. (Likely because `#round` doesn't trigger a similar substitution.) Now **this** is interesting to me, because I assumed that Mutant's purpose was to encourage changes to the _test_ code, not the implementation. I.e., do my tests cover the purportedly correct source code? However, Mutant's results will vary widely depending on the implementation, not just the tests.

For me, personally, this is still very useful because it leads to higher code quality — the real goal.

**Comment by mbj** [comment]
@dogweather For many classes `#to_i` and `#to_int` are identical, especially in the corelib.

But there are many classes that implement to `#to_i` that do not implement `#to_int`. Example `String`. Mutants mutation operators are based on two axioms, the more important one is:

* Always mutate to least powerful version of the code.

Where the use of a more narrow object interface (`#to_int`, '#to_str`, `#to_hash`) is more primitive, as its implemented by less classes, so your API works with the more correct subset of all cases.

You do not want to end up with code that uses `#to_i` where after a refactoring you introduce a bug where your receiver is NOT a `Float` anymore, it might be a `String` where `#to_i` silently works, but `#to_int` would blow up.

I agree this kind of defense in depth strategy might look overly pessimistic. But mutant is made for a specific propose: Helping me with delivering useful software for my clients that usually have *huge* code bases. Where the receiver of a `#to_int` or `#to_i` can be very dislocal, obfuscated by various layers of legacy (rails, and the whole `active*` ecosystem are a huge part of that legacy source).

IMO ~80% of mutants mutation operators are specific to mitigating (sadly not solving) conceptual dynlang weaknesses. They'd not even exist on a decently typed language.

> Now this is interesting to me, because I assumed that Mutant's purpose was to encourage changes to the test code, not the implementation. I.e., do my tests cover the purportedly correct source code? However, Mutant's results will vary widely depending on the implementation, not just the tests.

Mutants goal is NOT to force people adding more tests. Its goal is to reduce the gap between tests and actual implementation. In my projects, 95% of the cases killing an alive mutation is about reducing code, not adding a test. And reducing redundant / dead code is IMO much better than adding more test - code.

**Comment by mbj** [comment]
And BTW: I agree that `#round` is the much better API usage. That floats implement `#to_int` is IMO plain wrong.

**Comment by dogweather** [comment]
Hi, I'm coming back here because this subject really taught me a lot about Ruby and writing higher quality code. [This blog post about #to_a](http://zverok.github.io/blog/2018-02-02-to_a.html) reminded me of it.

I think it'd be great to have this concept written up somewhere as its own thing, maybe a blog post. I'd also really like to have these tests in a linter of some kind, like a Rubocop rule - brainstorming about it, that might not be hard to do.

**Comment by mbj** [comment]
@dogweather Feel welcome to write up docs about the subject, do talks or blog. But I cannot take the stab on doing this, when while I like the suggestion (and your comment is one?).

I'm simply to busy with paying clients (and getting more paying clients) than give away free work in the OSS.

I welcome PRs that add docs, but I cannot guarantee I can review them fast.

**Comment by mbj** [comment]
(reopen was a mistake, clicked wrong button).
