### ISSUE TITLE
Advice: external file name string mutations

### ISSUE THREAD

**Issue by tjchambers** [mbj/mutant#450]
Again I come looking for advice. In some of my code I am constructing in private methods a file path string. Sometimes these are for temporary files, sometimes logging files, and as well sometimes for Amazon S3 locations (also buckets are named dynamically). 

When this code is mutated as I would expect these strings are mutated. When these files are then created and written to, the files are created in various and sundry locations often far from the expected location (in my app directory, in my spec directory, in directory levels in the path to the original expected directory, etc.) . Obviously I can kill the mutations (although a bit more difficult by the fact the paths are constructed frequently in private methods). But the _damage_ is done so to speak, in that the files are already created at the termination of the mutated code run. Unlike rollback for DB transactions in RSpec, the files linger and clutter.

My current thinking is to separate the minor amount of code around the construction of the path name into a separate module and thereby create the path and kill that modules' mutations without having *written* the file. This has pros and cons, the pros being it is more SRP perhaps, and the con is that many of these files need the context info from the original module, so there is now a public API where there was a private one and a few elements of information needed to be shared. 

Of course there are other constructions possible. 

It would seem what I am trying to do at a higher level is to isolate mutations by servicing them in a safer environment (pre-usage of the path in file creation). My sense is this is part of a technique on how to construct code that will be mutated with side effects outside. 

In looking at the mutant code itself I don't see anything I recognize of a similar situation.

Any guidance on other approaches would be useful.

**Comment by mbj** [comment]
@tjchambers My advice is to abstract out the file system.

Wrapping all the various ways ruby allows to talk with the outside world in an object that supports the domain specific subset you need.

This way you can switch your application to a mock implementation on testing, without having to fear mutation testing leaves stale state in your file system. The mutation testing leaked state will go away with the memory that represents your mock implementation.

I realize this apporach does not scale easily to 3rd party gems that directly talk to the APIs I propose to be wrapped.

Here you can use rspec message expectations to intercept the calls before they are executed.

If you NEED file system IO as part of the spec suite that kills mutations, you can also prefix all file operations into an execution specifc temporary directory you can kill after the test runs.

This also fixes potential concurrency issues.

I think this question is fully answered with my post. If not feel free to reopen.
