### ISSUE TITLE
Add mutation `Hash#[]` → `Hash#key?`

### ISSUE THREAD

**Issue by backus** [mbj/mutant#456]
Reasoning being that

```ruby
do_action if options.key?(:setting)
```

is preferable compared to

```ruby
do_action if options[:settings]
```

**Comment by tjchambers** [comment]
@backus In the non-prefereable you are testing both the key and the resultant value, whereas in the *preferred version* aren't you just testing the key exists? Forgive me if mistaken.

**Comment by backus** [comment]
Yes, that is a possible use case of the second example.  Often though the second example is used as a key check since the missing key lookup returns nil.  If your condition is on the *value* of the hash value then a preferable conditional might be `if options[:settings].eql?('foo')`

**Comment by mbj** [comment]
And if you know the value is present do: `if options.fetch(:settings).eql?('foo')`
