### ISSUE TITLE
Unkillable self.included mutants

### ISSUE THREAD

**Issue by ch1c0t** [mbj/mutant#495]
I think I found a bug. The setup is [here](https://github.com/ch1c0t/unkillable--self.included--mutants).

Running `bundle exec mutant -I '.' -r wtf --use rspec 'M*'` yields 27 alive mutants :
```
Mutant configuration:
Matcher:         #<Mutant::Matcher::Config match_expressions: [M*]>
Integration:     Mutant::Integration::Rspec
Expect Coverage: 100.00%
Jobs:            2
Includes:        ["."]
Requires:        ["wtf"]
Subjects:        1
Mutations:       28
Results:         28
Kills:           1
Alive:           27
Runtime:         3.54s
Killtime:        0.41s
Overhead:        760.68%
Mutations/s:     7.92
Coverage:        3.57%
Expected:        100.00%
```
However, manual testing shows that they should be killed.

**Comment by backus** [comment]
change the spec to this

```ruby
require_relative '../wtf'
require 'devtools/spec_helper'

describe M do
  let(:klass) { Class.new }

  it 'sets value on include' do
    klass.include(M)
    expect(klass.value).to equal(42)
  end
end
```

and mutations should be killed.

**Comment by backus** [comment]
@mbj can explain this in more precise terms, but basically mutant loads your lib and specs on boot.  Since you defined `App` *outside* of rspec, `M` is only being included into `App` on boot.  When mutant later mutates the behavior of `included` it has no effect on the specs because `App` isn't being redefined each time the specs run.

**Comment by backus** [comment]
@ch1c0t could you close this if this answered your question?

**Comment by ch1c0t** [comment]
@backus Many thanks for the explanation.

**Comment by mbj** [comment]
To explain the invariant mutant relies on:

> The effect of changing the code-subject via a mutation needs to be observable by executing only the code of the test, excluding boot.

So what @backus is correctly proposing: Adding a test-time call side to code that was only called at boot time.

There is an idea to implement so called "boot time mutations" in mutant that would lessen the above constraint, but it would be much slower and generally not worth my limited implementors time.
