### ISSUE TITLE
Add mutation `#to_a` to `#to_set`

### ISSUE THREAD

**Issue by dkubb** [mbj/mutant#497]
Often developers use a primitive `Array` when they have no expectation of duplicate elements in a list, where a `Set` is more appropriate. This mutation will expose assumptions in code where an `Array` is used but a `Set` is better.

**Comment by mbj** [comment]
Yes. Set is much enough a subset in semantics to Array to warrant this as a reduction operation.

**Comment by tjchambers** [comment]
I believe this is a meaningful mutation, but the lack of support for Set as an Enumerable in ActiveRecord - not just lack but incorrect but valid SQL - has the potential IMHO to suggest a change to `to_set` is *suggested* and yet impacts will be strongly felt outside the mutated code. 

I am not against this mutation, but Set is not a UNIQUE Array variant.

**Comment by mbj** [comment]
> lack of support for Set as an Enumerable in ActiveRecord

WDYM exactly. If `#to_set` is not implemented the mutation will not be reported as an alive.

**Comment by dkubb** [comment]
> I am not against this mutation, but Set is not a UNIQUE Array variant.

I know, but in well written code it can usually stand in for much of what people expect from Array. If code does something that only works with an Array, then the tests should fail anyway.

**Comment by tjchambers** [comment]
For reference here is the discussion on support for Set in ActiveRecord

https://github.com/rails/rails/pull/19755

**Comment by tjchambers** [comment]
@bkubb I don't disagree, but passing a Set to another Class not under mutation test alters the behavior vs. Array being passed. That may happen with any code, not just Set vs. Array, but the inability to easily detect malformed SQL ELSEWHERE makes me pause when thinking about converting to a Set even when Set behavior IS what I want.

**Comment by dkubb** [comment]
One argument he makes is:

> This adds precedent for every other Enumerable, and we can't target Enumerable directly.

I'd like to know the reason why not? There's `Enumerable#to_a`. If you really do want an Array, then call `#to_a` inside your method. It'll work with all `Enumerable` objects. In the case of an `Array` it's super cheap. In this case duck typing solves the problem nicely and cleanly.

**Comment by tjchambers** [comment]
In this case specifically the difference between Set and Array in terms of ActiveRecord support is scaring me.

**Comment by mbj** [comment]
@tjchambers <evil-voice>Welcome to dynamic typing.</evil-voice>

And more constructive: If the difference is that important and mutant forces you to use `#to_set`, you should have a spec that "nails" the `#to_a` call, via asserting an instance of Array.

This is a case where mutant forces you to be more explicit about your expectations.

**Comment by tjchambers** [comment]
@dkubb I think the issue is who should call `to_a`. Certainly not the developer relying on ActiveRecord to be efficient and correct.

**Comment by tjchambers** [comment]
@mbj I support this mutation. But the `#to_a` call may need to be far away from the module under mutation.

**Comment by mbj** [comment]
> @mbj I support this mutation. But the #to_a call may need to be far away from the module under mutation.

If the `#to_a` call is not in the mutated subject, the `#to_set` will not be emitted.

**Comment by dkubb** [comment]
If you have a `#to_a`, but the tests continue to work with `#to_set` .. but the actual functionality is broken, doesn't that mean the test is broken since it doesn't actually test the thing you care about?

**Comment by tjchambers** [comment]
@dkubb It would seem that is the case, and I am not debating that. But the amount of change that is required to change to using a Set (only if it is passes into a where clause in ActiveRecord) has far reaching and invisible impact. 

The tests SHOULD prove that. The invisibility of it is what concerns me.

**Comment by tjchambers** [comment]
@mbj, @dkubb Just to be clear - I support this mutation. Changing MY code to use a Set is very concerning even if Set functionality IS what I want.

**Comment by kbrock** [comment]
I always feel `kind_of?(Array)` tests are a smell. We really don't need it to be an array, we just need the code to work. Is there another way to state "and works with active record"?

I think of mutations as best practices more than possible alternatives. So if a mutation pushes me towards code that is slower, less compatible, and or less practical, then I hesitate. I'm not so sure that using sets is a best practice.

**Comment by tuexss** [comment]
You're right, tests shouldn't look at which data structure is in use. But this mutation isn't for detecting whether you use a specific data structure, it is about using the simplest data structure available. For me it's a best practice to go for simpler and safer code, even if it's maybe not the easiest way to implement it. It's similar to methods with or without a `!` - in many cases it doesn't make a difference, but too often people tend to use the method without `!` where the one with the bang should be the default style. So this mutation isn't about telling "you shouldn't use array", it is about "you're using an array where an Enumerable or a Set would work just as well, are you sure you want to go that way?"

I don't think you want to say using sets is slower, less compatible and less practical. Sure, there are some tradeoffs, but if you don't use any methods/operators specific to arrays, chances are very high that you're trying to crack a nut with a sledgehammer.

**Comment by kbrock** [comment]
I overlook using `Set`. Maybe it is the fact that I have to `require 'set'` So the encouragement to use the simplest data structure is welcomed.

But I do wonder if using an`Set` is safer. If there is an easy test for me to ensure that it won't break other code, then that sounds good.

I would prefer if I didn't have to add the same boilerplate for common use cases like to_s, to_a or eql

**Comment by tuexss** [comment]
I totally understand your doubts. The last thing we want to have around is more to_s/to_a added to code.

What I'm concerned about is, when people use data structures randomly, as long as they do the job at hand. Not everything is an Array or a Hash, even in the ruby world. There are b-trees and sets, linked lists and stacks, ranges and many more. Writing better code means to identify which structure is needed by the data itself - it shouldn't even be a decision a programmer makes - it's the data that requires the structure. Abusing a similar structure instead of taking the right one is quite popular, especially because Arrays and Hashes in MRI are best known and easy to grasp. And they also have good overall benchmarks. But this leads to people seeing everything as a nail, just because they own a hammer. Sometimes it's just not an Array.

By reading about the methods available for different kinds of collections in Ruby will help to understand which one can do what. And by analysing your data you understand what you need to do with it. Then you find the smallest data structure that offers the methods you need for your data. It's like Occam's razor for programming. :)

**Comment by kbrock** [comment]
I agree that encouraging users to use the simplest data structure and/or code is best.
E.g.: often we use `gsub` when we could use `gsub!`, `sub`, or `tr` instead.

And while using a `Set` instead of an `Array` may be correct, people may be led into path with unintended/unknown consequences. E.g.: In a set, you are not supposed to modify records.

Again: Yes, lets encourage users to go for the simplest data structure. But I'm not convinced that `Set` is merely a simpler `Array`. In many ways it is more similar to a `Hash` than an `Array`.

**Comment by mbj** [comment]
> Again: Yes, lets encourage users to go for the simplest data structure. But I'm not convinced that Set is merely a simpler Array.

Mutant, to uncover semantic uncoverage applies operators to the code. These operators have to comply with one of the following ideas (or both):

A) The operator clearly reduces semantics of the code under mutation. Reduction in a way the resulting code (after operator applied) is a proper subset semantically of the original version. `a; b` -> `a` is a classic example. The proposed `to_a` to `to_set` for much of the semantic complies to this axiom but for much not. For example it adds behavior that was not present before for `Set` specific API. The mutation operators in this class are to my personal observation the most successful ones in terms of detecting unused semantics the developer is interesting in.
B) The operator does not reduce, but does something totally different but in the same class (class in sense of typeclass, not OO). Example here is changing `+` to `-`.

The proposed operator is in a grey area between A) and B), nevertheless I think it adds value. And we should try it on real code before we decide if we want it or not.

**Comment by tjchambers** [comment]
As I have proven on real code this is a silent killer because of how AR does not consider an `Array` and `Set` to be similar.

**Comment by mbj** [comment]
> As I have proven on real code this is a silent killer because of how AR does not consider an Array and Set to be similar.

WDYM by silent killer?
