### ISSUE TITLE
Is it possible to disable a particular mutation for a given line?

### ISSUE THREAD

**Issue by michaelherold** [mbj/mutant#498]
I have one particular instance where this would be useful: the `__send__` to `public_send` mutation. In Ruby < 2.1 `Module#include` was a private method, but in Ruby >= 2.1 it was changed to be a public method. One of my libraries still has to support 2.0 (and 1.9.3 currently ...) so I can't make the change to `public_send`. This means that I get a mutation that isn't killed when running mutant in 2.2.3, thus keeping me from the sweet, sweet nectar that is 100% mutation coverage. :cry:

While my corner case is not particularly important, I think the ability to mark a line as excluded from mutation testing could be useful. It communicates that the person who is `git blame`d for the disabled mutation has said, "Yes, I know there's a live mutation here, but there's a reason for it."

Is this possible in mutant? I wasn't able to find anything that looked like it could enable that functionality. If it's not currently possible, would it be something that anyone else would find useful?

**Comment by mbj** [comment]
@michaelherold There is no fine grained configurability for good reasons. My OSS time is very limited, and supporting fine grained configuration adds complexity, even when done well. So a while back I made the decision to only provide features that I'd use for my commercial activities, and nothing beyond. The overall value for people using mutant is better from doing N features right at a high quality, than to distribute the limited OSS time supporting N * M features at limited quality.

The feature you are requesting was requested very often in the past, and I'm sorry I'll not provide it.

I personally never need the fine grained exclusions you are asking for, mostly because I do not support old rubies (for the same OSS policy).

As a workaround, that might even be better:

What about shipping >= 2.1 compatible code by default and when your lib gets required on detection of < 2.1 you include a module that replaces the `public_send` with `send` call sides? Depending on the number of call sides this might be the better path than to "blind yourself via a exclusion feature" (that does not exist yet).

I'll close this issue as I think answered your question. Feel free to continue discussion.

**Comment by michaelherold** [comment]
Thanks @mbj! I totally understand about feature creep. I appreciate you taking the time to suggest a workaround.

Thank you for creating such a useful project. I look forward to seeing where you'll take it.

**Comment by mbj** [comment]
@michaelherold How many call sides for `#send` vs `#public_send` are affected?

**Comment by tjchambers** [comment]
@michaelherold FWIW I asked for a similar *ignore a line* in mutant. After having used it for a considerable amount of time (> 8 hours per day for weeks), I concur with the decision to keep the complexity low and focus limited time on other features. For me it has been an extremely valuable tool as is, and it just keeps getting better (or worse if you count more mutations to chase as worse - for me that is better). 

Appreciate you being part of the mutant community.

**Comment by michaelherold** [comment]
@mbj The only line I've ever had this issue on is [this particular one](https://github.com/michaelherold/module_builder/blob/1b814b68c30bd6aac1f9ab59f3c64cf571647a25/lib/module_builder/builder.rb#L110). Is that what you're asking? I'm unfamiliar with the term "call side".

@tjchambers I also agree with keeping it simple - the simplest thing that works, right? :smile: The fact that I have this one mutation stay alive isn't really an issue because I have diagnosed it and determined that it's not an issue. I'm in full agreement that since this feature is something that would complicate mutant, it's something that should be ignored. I'd rather @mbj spend his time coming up with new, better things instead of taking time to scratch this nitpicky itch!

**Comment by mbj** [comment]
@michaelherold Why dont you do the following (conceptually untested):

```
# my_lib/pre_ruby_20.rb
module MyLib
  module PreRuby21
    def inclusions
      inclusions.each { |mod| @module.__send__(:include, mod) }
    end
  end

  ModuleUsingPublicSend.send(:include, PreRuby21)
end

# my_lib.rb
require 'my_lib/some_stuff'

if RUBY_VERSION < '2.1'
  require 'my_lib/pre_ruby_21.rb'
end
```

Now you by default ship `#public_send` in your default implementation and get 100% mutation coverage on 2.2.3. As a bonus side: If any person decides to violate `Module#include` API in the future and set `#include` to private visibility, your code using `#public_send` will notice.

And as I you only (?) run mutant on 2.2.3, mutant will *never* see the pre 2.1 code, and will not try to mutate it.

Summary: You use the most correct method by default and all code for supporting "older" rubies sits in a dedicated file, allowing to drop support for old rubies easier, and monitor for the impact of old ruby support in a central place.

**Comment by mbj** [comment]
> I'm unfamiliar with the term "call side".

Call side is the location a method is called. A method can have one multiple or none call sides.

**Comment by michaelherold** [comment]
@mbj Thank you so much for the suggestion! I'm adding that to my board to think about for my next release. You're very kind to spend time coming up with this idea for me.

> And as I you only (?) run mutant on 2.2.3

Yep, just as a convenience. I've run it on other versions to make sure that I wasn't missing anything, but since it takes a while I just normally run on my primary Ruby.

> Call side is the location a method is called. A method can have one multiple or none call sides.

Thanks for the clarification. I've heard "call site" before, but never "call side".

**Comment by mbj** [comment]
@michaelherold I mix up `d` and `t` very randomly. Means that `call site` is correct, and `call side` is a mistake. I do not hear the difference between d / t for most englisch words.
