### ISSUE TITLE
Add mutation enum[n..-1] → enum.drop(n)

### ISSUE THREAD

**Issue by dkubb** [mbj/mutant#521]

**Comment by mbj** [comment]
Matching that one in the AST is more complex than the mutations we sue to have right now. I'd love to support it, without lots of manual special cased code.

But we IMO need an "AST matching language" a "CSS for AST structures" with an efficient precompiler that merges various match expressions into one application to avoid a re-iteration per mutation operator.

For now I think we should implement this one via the usual explicit strategy, and than observice duplication with other operators that cross many AST levels.
