### ISSUE TITLE
Mutating false to nil

### ISSUE THREAD

**Issue by knovoselic** [mbj/mutant#544]
Consider the following code:

    class Book
      attr_reader :pages

      def initialize
        @pages = []
      end

      def add_page_without_ads(text)
        add_page text, false
      end

      def add_page_with_ads(text)
        add_page text, true
      end

      private

      def add_page(text, ads)
        text += 'Buy something!' if ads
        pages << text
      end
    end

and the following spec:

    require 'spec_helper'

    describe Book do
      subject(:book) { described_class.new }

      describe '#add_page_without_ads' do
        it 'just adds a new page with the specified text' do
          subject.add_page_without_ads 'some text.'
          expect(subject.pages).to eq ['some text.']
        end
      end
      describe '#add_page_with_ads' do
        it 'appends adds to the end of the page' do
          subject.add_page_with_ads 'some text.'
          expect(subject.pages).to eq ['some text.Buy something!']
        end
      end
    end

The code/spec produce only one alive mutation:

    @@ -1,4 +1,4 @@
     def add_page_without_ads(text)
    -  add_page(text, false)
    +  add_page(text, nil)
     end

What would you do in this case? Would you leave the mutation alive, or replace it with nil? `false` makes a lot more sense then `nil` in the context of the `add_page` method, although both `false` and `nil` will produce the same result.

**Comment by maksar** [comment]
I would expose only one public method in the first place:
```
  def add_page(text, with_ads: nil)
    text += 'Buy something!' if with_ads
    pages << text
  end
```

**Comment by mbj** [comment]
Kill via refactoring:

```
class Book
  attr_reader :pages

  def initialize
    @pages = []
  end

  def add_page_without_ads(text)
    add_page(text)
  end

  def add_page_with_ads(text)
    add_page_ads(text)
  end

  private

  def add_page(text, ads)
    pages << text
  end

  def add_page_ads(text)
     add_page(text + 'Buy Something!')
end
```

Removes boolean control parameter entirely.

**Comment by mbj** [comment]
Even when I closed this issue: feel free to continue discussion.

**Comment by dkubb** [comment]
Having a method that takes a boolean in order to determine the code path it executes is a code smell, specifically [Control Coupling](https://github.com/troessner/reek/blob/master/docs/Control-Couple.md). It's almost always better to refactor it away.

**Comment by knovoselic** [comment]
Thanks everyone, I get what you're saying. Here's a better example (rails codebase): .

    def some_action
      do_something
      head :ok
    end


Mutant will try to mutate `:ok` into `nil` and the mutation will not get killed because `head nil` still returns HTTP OK. Any suggestions here? I think `head :ok` is much better than `head nil`.

**Comment by mbj** [comment]
@knovoselic The problem is that rails does not prevent `nil`, not that mutant identifies this misdesign in the rails API.

The mutation from any expression to `nil` when alive is valid, in all cases. But in case of imperfect 3rd party API design, it might be hard to kill.

You likely can kill this mutation via a message expectation asserting the argument is `:ok` and not nil. Or propose to fix rails ;)

The message expectation one is likely the way to go short-term.

**Comment by knovoselic** [comment]
@mbj Thanks. Yeah, I can kill it via a message expectation, but I don't like that. I'll leave it for now.

**Comment by mbj** [comment]
I do not like the message expectation either, but I consider the root cause really is on the rails API design side. If `head nil` and `head :ok` are indistinguishable something is wrong.
