### ISSUE TITLE
Mutant Stuck using MRI 2.3.0

### ISSUE THREAD

**Issue by wjdhamilton** [mbj/mutant#552]
Whilst trying to test a rails 4.2 app on OSX using ruby 2.3.0 mutant consistently get stuck despite a timeout being set in rspec as per documentation. Unfortunately, I have no idea how to debug this! Any help would be much appreciated. Strangely, the problem seems to be different using MRI 2.2.1 than MRI 2.3.0. The tests that got stuck in 2.3.0 are different from those that get stuck in 2.2.1.

**Comment by wjdhamilton** [comment]
Fixed it! I had an errant call to byebug in one of the tests which was naturally pausing execution, however the call was bound to a conditional that did not resolve when the code was being normally tested. Is it worth mentioning this in the docs? I know it's obvious in hindsight but I don't think it was that obvious in the heat of the moment!

**Comment by mbj** [comment]
@wjdhamilton Haha, cool. Thx for sharing anyway. More googleable issue resolutions are appreciated.



> I had an errant call to byebug in one of the tests which was naturally pausing execution, however the call was bound to a conditional that did not resolve when the code was being normally tested. Is it worth mentioning this in the docs?

WDYM, can you give me a small code example? I want to be sure I reply to the right thing.

**Comment by wjdhamilton** [comment]
Certainly!

```ruby
test 'It can pause execution without you realising' do
  thingy = subject.the_thing
  byebug unless thingy # You forgot about this after fixing the reason thingy was nil
  # Behaviour to be tested
end
```

**Comment by mbj** [comment]
Ahh, so its a conditional mutant caused to be evaluated in your tests from injecting a behavior difference that made the bug (you fought before) trigger.

I do think you can prevent this via adding a whitelisting conditional based on an ENV read.

```
DO_BYBEBUG=1 bundle exec rspec ...
```

And your code would only branch into `bytebug` when this env variable exists.

**Comment by wjdhamilton** [comment]
So, is that something the library would have to implement or does it already exist?

**Comment by mbj** [comment]
I was more thinking about you predicate such "debug things" via equivalent of `if ENV.key?('YOUR_DEBUG_KEY')` this way this behavior that stops rspec would not be triggerable under mutation testing, and more important CI.

**Comment by wjdhamilton** [comment]
That’s a good idea, but on the other hand given that mutant can make temporary alterations to the code, why not allow the user to specify a rule that causes any lines including byebug to be removed when mutant is run? That way you’re not asking the user to add additional lines of code to their project. Something like: 

```ruby 
Mutant.config do |c|
	c.remove_lines_containing ‘byebug’
end
```

Might do the job

**Comment by mbj** [comment]
@wjdhamilton Thats a possible but IMO impractical solution:

* Mutant right now does NOT mutate the specs, and your call side is in the specs
* Desterministically statically determining if `Kernel#byebug` is called is not possible, as it might be wrapped by other spec helpers. I'd have to turn mutant into a ruby implementation to determine this, which will not happen for obvious reasons.
* Minor point: Mutant does not support global configuration (like your example) and will never for practical reasons.
* Stopping the specs in certain scenarios by default and having tool options to work around these is not really a good idea. As many tools (not only CI) require termination. Example is your CI, you really do not want to stop execution of your rspec examples when your spec code runs into `byebug`. Hence I think byebug "stop the world" should be whitelisted locally and have a decent default in other environments.
* Personal opinion: I consider calls to `byebug` as debug statements that should never be committed to the repository anyway.

**Comment by wjdhamilton** [comment]
Having read your thoughts on this, I agree. I also think that adding that flag would be an excellent idea. I’ll try and use the Rails environment flag in future. 

Thanks for your help and advice!

James

**Comment by mbj** [comment]
> I also think that adding that flag would be an excellent idea.

Did you miss a negation here?

> and use the Rails environment flag in future.

What I proposed is a unix environment variable, not related to rails at all.

**Comment by wjdhamilton** [comment]
No I don’t think I missed a negation, I was referring to your suggestion - `if ENV.key?(‘YOUR_DEBUG_KEY’)` as being the right idea, not mine.

**Comment by mbj** [comment]
> I also think that adding that flag would be an excellent idea.

Heh, I was assuming "the flag" referrs to Mutant config you proposed. Thx for clarifying.
