### ISSUE TITLE
Mutant reporting 100% coverage on 0 subject matches

### ISSUE THREAD

**Issue by mcandre** [mbj/mutant#553]
I used mutant for the first time on my [rubycheck](https://github.com/mcandre/rubycheck) gem. Am I doing this right?

Trace:

```
$ git clone git@github.com:mcandre/rubycheck.git
$ cd rubycheck/
$ bundle
$ gem install mutant-rspec
$ mutant --include lib --require rubycheck --use rspec Rubycheck*
Mutant configuration:
Matcher:         #<Mutant::Matcher::Config match_expressions: [Rubycheck*]>
Integration:     Mutant::Integration::Rspec
Expect Coverage: 100.00%
Jobs:            8
Includes:        ["lib"]
Requires:        ["rubycheck"]
Subjects:        0
Mutations:       0
Results:         0
Kills:           0
Alive:           0
Runtime:         0.00s
Killtime:        0.00s
Overhead:        Inf%
Mutations/s:     0.00
Coverage:        100.00%
Expected:        100.00%
Active subjects: 0








Mutant configuration:
Matcher:         #<Mutant::Matcher::Config match_expressions: [Rubycheck*]>
Integration:     Mutant::Integration::Rspec
Expect Coverage: 100.00%
Jobs:            8
Includes:        ["lib"]
Requires:        ["rubycheck"]
Subjects:        0
Mutations:       0
Results:         0
Kills:           0
Alive:           0
Runtime:         0.06s
Killtime:        0.00s
Overhead:        Inf%
Mutations/s:     0.00
Coverage:        100.00%
Expected:        100.00%
Active subjects: 0
Mutant configuration:
Matcher:         #<Mutant::Matcher::Config match_expressions: [Rubycheck*]>
Integration:     Mutant::Integration::Rspec
Expect Coverage: 100.00%
Jobs:            8
Includes:        ["lib"]
Requires:        ["rubycheck"]
Subjects:        0
Mutations:       0
Results:         0
Kills:           0
Alive:           0
Runtime:         0.06s
Killtime:        0.00s
Overhead:        Inf%
Mutations/s:     0.00
Coverage:        100.00%
Expected:        100.00%
```

**Comment by mbj** [comment]
No:

```
Mutations:       0
Subjects:        0
```

AKA: Nothing to mutate, hence reporting 100% (but should probably not). So both are wrong, your usage, and mutants behavior on no matches (without `--since`).

Seems your namespace is `RubyCheck`, https://github.com/mcandre/rubycheck/blob/master/lib/rubycheck.rb#L14, not `Rubycheck` hence there are no matches.

OT: I fixed your issue title as not very productive for other users.

I'll keep this issue open until mutant reports 0% for 0 subject matches unless `--since` is specified.

**Comment by mbj** [comment]
Conceptually I do not agree anymore that mutant should report `0%` coverfage and exit `0` in the case no subjects are selected. I'll close this issue for now.

**Comment by dgollahon** [comment]
> Conceptually I do not agree anymore that mutant should report 0% coverage and exit 0 in the case no subjects are selected. I'll close this issue for now.

Just curious, what is your current opinion on the correct behavior? As a side note: I am occasionally surprised when mutant exits `0` but nothing was selected--usually when I have a typo in my match expression.

**Comment by mbj** [comment]
@dgollahon Each invocation of mutant "asks" for a coverage report on what is selected. And mutant exits nonzero if there was a non covered mutation. Not having a candidate IMO does not qualifiy as uncovered mutation, but see below.

So IMO the primary rule should be: Mutant exiting 0 should imply coverage was 100%.

Now: Not selecting any mutation is common on incremental use. Lets say a co-worker tuned a `.js` file. Its totally valid that in this scenario mutant exits 0 (hence also should report 100% on 0 mutations).

The interesting case is non incremental use on 0 selected subjects: Here mutant IMO should complain and abort early.

This is not what this issue asked for. The original author had a problem with finding his subjects.

**Comment by dgollahon** [comment]
> The interesting case is non incremental use on 0 selected subjects: Here mutant IMO should complain and abort early.

Cool, agreed. I will open an issue if there isn't one already.

> This is not what this issue asked for. The original author had a problem with finding his subjects.

True. Should mutant complain and abort if someone supplied `NotARealClass` or `NotARealModuleNamespace*`? The previous change would not cover if you had a typo in an expression and supplied `--since` or if you supplied two expressions `ARealClass` and `NotARealClass`. Should these get validated somehow?

**Comment by mbj** [comment]
> if someone supplied `NotARealClass` or `NotARealModuleNamespace*`? The previous change would not cover if you had a typo in an expression and supplied `--since` or if you supplied two expressions `ARealClass` and `NotARealClass`. Should these get validated somehow?

This is a different case, and yes mutant should complain explicitly. The rule should be: For every match expression that did not select a subject (this is pre `--since` mechanics): error/warn.
