### ISSUE TITLE
Expected coverage, perfect the enemy of good? (discuss)

### ISSUE THREAD

**Issue by wied03** [mbj/mutant#559]
I was perplexed by an exit code of 1 when I was exceeding my expected coverage. I read this post and understand why that's happening: http://blog.arkency.com/2015/05/mutation-testing-and-continuous-integration/

I can appreciate the logic in it. That said, doesn't requiring an exact match kind of make perfect the enemy of good for someone trying to get into this?

It seems like to "white list", I'd need to `--ignore-subject` if the subject doesn't match 100% or I need to text parse the output and implement >= on my own. If none of my subjects hit 100%, I'd have to exclude them all (or run them individually and face noise if the number slightly varies). I would have no incremental way to work towards 100%. 

If I had the option to do greater than or equals (in addition to what's there), would that be a bad thing?

If the answer is no, then perhaps another way to fix this problem is to allow >=, but always remember the latest "high point". The coverage could be persisted to a file for each subject. Then mutant would fail if the number drops. I know that could be a bit awkward for CI/source control, but it's likely that someone runs the mutant tests locally anyways before CI does and they could see that the numbers "increased" in that persisted file and check it in to source control.

Anyways, just some thoughts.

**Comment by mbj** [comment]
> I can appreciate the logic in it. That said, doesn't requiring an exact match kind of make perfect the enemy of good for someone trying to get into this?

I can see your argument. But: Writing mutation testing engines is a hard job. I do this on my free time. So I long ago made the decision to ONLY support *my* use cases. I do not proactively optimize for beginners, at all. I do not add switches useful for other project types, etc.

All to put the very limited opensource time I have to a good use. While its hard to onboard mutant as a beginner, this policy significantly improves the usability for "professional users", as they get a more stronger tool with more value by default. Not having to fight "beginner comatible defaults / options".

If I'd had offset my efforts to support beginners, the tool would never have matured for professional use.

> If I had the option to do greater than or equals (in addition to what's there), would that be a bad thing?

Its as you seem to understand this is a weaker primitive, a primitive I'd not use on my own projects, hence its not supported.

> If the answer is no, then perhaps another way to fix this problem is to allow >=, but always remember the latest "high point".

Requires state keeping, no chance I implement this in my free time see policy ;)

> Anyways, just some thoughts.

I appreciate them, as they give me the chance to state my policy again.

I'll close this issue for now as I think I answered the question. Feel free to continue discussion anyway.

**Comment by mbj** [comment]
@wied03 OT there is a slack channel where we discuss these questions with more people on a more regular basis, feel free to let me know your email so I can invite you.

**Comment by wied03** [comment]
Fair enough. I certainly appreciate the effort you put into this. Are pull requests for any of the above out of the question? Or is the review + long term maintenance of a PR for this going to be a pain?

**Comment by mbj** [comment]
> Are pull requests for any of the above out of the question? Or is the review + long term maintenance of a PR for this going to be a pain?

When a PR is made that passes code review and its not significantly to much (from my perspective dead) logic: I'll take it.

Code review process here is "though" but should be of value for anyone trying.

**Comment by wied03** [comment]
Well, for the guy that wrote a mutant testing tool, I would be surprised if the code review process was easy :)

**Comment by mbj** [comment]
> Well, for the guy that wrote a mutant testing tool, I would be surprised if the code review process was easy :)

Hint: I've 100% self coverage right now, and I'll not sacrifice it ;)

**Comment by mbj** [comment]
@wied03 Thinking about this a bit longer: I'd even consider to drop `--expect-coverage` from mutant master, as I do not use it "at all".

Instead we could encrich the `Config` with an `SuccessCriteria` object that you can inject for your own on projects that do not follow my own workflow.
