### ISSUE TITLE
Fix rubocop configuration to flag #inject used when #reduce should be preferred

### ISSUE THREAD

**Issue by dkubb** [mbj/mutant#569]
For some reason rubocop is not properly flagging uses of `#inject` and recommending `#reduce` instead. 

Here is one example:

https://github.com/mbj/mutant/blob/41c41b2a1723f15eb84358cb61dea08ded7756c7/spec/support/corpus.rb#L97

While I hope it's just this one instance, it could be a signal that rubocop is missing other flags.

**Comment by mbj** [comment]
This was addressed a while ago.

**Comment by dgollahon** [comment]
Actually, just FYI: https://github.com/rubocop-hq/rubocop/issues/9262. I will fix the last instance of `inject` in the codebase in a few minutes.
