### ISSUE TITLE
regexp_parser does not support MRI 2.3.1 yet

### ISSUE THREAD

**Issue by mvz** [mbj/mutant#595]
This problem surfaces when running current master with MRI 2.3.1. Running mutant, I get `Regexp::Syntax::MissingSyntaxSpecError: Missing syntax specification file for 'ruby/2.3.1'` from `regexp_parser`.

**Comment by mbj** [comment]
Interesting. Mutant did not got a release for master regexp mutations yet. I'll get that fixed before release. //cc @backus.

**Comment by backus** [comment]
I'll get that fixed tonight

**Comment by mbj** [comment]
This was addressed upstream meanwhile, waiting for a release. @mvz Thx for reporting.
