### ISSUE TITLE
Re-Introduce regexp mutations after invariant fixes

### ISSUE THREAD

**Issue by mbj** [mbj/mutant#600]
Regexp mutations from https://github.com/mbj/mutant/pull/565 where removed in #599 for breaking invariants currently not perfectly enforced in the build.

Steps needed to bring this feature back:

* [x] Corpus failed (handled via https://github.com/ammar/regexp_parser/issues/24)
* [ ] Too many warnings added to the build (see https://github.com/ammar/regexp_parser/issues/25)
* [ ] Muant did not enforce warning freenes in the first place

**Comment by dgollahon** [comment]
Wasn't this closed by #618?

**Comment by backus** [comment]
Yup
