### ISSUE TITLE
Alive mutation on frozen strings 

### ISSUE THREAD

**Issue by tjchambers** [mbj/mutant#609]
I have a number of results as in below:

``` ruby
OE::EffectKeys#render:/Users/tj/projects/AOT/app/lib/oe/effect_keys.rb:8
- rspec:0:./spec/lib/oe/effect_keys_spec.rb:11/OE::EffectKeys#render renders the keys
evil:OE::EffectKeys#render:/Users/tj/projects/AOT/app/lib/oe/effect_keys.rb:8:0300c
@@ -1,10 +1,10 @@
 def render
-  out = "<div id='TextEffectKeys'><textarea rows=3 cols=40 name='econtent[]'></textarea></div>".dup
+  out = "<div id='TextEffectKeys'><textarea rows=3 cols=40 name='econtent[]'></textarea></div>"
   out << "<div id='ConclusionEffectKeys'></div>"
   out << "<div id='ExplanationEffectKeys'></div>"
   out << add_menu("PointEffectKeys")
   out << add_menu("IndicationPointEffectKeys")
   out << add_menu("ActivityEffectKeys")
   out << add_menu("ObjectiveEffectKeys")
 end
```

I have also seen cases where I used `String.new` as well and those also remain alive in Ruby 2.3.1 with the pragma `# frozen_string_literal: true`. I have added code to confirm that the ruby version  I am running mutant under is 2.3.1. 

I have not created a small reproducible GIST yet, but it would look like:

``` ruby
# frozen_string_literal: true

    def test_code
        a = 'a string'.dup
        a << 'adding to?'
    end
```

which should NOT IMO suggest removing the `.dup` as viable under Ruby 2.3.1. 

My only theory is that this may be due to the unparser and in that mode creating what results in a mutable string when unparsing. Since you could inscribe my knowledge of the unparser on the head of a pin, this was just a theory. So I did the following test with code below:

``` ruby
# frozen_string_literal: true

    def test_code
        String.new('aa')
    end
```

``` ruby
describe '#test_code' do
    it 'is not frozen' do
      expect(test_code.frozen?).to be false
    end
  end
```

and the result was an alive mutation:

```
@@ -1,4 +1,4 @@
 def test_code
-  String.new('aa')
+  "aa"
 end
```

This further leaves me convinced that the string being created is in fact mutable during the mutation runs.

**Comment by mbj** [comment]
@tjchambers Mutant does not support ruby 2.3 anymore. Also mutant now emits the mutations inside a frozen literal context.

Hence the `dup` is now very semantical and this issue should be solved.

I'm closing it, should you still have related problems feel free to reopen / comment here.
