### ISSUE TITLE
How to kill Regexp::IGNORECASE mutation?

### ISSUE THREAD

**Issue by tjchambers** [mbj/mutant#610]
I have code that looks like the following:

``` ruby
# frozen_string_literal: true
module OE
  module WildcardToRegex

    REAL_DOT       = '\\.'
    REGEX_ASTERISK = '.*'

    private_constant(*constants(false))

    def self.regex_it(text)
      Regexp.new("^#{wildcard_to_regex(text)}$", Regexp::IGNORECASE)
    end

    # Converts real periods to escaped ones
    # and transforms the wildcards to Regex wildcards
    # '*' to multivalue '.*'
    # '?' to '.'
    def self.wildcard_to_regex(text)
      text.gsub('.', REAL_DOT).gsub('*', REGEX_ASTERISK).tr('?', '.')
    end
  end
end
```

and an alive mutation:

``` ruby
 def self.regex_it(text)
-  Regexp.new("#{"^"}#{wildcard_to_regex(text)}#{"$"}", Regexp::IGNORECASE)
+  Regexp.new("#{"^"}#{wildcard_to_regex(text)}#{"$"}", self)
 end
```

which I cannot figure out how to kill. 

Attempt:

```
 subject { described_class.regex_it(text) }
 describe '.regex_it' do

    context 'matches case insensitive' do
      let(:text) { 'cde' }
      it 'defines case insensitive' do
        expect(subject.options).to equal(Regexp::IGNORECASE)
      end
      it { expect('CdE').to match subject }
    end
  end
```

which does not kill. My inference is that when Regexp receives the options parameter - a bit map - it sets the settings based on the bits that are on or off. Then when it is returned the settings are extracted from the stored bit map settings - not the original. And `self` just happens to have bit 0 set = '1' and therefore mimics the addition of parameter `Regexp::IGNORECASE`. So the behavior is the same and there is no way I can come up with so far that will kill it. 

Any ideas would be appreciated.

**Comment by backus** [comment]
Have you tried just interpolating into a regexp literal? This should be equivalent and also remove the mutation from `Regexp::IGNORECASE` → `self`

```ruby
/^#{wildcard_to_regex(text)}$/i
```

**Comment by tjchambers** [comment]
I thought of that overnight and got up early to try it!

**Comment by tjchambers** [comment]
AND IT WORKS! Great minds think alike - or at least similarly :)

**Comment by tjchambers** [comment]
As a side note that cut the potential mutations from 63 -> 50, a reduction of 13.

**Comment by mbj** [comment]
I'm reopening this to write a verbose answer, since I think that more should be said on this issue. (Hint: rubies API is to blame to not fail on passing primitives as the flag argument).

**Comment by tjchambers** [comment]
@mbj I look forward to reading it. Don't let it interfere with your fork.

**Comment by mbj** [comment]
I'm closing this for the moment. I like the answer by @backus well enougn and my additions are 4y outstanding ;)
