### ISSUE TITLE
Crash from use of Safe Chaining &. operator 

### ISSUE THREAD

**Issue by tjchambers** [mbj/mutant#611]
I believe this has something to do with the .each preceded by the `&` safe chaining operator. I tried changing the code to `puts params[:aid]&.inspect` and did NOT get a traceback. 

Code:

``` ruby
class RoadmapProcessor
  include Adamantium::Flat

  def process(params)
    params[:aid]&.each { |adjustment| ActivityPositioner.call(adjustment) }
  end
end
```

Spec:

``` ruby
require 'rails_helper'

RSpec.describe RoadmapProcessor do
  before :each do
    [ActivityPositioner].each do |name|
      stub_const(name.to_s, double(name.to_s.downcase).as_null_object)
    end
  end

  let(:params) do
    {
      'aid': [
               {
                 'aid':  'prog942',
                 'pid':  's154p105',
                 'pctx': '41.935483870967744',
                 'pcty': '52.58620689655172'
               }
             ]
    }
  end

  describe '#process' do
    it 'processes the params' do
      expect(ActivityPositioner).to receive(:call).with(an_instance_of(Hash))
      subject.process(params)
    end

    it 'processes with no params' do
      expect(ActivityPositioner).not_to receive(:call)
      subject.process({})
    end
  end
end
```

<details>
<summary>

Traceback...</summary>

[2016-07-01T09:40:21.628128000Z] RAILS_ENV=test bundle exec mutant -r./config/environment.rb -j6 --use rspec RoadmapProcessor > log/mutant/lib/roadmap_processor_5bfbdd765bf092770753dd3d2d4cbede_899d0a07dd66f15d01e4e6a6c942e32c_0.8.10.log
/Users/tj/.rvm/gems/ruby-2.3.1@global/gems/unparser-0.2.5/lib/unparser/emitter/send.rb:182:in `emit_arguments': undefined method`empty?' for nil:NilClass (NoMethodError)
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/unparser-0.2.5/lib/unparser/emitter/send/conditional.rb:21:in `dispatch'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/unparser-0.2.5/lib/unparser/emitter.rb:104:in`write_to_buffer'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `call'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in`block (3 levels) in create_memoized_method'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/memory.rb:63:in `block (3 levels) in fetch'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:58:in`fetch'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/memory.rb:62:in `block (2 levels) in fetch'
    from /Users/tj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in`mon_synchronize'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/memory.rb:61:in `block in fetch'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:58:in`fetch'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/memory.rb:60:in `fetch'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:116:in`block (2 levels) in create_memoized_method'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/unparser-0.2.5/lib/unparser/emitter.rb:199:in `visit_plain'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/unparser-0.2.5/lib/unparser/emitter.rb:472:in`block in visit_indented'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/unparser-0.2.5/lib/unparser/emitter.rb:437:in `indented'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/unparser-0.2.5/lib/unparser/emitter.rb:472:in`visit_indented'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/unparser-0.2.5/lib/unparser/emitter.rb:457:in `emit_body'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/unparser-0.2.5/lib/unparser/emitter/def.rb:38:in`dispatch'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/unparser-0.2.5/lib/unparser/emitter.rb:104:in `write_to_buffer'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in`call'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `block (3 levels) in create_memoized_method'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/memory.rb:63:in`block (3 levels) in fetch'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:58:in `fetch'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/memory.rb:62:in`block (2 levels) in fetch'
    from /Users/tj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/memory.rb:61:in`block in fetch'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:58:in `fetch'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/memory.rb:60:in`fetch'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:116:in `block (2 levels) in create_memoized_method'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/unparser-0.2.5/lib/unparser.rb:29:in`unparse'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/bundler/gems/mutant-0e83f310daf3/lib/mutant/mutation.rb:30:in `source'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in`call'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `block (3 levels) in create_memoized_method'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/memory.rb:63:in`block (3 levels) in fetch'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:58:in `fetch'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/memory.rb:62:in`block (2 levels) in fetch'
    from /Users/tj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/memory.rb:61:in`block in fetch'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:58:in `fetch'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/memory.rb:60:in`fetch'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:116:in `block (2 levels) in create_memoized_method'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/bundler/gems/mutant-0e83f310daf3/lib/mutant/mutation.rb:72:in`sha1'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `call'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in`block (3 levels) in create_memoized_method'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/memory.rb:63:in `block (3 levels) in fetch'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:58:in`fetch'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/memory.rb:62:in `block (2 levels) in fetch'
    from /Users/tj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in`mon_synchronize'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/memory.rb:61:in `block in fetch'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:58:in`fetch'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/memory.rb:60:in `fetch'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:116:in`block (2 levels) in create_memoized_method'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/bundler/gems/mutant-0e83f310daf3/lib/mutant/mutation.rb:22:in `code'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in`call'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `block (3 levels) in create_memoized_method'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/memory.rb:63:in`block (3 levels) in fetch'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:58:in `fetch'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/memory.rb:62:in`block (2 levels) in fetch'
    from /Users/tj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/memory.rb:61:in`block in fetch'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:58:in `fetch'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/memory.rb:60:in`fetch'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:116:in `block (2 levels) in create_memoized_method'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/bundler/gems/mutant-0e83f310daf3/lib/mutant/mutation.rb:14:in`identification'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `call'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in`block (3 levels) in create_memoized_method'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/memory.rb:63:in `block (3 levels) in fetch'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:58:in`fetch'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/memory.rb:62:in `block (2 levels) in fetch'
    from /Users/tj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in`mon_synchronize'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/memory.rb:61:in `block in fetch'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:58:in`fetch'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/memory.rb:60:in `fetch'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:116:in`block (2 levels) in create_memoized_method'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/bundler/gems/mutant-0e83f310daf3/lib/mutant/reporter/cli/printer/mutation_result.rb:53:in `run'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/procto-0.0.3/lib/procto.rb:62:in`public_send'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/procto-0.0.3/lib/procto.rb:62:in `block in initialize'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/bundler/gems/mutant-0e83f310daf3/lib/mutant/reporter/cli/printer.rb:71:in`visit'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/bundler/gems/mutant-0e83f310daf3/lib/mutant/reporter/cli/printer.rb:60:in `block in visit_collection'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/bundler/gems/mutant-0e83f310daf3/lib/mutant/reporter/cli/printer.rb:59:in`each'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/bundler/gems/mutant-0e83f310daf3/lib/mutant/reporter/cli/printer.rb:59:in `visit_collection'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/bundler/gems/mutant-0e83f310daf3/lib/mutant/reporter/cli/printer/subject_result.rb:18:in`run'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/procto-0.0.3/lib/procto.rb:62:in `public_send'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/procto-0.0.3/lib/procto.rb:62:in`block in initialize'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/bundler/gems/mutant-0e83f310daf3/lib/mutant/reporter/cli/printer.rb:71:in `visit'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/bundler/gems/mutant-0e83f310daf3/lib/mutant/reporter/cli/printer.rb:60:in`block in visit_collection'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/bundler/gems/mutant-0e83f310daf3/lib/mutant/reporter/cli/printer.rb:59:in `each'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/bundler/gems/mutant-0e83f310daf3/lib/mutant/reporter/cli/printer.rb:59:in`visit_collection'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/bundler/gems/mutant-0e83f310daf3/lib/mutant/reporter/cli/printer/env_result.rb:13:in `run'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/procto-0.0.3/lib/procto.rb:62:in`public_send'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/procto-0.0.3/lib/procto.rb:62:in `block in initialize'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/bundler/gems/mutant-0e83f310daf3/lib/mutant/reporter/cli.rb:68:in`report'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/bundler/gems/mutant-0e83f310daf3/lib/mutant/runner.rb:29:in `run_mutation_analysis'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/bundler/gems/mutant-0e83f310daf3/lib/mutant/runner.rb:14:in`initialize'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/adamantium-0.2.0/lib/adamantium/class_methods.rb:17:in `new'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/adamantium-0.2.0/lib/adamantium/class_methods.rb:17:in`new'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/gems/procto-0.0.3/lib/procto.rb:62:in `block in initialize'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/bundler/gems/mutant-0e83f310daf3/lib/mutant/cli.rb:18:in`run'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/bundler/gems/mutant-0e83f310daf3/bin/mutant:39:in `<top (required)>'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/bin/mutant:23:in`load'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/bin/mutant:23:in `<main>'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/bin/ruby_executable_hooks:15:in`eval'
    from /Users/tj/.rvm/gems/ruby-2.3.1@global/bin/ruby_executable_hooks:15:in `<main>'
</details>

**Comment by tjchambers** [comment]
I am going to investigate this further as it may be a NoMethodError on nil.each ...

**Comment by tjchambers** [comment]
I retested and it still appears to be a mutant and/or unparser issue.

**Comment by mbj** [comment]
@tjchambers First mutant crash reported in a long time. Cudos for this, thx for reporting!

**Comment by tjchambers** [comment]
@mbj I enjoy bugs as much as the next person but ...

**Comment by tjchambers** [comment]
This no longer fails on version 0.8.25. Closing...
