### ISSUE TITLE
Mutant mutates, but tests still pass, but shouldn't

### ISSUE THREAD

**Issue by onemanstartup** [mbj/mutant#614]
Rails 5, RSpec 3.5.0, last mutant.
I run mutant like this `RAILS_ENV=test bundle exec mutant -r ./config/environment --use rspec PaymentMethodPolicy`
I have two tests of method which returns false or true.
```ruby
      it { expect(subject.destroy?).to be false }
      it { expect(subject.destroy?).to be true }
```
```ruby  
  def destroy?
    admin?
  end
```
mutant changes it to 
```diff
  def destroy?
-  admin?
+  nil
 end
```
and mutations is not killed. but if I change code manually tests failed.
However if i run mutant with specific method `RAILS_ENV=test bundle exec mutant -r ./config/environment --use rspec PaymentMethodPolicy#destroy` it kills all mutations.

**Comment by backus** [comment]
Your selector in your command seems to be incorrect. You wrote `PaymentMethodPolicy#destroy` when it should be `PaymentMethodPolicy#destroy?`. Can you share the full test file though along with the full mutant test output? My hunch is that the tests you included are not being selected but I can't confirm that with what you have provided

**Comment by onemanstartup** [comment]
I don't even.. It's working. I started working on other things yesterday(frontend), come back today in the morning, start running mutant it's working and killing all mutants. 
Sorry to bother. I don't even know how this could happen. Because one time it's working, next time it is not, and next it is working again.
I will close issue, maybe it's only me. Thanks.

**Comment by tjchambers** [comment]
@onemanstartup I have this behavior myself for a different reason - one time works, next not. I am not saying this is your condition, but I use RSpec `pattern` in my `~/.rspec` file to filter examples, and if I am using that for one example and running #mutant on another rspec respects the pattern either way and filters out my specs under mutant - as it should. However this can look like mutant is the culprit.
