### ISSUE TITLE
Mutant (0.8.11) works fine without /specs directory

### ISSUE THREAD

**Issue by emiltrotuar** [mbj/mutant#632]
Run `mutant -I lib -r example --use rspec 'Example'` and it will show you some low coverage even though specs for 'Example' are missing
then create /specs and add /specs/example_spec.rb with 100 coverage
and it will work as expected

Some of earlier editions were throwing an exception about missing directory /specs or 
something like 'No rspec example groups found...' if there were no specs

**Comment by mbj** [comment]
> Run mutant -I lib -r example --use rspec 'Example' and it will show you some low coverage even though specs for 'Example' are missing

This is from the effect that mutant right now counts neutral mutations as part of the coverage. Neutral mutations are inserting the original code unmodified again, and expect to find NO test that is red.

If no tests are found this self test condition is fulfilled.

> Some of earlier editions were throwing an exception about missing directory /specs or 
> something like 'No rspec example groups found...' if there were no specs

I think that must be a really old version?
