### ISSUE TITLE
Could not load integration "rspec" (you may want to try installing the gem mutant-rspec)

### ISSUE THREAD

**Issue by cyberw** [mbj/mutant#637]
Hi!

When I try running mutant I get this error. I have installed mutant-rspec, tried running it on both OSX and Linux.

**Comment by mbj** [comment]
Can you post your `Gemfile`?

**Comment by cyberw** [comment]
# This gemfile is intended for use on "rakemeter master" as well as jmeter master
source 'https://nexus.int.klarna.net/content/groups/publicgems/'
gem 'rake'
gem 'pg'
gem 'ruby-jmeter', git: 'https://github.com/cyberw/ruby-jmeter.git'
gem 'aws-sdk'
gem 'rubocop', '~> 0.37.2'
gem 'rspec'
gem 'mutant-rspec'

But I get this behaviour with no Gemfile as well (using only manually installed gems)

**Comment by mbj** [comment]
@cyberw what does happen if you use `source `https://rubygems.org`? I do not have any control about other sources, and these could easily misbehave.

**Comment by cyberw** [comment]
Well what do you know. Maybe I had a too old version of rspec? (3.4.0)

**Comment by mbj** [comment]
> Well what do you know. Maybe I had a too old version of rspec? (3.4.0)

This does not help me. Can you tell me if it works when you use an official rubygems repository. I do not have the time to assert 3rd party repository contents while working for free in OSS.

**Comment by cyberw** [comment]
Sorry, I meant that now it works (I was not questioning what you know - but rather proclaiming I was surprised, like "huh, well what do you know...") 

 I'm still not entirely clear as to why it is working, but I think it was because I got an updated version of rspec.

**Comment by mbj** [comment]
@cyberw k, cool.

**Comment by mbj** [comment]
Sorry for the state transition, hit the wrong button.
