### ISSUE TITLE
Testing a module - have to manually reload models

### ISSUE THREAD

**Issue by knovoselic** [mbj/mutant#644]
I'm trying to use mutant with the following gem:
https://github.com/glooko/mongoid-embedded-errors

I've noticed that almost all mutations fail, even the most basic ones like replacing whole method with a `raise`. After some debugging it turns out that models used by specs (in spec/support/models) are not reloaded when mutant mutates `Mongoid::EmbeddedErrors` module, meaning the specs are always testing the initial (non-mutated code), and are always passing.

I've managed to hack a fix for it:

``` ruby
  config.before(:each) do
    # Need to manually reload spec models for mutant to work as expected
    if ENV['MUTANT']
      Dir[SPEC_MODELS_PATH].each do |filename|
        Object.send(:remove_const, File.basename(filename, '.rb').capitalize)
        load filename
      end
    end
  end
```

Is there a better way of doing this? Am I doing something wrong - should mutant take care of the reloading automatically?

**Comment by mbj** [comment]
Can you specify what exactly you mean by reloading?

Mutant assumes that your constants are all loaded before mutations are inserted. If your code also inserts constants, this invariant is broken.

**Comment by knovoselic** [comment]
@mbj Unless I do `remove_const` and then `load` the file which defines the class, it looks like the class is always using the first version of code, not mutated one. I'm trying to test the following module:
https://github.com/glooko/mongoid-embedded-errors/blob/d1c77f496be0bf786eecc7fa2cbf76a3a7868b56/lib/mongoid/embedded_errors.rb

I'm not sure if this is happening because I'm testing a module, or because of the way I've set up spec models (they are loaded in `spec_helper.rb`). Any help/instructions would be helpful.

**Comment by mbj** [comment]
@knovoselic Mutant does not support subjects that mutate the constant space after loading the subject under test.

You want to force your subject under test to have a fully expanded / populated constant scope before mutation testing starts. You can do this via creating a separate 'require entrypoint' mutant can use to load your subjects. Use `--require your/project/all-autolloads-expanded` or similar.

**Comment by knovoselic** [comment]
@mbj thanks, that's good to know!
