### ISSUE TITLE
Add mutation from `foo === bar` → `bar.kind_of?(foo)`

### ISSUE THREAD

**Issue by backus** [mbj/mutant#689]
Threequals might be more powerful than the use case requires

```ruby
String === 'foo'                       # => true
/foo/  === 'foo'                       # => true
->(value) { value == 'foo' } === 'foo' # => true
```

**Comment by dkubb** [comment]
This is more a style issue, but I tend to prefer `#kind_of?` due to it's similarity to `#instance_of?`, which is a stronger form of the test.

**Comment by backus** [comment]
Sure I can make it `kind_of?`
