### ISSUE TITLE
Tests passing locally but 16 'found a bug in mutant / unparser' errors for 18 tests

### ISSUE THREAD

**Issue by compwron** [mbj/mutant#695]
I am seeing the error ```Original code was inserted unmutated. And the test did NOT PASS.
Your tests do not pass initially or you found a bug in mutant / unparser.``` but my tests do pass locally and in my travis.ci build. If you have time, I'd love to understand more about what is happening here. I want to run mutant against my codebase so that I can improve how I test. 

This might be related to file IO operations, even though each test is making its own file directory and git repo (the code that I am trying to mutate is all about file IO and git repos)

My full mutant log is at https://github.com/safe-commit-hook-rb/safe-commit-hook-rb/blob/7f1cb01517dc64702ec65236e058aba6a7cc9560/mutant_output.txt 
I created this file via the command: ```bundle exec mutant --include lib --use rspec SafeCommitHook > mutant_output.txt"```

This mutant run was against the code as of commit https://github.com/safe-commit-hook-rb/safe-commit-hook-rb/tree/7f1cb01517dc64702ec65236e058aba6a7cc9560

**Comment by backus** [comment]
@compwron can you try running with `--jobs 1` and let me know if you still run into neutral failures?

**Comment by compwron** [comment]
Yep that was it. Weird, I thought I had made the tests parallelizable. Thanks! https://gist.github.com/compwron/df87d339fbcd5cac441c3cec40474e6b

**Comment by mbj** [comment]
@compwron Mutant has a build in heuristic to detect non parallelizable tests, that one was reporting. Rule of thumb: Whenever you see noop errors reported: Do not trust the results.
