### ISSUE TITLE
Mutant 0.8.12 doesn't work on MRI 2.4

### ISSUE THREAD

**Issue by ch1c0t** [mbj/mutant#697]
The latest release published at Rubygems(0.8.12) doesn't work on MRI 2.4:
```
bundler: failed to load command: mutant (/home/ch1c0t/.gem/ruby/2.4.0/bin/mutant)
Regexp::Syntax::MissingSyntaxSpecError: Missing syntax specification file for 'ruby/2.4'
  /home/ch1c0t/.gem/ruby/2.4.0/gems/regexp_parser-0.3.6/lib/regexp_parser/syntax.rb:109:in `load'
  /home/ch1c0t/.gem/ruby/2.4.0/gems/regexp_parser-0.3.6/lib/regexp_parser/syntax.rb:38:in `new'
  /home/ch1c0t/.gem/ruby/2.4.0/gems/regexp_parser-0.3.6/lib/regexp_parser/lexer.rb:14:in `lex'
  /home/ch1c0t/.gem/ruby/2.4.0/gems/regexp_parser-0.3.6/lib/regexp_parser/parser.rb:26:in `parse'
  /home/ch1c0t/.gem/ruby/2.4.0/gems/mutant-0.8.12/lib/mutant/ast/regexp.rb:15:in `parse'
```
Hence, I have to use the upstream. Do you plan to issue a new release anytime soon?

**Comment by mbj** [comment]
We'll have to update the `regexp-parser` dependency once its 2.4 support was released: https://github.com/ammar/regexp_parser/pull/30

**Comment by mbj** [comment]
> Pushed regexp_parser 0.4.2 to rubygems.org

I'll try to do the update later the day. But according to my OSS policy I'll not give any guarantees, mostly because mutant development is driven by my commercial needs and my clients are all on 2.3 right now.

**Comment by ch1c0t** [comment]
@mbj Sure. Thank you for the quick response.

**Comment by ojab** [comment]
Any update on this?

**Comment by mbj** [comment]
@ojab No, no OSS time. But its an easy contribution feel free to try by yourself.

**Comment by ojab** [comment]
Done https://github.com/mbj/mutant/pull/717
Also I want to have parser updated to '~> 2.4.0' (there was no syntax additions since currently used '~> 2.3.1', so only version bump is needed without further changes to unparser/etc), but I'm stuck in mutant/unparser/devtools interdependencies.

Any advice how PRs should be done?

**Comment by mbj** [comment]
@ojab some people just created PRs for these, should land in their master / release "soon".

**Comment by mbj** [comment]
This was released a long time ago, closing.
