### ISSUE TITLE
Mutant should not emit equivalent mutation `self.foo` → `foo()` when an lvar with the same name is present

### ISSUE THREAD

**Issue by backus** [mbj/mutant#700]
Example code

```ruby
$ cat lib/example.rb
# frozen_string_literal: true

class Foo
  def initialize(bar, baz)
    @bar = bar
    @baz = baz
  end

  def blah
    bar = baz.bar

    bar + self.bar
  end

  attr_reader :bar, :baz
end # Foo
```

Corresponding example spec that should be full mutant coverage

```ruby
$ cat spec/example_spec.rb
require 'rspec'
RSpec.describe Foo do
  it 'adds bar and baz.bar' do
    baz = double(bar: 3)
    bar = 2

    foo = Foo.new(bar, baz)

    expect(foo.blah).to be(5)
  end
end
```

Tests pass:

```sh
$ bundle exec rspec --require example
.

Finished in 0.00224 seconds (files took 0.21787 seconds to load)
1 example, 0 failures

```

Mutant emits equivalent mutation:

```sh
$ bundle exec mutant --use rspec --include lib --require example -- 'Foo*'

Mutant configuration:
Matcher:         #<Mutant::Matcher::Config match_expressions: [Foo*]>
Integration:     Mutant::Integration::Rspec
Jobs:            8
Includes:        ["lib"]
Requires:        ["example"]
Subjects:        2
Mutations:       43
Results:         43
Kills:           42
Alive:           1
Runtime:         1.99s
Killtime:        5.34s
Overhead:        -62.66%
Mutations/s:     21.57
Coverage:        97.67%
Active subjects: 0
Foo#blah:/Users/johnbackus/Projects/gists/mutant-self-parens/lib/example.rb:9
- rspec:0:./spec/example_spec.rb:3/Foo adds bar and baz.bar
evil:Foo#blah:/Users/johnbackus/Projects/gists/mutant-self-parens/lib/example.rb:9:aabd3
@@ -1,5 +1,5 @@
 def blah
   bar = baz.bar
-  bar + self.bar
+  bar + bar()
 end
-----------------------
Mutant configuration:
Matcher:         #<Mutant::Matcher::Config match_expressions: [Foo*]>
Integration:     Mutant::Integration::Rspec
Jobs:            8
Includes:        ["lib"]
Requires:        ["example"]
Subjects:        2
Mutations:       43
Results:         43
Kills:           42
Alive:           1
Runtime:         1.99s
Killtime:        5.34s
Overhead:        -62.66%
Mutations/s:     21.57
Coverage:        97.67%
```

In a similar vein to https://github.com/mbj/mutant/issues/615, this is basically just a difference in style when a local variable is present with the same name. Without the local variable I like this mutation.

**Comment by backus** [comment]
I'll fix if you agree it is a bug @mbj

**Comment by mbj** [comment]
> I'll fix if you agree it is a bug @mbj

Its not a bug. Let me explain: `self.foo` where `foo` can be used is redundant AST.

`foo()` has the AST: `(send nil :foo)`, and its a form where you can reach any private method. Its the implicit send to self.

Where `self.foo` has the AST `(send self :foo)` where you could NOT call private methods. `self` is just a stand in for ANY possible receiver, that by chance just was `self`, its the explicit send to self.

We should always prefer the primitive AST. 

At the syntax level: The parser when it sees `foo` has to consult the lvar scope to decide if its an lvar read or an method call, for `foo()` you made this explicit with minimal effort.

That people tend to prefer the `self.foo` form when working around lvar clashes is just from the fact they are not aware that `foo` is just syntax shugar for `foo()` that gets expanded depending on the lvar scope. And most books get it wrong and instead want you to use `self.foo` to come around this.

Think about it this way: You intend to call `#bar` via the syntax `bar`, but you cannot as shugar is in your way, now to come around this problems you have to fix your syntax for the AST you are intend to use, not change your call pattern to call a remote object (that just happens to be `self`).

**Comment by backus** [comment]
Heh I was hoping you wouldn't make the AST argument. I don't think the argument from the perspective of the AST is compelling at all. It is your tool though so alright.

**Comment by mbj** [comment]
> Heh I was hoping you wouldn't make the AST argument. I don't think the argument from the perspective of the AST is compelling at all. It is your tool though so alright.

Forget the AST, think about the source of the problem as the syntax. 

If you want a private method send to `bar`, but you cannot because of a clash with an lvar, you should fix it via syntax that does not clash, not changing to a more powerful send primitive that can reach foreign objects.

**Comment by mbj** [comment]
Summary: You intend to send to self, and should use a primitive that sends to self, not a primitive that sends to any object but than you instruct that primitive to send to self.

This is like talking to someone in the same room with a cellphone, its redundant.

**Comment by backus** [comment]
> If you want a private method send to bar, but you cannot because of a clash with an lvar, you should fix it via syntax that does not clash, not changing to a more powerful send primitive that can reach foreign objects.

I'm not convinced that doing `self.foo` is more powerful than `foo`. I would agree with that for `any_receiver_besides_self.foo` but you can't define an lvar named `self` so I don't think there is anything more powerful here. You could even flip the argument on its head and say `self.foo` is more primitive because then you are demonstrating that you are calling a public method while `foo()` could be calling a public or a private method.

**Comment by mbj** [comment]
Its about the "thing that can send to any object" vs "thing that can send only to myself".

If you talk to yourself, use the syntax that can only talk to yourself.

**Comment by dgollahon** [comment]
> If you talk to yourself, use the syntax that can only talk to yourself.

Then that's really more of a syntax preference, right? I think it's also why @backus opened the issue to begin with: one is not more correct than the other, semantically.

**Comment by mbj** [comment]
Its a primitive preference. If the lvar would not be present, you'd use the primitve that can only talk to self. If the lvar is present you should still use it.

**Comment by dgollahon** [comment]
> Its a primitive preference. If the lvar would not be present, you'd use the primitve that can only talk to self. If the lvar is present you should still use it.

Right, I'm just saying that's a matter of taste, not semantics. It's your project, of course, but imo it'd be best if mutant minimized the number of equivalent programs it emits.

**Comment by mbj** [comment]
If you used `self.foo` where `foo()` is sufficient its not equivalent semantics. Its redundant primitive use. Fix it. Or have a case where the receiver is sometimes a foreign object to counter mutants reduction of `receiver.method` to `method`.

**Comment by dgollahon** [comment]
> If you used self.foo where foo() is sufficient its not equivalent semantics.

I understand that the AST is different, but i can't think of a case where the result could possibly be different--that's why i'm saying it's equivalent. Is there a case where you could get a different result by calling `foo()` instead of `self.foo` (excluding the fact that `self.foo` has narrower access to methods)?

**Comment by dgollahon** [comment]
I suppose the same argument applies to `self.foo` v.s. `foo` though when a `foo` lvar is absent.

Still doesn't seem meaningful to me to enforce using `()` over `self.` though.

**Comment by mbj** [comment]
Again. its not equivalent. Its equivalent under the assumption that `self.foo` does the same thing as `foo()` which it definitively does not.

The difference may not be observable in the cases you have in mind, but it exists. Mutant "fixes" a high number of "equivalent" problems via: Telling the user to accept one form over the other, and only mutate in one direction. This way you can eliminate this "equivalent" (in your mind) to re-occur.

Its an argument that a send form that can reach any possible receiver is more powerful than a send form that can reach only the sender. Hence I made the decision to mutate in this particular direction.

Feel free to fork and change it. As I'm tired of the discussion that does not really work with my arguments but instead re-iterates a notion of arbitrary style where I explained my self over and over again: I'll lock this discussion now.
