### ISSUE TITLE
Speedup mutant by using in memory database

### ISSUE THREAD

**Issue by matthias-g** [mbj/mutant#705]
I have a setup for mutant using rspec and fixtures. Because I noticed that the database interactions make up a huge part of the runtime of mutant I'm trying to use an sqlite in memory database.

I've added the following lines to `rails_helper.rb` and they make it work for running `bundle exec rake spec`.
```ruby
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Schema.verbose = false
load "#{Rails.root.to_s}/db/schema.rb"
```

But mutant fails to load the fixtures:
```
Failure/Error: raise(ActiveRecord::StatementInvalid, "Could not find table '#{table_name}'") if structure.empty?

ActiveRecord::StatementInvalid:
  Could not find table 'users'
# ~/.rvm/gems/ruby-2.2.5/gems/mutant-rspec-0.8.11/lib/mutant/integration/rspec.rb:63:in `call'
# ~/.rvm/gems/ruby-2.2.5/gems/mutant-0.8.12/lib/mutant/env.rb:48:in `block in run_mutation_tests'
# ~/.rvm/gems/ruby-2.2.5/gems/mutant-0.8.12/lib/mutant/isolation/fork.rb:66:in `block in result'
# ~/.rvm/gems/ruby-2.2.5/gems/mutant-0.8.12/lib/mutant.rb:223:in `open'
# ~/.rvm/gems/ruby-2.2.5/gems/mutant-0.8.12/lib/mutant.rb:223:in `block in <class:Config>'
# ~/.rvm/gems/ruby-2.2.5/gems/mutant-0.8.12/lib/mutant/isolation/fork.rb:63:in `call'
# ~/.rvm/gems/ruby-2.2.5/gems/mutant-0.8.12/lib/mutant/isolation/fork.rb:63:in `result'
# ~/.rvm/gems/ruby-2.2.5/gems/mutant-0.8.12/lib/mutant/isolation/fork.rb:55:in `child'
# ~/.rvm/gems/ruby-2.2.5/gems/mutant-0.8.12/lib/mutant/isolation/fork.rb:37:in `block in parent'
# ~/.rvm/gems/ruby-2.2.5/gems/mutant-0.8.12/lib/mutant/isolation/fork.rb:36:in `fork'
# ~/.rvm/gems/ruby-2.2.5/gems/mutant-0.8.12/lib/mutant/isolation/fork.rb:36:in `parent'
# ~/.rvm/gems/ruby-2.2.5/gems/mutant-0.8.12/lib/mutant/isolation/fork.rb:23:in `block in call'
# ~/.rvm/gems/ruby-2.2.5/gems/mutant-0.8.12/lib/mutant/isolation/fork.rb:22:in `pipe'
# ~/.rvm/gems/ruby-2.2.5/gems/mutant-0.8.12/lib/mutant/isolation/fork.rb:22:in `call'
# ~/.rvm/gems/ruby-2.2.5/gems/mutant-0.8.12/lib/mutant/env.rb:46:in `run_mutation_tests'
# ~/.rvm/gems/ruby-2.2.5/gems/mutant-0.8.12/lib/mutant/env.rb:25:in `kill'
# ~/.rvm/gems/ruby-2.2.5/gems/mutant-0.8.12/lib/mutant/parallel/worker.rb:60:in `call'
# ~/.rvm/gems/ruby-2.2.5/gems/mutant-0.8.12/lib/mutant/parallel/worker.rb:60:in `handle_job'
# ~/.rvm/gems/ruby-2.2.5/gems/mutant-0.8.12/lib/mutant/parallel/worker.rb:45:in `handle'
# ~/.rvm/gems/ruby-2.2.5/gems/mutant-0.8.12/lib/mutant/parallel/worker.rb:31:in `run'
# ~/.rvm/gems/ruby-2.2.5/gems/mutant-0.8.12/lib/mutant/parallel/worker.rb:17:in `run'
# ~/.rvm/gems/ruby-2.2.5/gems/mutant-0.8.12/lib/mutant/parallel/master.rb:43:in `block (2 levels) in run'
# ~/.rvm/gems/ruby-2.2.5/gems/mutant-0.8.12/lib/mutant/actor/env.rb:14:in `block in spawn'
```

It looks like mutant does not use the in memory database and load the schema before running the specs. Do you have an idea on how to fix that?

**Comment by andrzejkrzywda** [comment]
I'm not sure if this is the same case, but it may be helpful to look at how we solved a similar problem:

https://github.com/arkency/rails_event_store_active_record/blob/master/spec/spec_helper.rb#L9-L29

**Comment by mbj** [comment]
@matthias-g You are on the right track and what @andrzejkrzywda told you is correct

Context: Mutant offers a high level of concurrency and does its "best" to isolate concurrent executions from each other. If your code uses a shared medium (the database in this case) you have to isolate the DB accesses by yourself.

There are various more advanced patterns possible ot reduce the time spend on re-seeding but explaining them would break the time constraints I've here to do OSS support.

I'm closing this issue as I *think* what @andrzejkrzywda told you will solve your problem, if its not solved feel free to re-open.

**Comment by matthias-g** [comment]
Thanks for your quick replies!

The solution actually works but unfortunately it doesn't improve the performance in my case.
As my schema is more complex as in the file linked by @andrzejkrzywda the overhead introduced for loading the schema is so high that it negates the speedup of the in memory database.

**Comment by matthias-g** [comment]
Just in case someone else has a similar setup with rspec and fixtures:

To load the fixtures I was using
```ruby
RSpec.describe MyClass do
  fixtures :users, :roles #, ...
end
```

I've found that the performance for mutant improves when I remove the `fixtures` in the `describe` and instead use `bundle exec rails db:fixtures:load` before running mutant to load the fixtures into the database.

**Comment by mbj** [comment]
@matthias-g Yes, the constrant overhead to re-seed the DB can eat up the parallel execution gains.

One possible solution is to share the already loaded schema with the mutant test executions, removing the overhead. Mutant forks per mutation hence if the schema is already loaded at this point all writes will be automatically discarded.

Conceptually as you'll never run your production application on SQLite I think you should not use SQLite for tests but instead use postgresql (if you *really* need DB infected tests) seed the schema before testing and than execute each separate test in a serializable transaction that gets never commited. This way you get "decent" production equivalent testing, and isolation between kill fork threads.

This setup works nice for me on legacy projects that do still require lots of DB access to execute their tests.
