### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by MrJoy** [mbj/mutant#713]
I'm getting `command not found` because the `mutant` script isn't being included in the path properly.  I suspect it's because this:

```
gem.executables      = %w[mutant]
```

Should actually be this:

```
gem.executables      = %w[bin/mutant]
```

**Comment by MrJoy** [comment]
(For clarity, `bundle exec mutant` works, `mutant` does not -- unlike other gems with executables.)

**Comment by mbj** [comment]
@MrJoy This is an interesting one.

It appears that `gem.executables` should be interpreted relative to `gem.bindir`, which AFIAK defaults to `bin`, hence it *should* work already.

http://guides.rubygems.org/specification-reference/#bindir
http://guides.rubygems.org/specification-reference/#executables

I just tested it locally on `chruby` / `Linux`.

Before changing it I'd like to know what causes the difference?

**Comment by MrJoy** [comment]
Ok, so...  Embarrassing thing:  I just went to try it out again and... it worked.  I thought maybe there's a difference in my environment it must be coming from some difference between doing a `gem install mutant` vs. letting Bundler install it.  The branch I'm on doesn't have it in the `Gemfile` / `Gemfile.lock`, but the gem is still present from my earlier tinkering.  However, running `bundle clean --force` and then doing a `gem install mutant` has it working.

So...  I have NFI why I was getting `command not found` after (apparently successful) `gem install mutant` attempts before.  Sorry to waste your time. :-/
