### ISSUE TITLE
Mutation "x.to_int" to "Integer(x)" is not always good.

### ISSUE THREAD

**Issue by felixvf** [mbj/mutant#737]
Suppose you have some code like

```ruby
time.to_i - 86400/2
```

where `time` is a `Time` instance, then 'mutant' mutates this to

```ruby
Integer(time) - 86400/2
```

However, the original and the mutant are semantically equivalent. Furthermore, the suggested mutant is actually slower (because it does this and that and finally calls #to_i anyway).

In this specific situation,
1. how can this mutation be switched off manually (e.g. by some kind of code annotation)?
2. how can this mutation be switched off automatically (e.g. by Mutant detecting or inferring that `time` cannot be a String instance (where mutating #to_i may make sense) but a Time instance)?

**Comment by mbj** [comment]
> how can this mutation be switched off manually (e.g. by some kind of code annotation)?

You cannot switch it of, mutant intentionally provides no switches. If you spotted equivalent semantics (from mutant point of view) you can always force one way via a message expectation. As this happens rarely enough it typically scales.

> how can this mutation be switched off automatically (e.g. by Mutant detecting or inferring that time cannot be a String instance (where mutating #to_i may make sense) but a Time instance)?

I've got test runtime type detection in a private fork of mutant, but I'll likely not end up releasing this in the OSS version.

**Comment by mbj** [comment]
While I closed the issue, feel free to re-open in case my answer is not conclusive.
