### ISSUE TITLE
0.8.15 with gem updates?

### ISSUE THREAD

**Issue by grantneufeld** [mbj/mutant#741]
What needs to be done to get the `release/v0.8.15` branch finished off and released? Is there anything we can do to help wrap it up?

Also, what would it take to upgrade the `parser` gem to 2.5, and `regexp_parser` to 0.5? Do those just need to be bumped in the gemspec, or is there a code conflict(s) to be resolved?

Thanks!

**Comment by mbj** [comment]
> Also, what would it take to upgrade the parser gem to 2.5, and regexp_parser to 0.5? Do those just need to be bumped in the gemspec, or is there a code conflict(s) to be resolved?

Very likely there is also some work required to bump unparser to `2.5` AST changes.

Help / PRs apprechiated.

**Comment by mbj** [comment]
Released via #748
