### ISSUE TITLE
Fully qualified explicit match expressions should never crash mutant

### ISSUE THREAD

**Issue by mensfeld** [mbj/mutant#752]
Example taken from Karafka:

```ruby
bundle exec mutant --include lib --require karafka --use rspec Karafka::Schemas*
```

It fails for this class: https://github.com/karafka/karafka/blob/master/lib/karafka/schemas/config.rb#L14

**Comment by mbj** [comment]
@mensfeld This issue was never a real blocker to try out mutant on your code base. Still it may be the correct time to try again. I've got more time for mutant now. Let me know if you are still interested.

**Comment by mbj** [comment]
Wrong button ;)
