### ISSUE TITLE
[Rails] Mutant reports that it didn't do anything

### ISSUE THREAD

**Issue by asilano** [mbj/mutant#755]
Pretty sure I must be doing something wrong here...

I have the small beginnings of a Rails 5, Ruby 2.5 project, ([here on github](https://github.com/asilano/free-dom/tree/restart) - note, the `restart` branch (I'm rebuilding an old project from the ground up)).

With `mutant-rspec` in the Gemfile, I run `RAILS_ENV=test bundle exec mutant -r ./config/environment --use rspec User`. Mutant reports:

```
Mutant configuration:
Matcher:         #<Mutant::Matcher::Config match_expressions: [User]>
Integration:     Mutant::Integration::Rspec
Jobs:            2
Includes:        []
Requires:        ["./config/environment"]
Subjects:        0
Mutations:       0
Results:         0
Kills:           0
Alive:           0
Runtime:         0.11s
Killtime:        0.00s
Overhead:        Inf%
Mutations/s:     0.00
Coverage:        100.00%
```

...which I think means it didn't do anything. Why not?

**Comment by mbj** [comment]
@asilano Your model has nothing to mutate: https://github.com/asilano/free-dom/blob/restart/app/models/user.rb#L1-L8

Mutant assumes that you can trust dependencies, but also it does not (yet) support class level mutations, only instance and singleton methods will be mutated.

So from mutants perspective there is nothing to cover, hence you get 100% right now. Start adding a method to see what would happen.

I'll close this issue, feel free to re-open in case I got something wrong.

**Comment by asilano** [comment]
Aha, that makes sense. And indeed, when I run it over `GamesController` it finds a whole bunch of issues because I haven't tested that at all yet.

So, do I have to run it over each class individually and specifically? I see that it takes a very long time, so I get why that's a good idea, but is there any way of widening the scope? For instance, I hoped that it might take wildcards, but `Game*` also does nothing. Sometimes you just want to set a huge suite running and grab a cup of tea...

**Comment by mbj** [comment]
> So, do I have to run it over each class individually and specifically? I see that it takes a very long time, so I get why that's a good idea, but is there any way of widening the scope? For instance, I hoped that it might take wildcards, but `Game*` also does nothing. Sometimes you just want to set a huge suite running and grab a cup of tea...

Just use an app specific namespace `YourApp` and have all your classes below that namespace. Mutant can deal with `YourApp*`.

Also you should write some dummy tests that do not assert anything for untested code, this will make mutant much faster as it would not widen the test set if it finds a match for the current subject.

**Comment by asilano** [comment]
Ok, that seems fair - `*` is a child match, rather than a wildcard. Am I right in thinking that Rails' top-level app-name namespace doesn't count? Which is fair enough, I just need to know.

**Comment by mbj** [comment]
@asilano Yes `*` is a recursive namespace matching operator. I never had the reason to match namespace prefixes, so I did not implement it.
