### ISSUE TITLE
Are Mutant results idempotent?

### ISSUE THREAD

**Issue by Winbobob** [mbj/mutant#760]
Hi,

I tested same RSpec unit test (for Rails application) on Mac and Ubuntu. I set the timeout 5 seconds. The code used `build`keywords instead of `create` to set up`FactoryBot` test data. In theory, the code did not rely on testing DB. I just wonder whether it is because of the concurrency. 

Below is the command I run:
```
RAILS_ENV=test bundle exec mutant -r ./config/environment --use rspec AssignmentTeam
```

 - On Mac, the coverage is `85.79%`. Below is the result:
```
Mutant configuration:
Matcher:         #<Mutant::Matcher::Config match_expressions: [AssignmentTeam]>
Integration:     Mutant::Integration::Rspec
Jobs:            8
Includes:        []
Requires:        ["./config/environment"]
Subjects:        30
Mutations:       1461
Results:         1461
Kills:           1256
Alive:           205
Runtime:         730.62s
Killtime:        5088.69s
Overhead:        -85.64%
Mutations/s:     2.00
Coverage:        85.97%
```

 - On Ubuntu, the coverage is `76.04%`. Below is the result:
```
Mutant configuration:
Matcher:         #<Mutant::Matcher::Config match_expressions: [AssignmentTeam]>
Integration:     Mutant::Integration::Rspec
Jobs:            1
Includes:        []
Requires:        ["./config/environment"]
Subjects:        30
Mutations:       1461
Results:         1461
Kills:           1111
Alive:           350
Runtime:         11205.92s
Killtime:        10246.39s
Overhead:        9.36%
Mutations/s:     0.13
Coverage:        76.04%
```

**Comment by mbj** [comment]
> * Yes. I use `database_cleaner`. I try to run unit tests right now and I suppose not to touch testing DB. If I do not force cleaning testing DB for each test case, the mutant testing should be much faster, right?

Yes, best way to know is to simply execute your unit tests and shut down the DB while they run. You'll be amazed on how easy it is to sneak in DB IO from an rails environment.

In my projects I use a special AR connection adapter to make sure only the schema loads can be executed for tests where I want to be sure no DB IO happens. I consider to opensource that one.

**Comment by mbj** [comment]
>     * Yes. I did not set the `job` parameters. So the mutant testing will be parallelized based on how many cores in the system. I will try to run Mac without concurrency or ubuntu with concurrency to see whether there are any differences.

I suspect that at least on Mac you have set `-j1` or `--jobs 1`. As these days all macs have multiple logic cores. And mutant should detect the number of cores and in the absence of a `-j` or `--jobs` flag default to use a concurrent run.

**Comment by mbj** [comment]
>     * I used only one testing DB locally to run mutant testing.The reason why I chose 5s timeout is because my slowest unit test takes less than 3s to run. So I thought 5s is enough. Now I think I have to increase the timeout threshold as well as try to stop cleaning testing DB for each test case.

Why not make it the other way round and try to have your tests NOT leaking DB state? Before you told me that your tests do not touch the DB, so this is a bit contradictionary to me.

Maybe you should try to enforce that tests that are not supposed to touch the DB do not touch it. And only tests that touch it have the DB cleaner active?

Also try to minimize your code in `before :suite` as its run per mutation.

**Comment by Winbobob** [comment]
> > ```
> > * I used only one testing DB locally to run mutant testing.The reason why I chose 5s timeout is because my slowest unit test takes less than 3s to run. So I thought 5s is enough. Now I think I have to increase the timeout threshold as well as try to stop cleaning testing DB for each test case.
> > ```
> 
> Why not make it the other way round and try to have your tests NOT leaking DB state? Before you told me that your tests do not touch the DB, so this is a bit contradictionary to me.
> 
> Maybe you should try to enforce that tests that are not supposed to touch the DB do not touch it. And only tests that touch it have the DB cleaner active?
> 
> Also try to minimize your code in `before :suite` as its run per mutation.

Thank you very much for your suggestion! I will try to optimize my unit tests!

**Comment by mbj** [comment]
@Winbobob Can we close this?

**Comment by Winbobob** [comment]
@mbj Sure. Thank you very much for your help! I appreciate it!

**Comment by mbj** [comment]
@Winbobob Just curious are you still using mutant? Feel free to shoot me an email, I've got some (private) questions.

**Comment by mbj** [comment]
@Winbobob Mutant how has per worker process hooks: https://github.com/mbj/mutant/pull/1379 which can be used to isolate concurrency effects on the database from each other.

**Comment by Winbobob** [comment]
> @Winbobob Mutant how has per worker process hooks: https://github.com/mbj/mutant/pull/1379 which can be used to isolate concurrency effects on the database from each other.

Thank you for letting me know, @mbj! I'm not using Mutant right now. I will let you know once I use it again.
