### ISSUE TITLE
Handle errors from regexp_parser?

### ISSUE THREAD

**Issue by mvz** [mbj/mutant#813]
regexp_parser is a little more strict than MRI and raises an exception, e.g., on a regexp like `/u{/`. See https://github.com/ammar/regexp_parser/issues/59. I'm inclined to agree that regexp_parser should not allow cases that MRI's documentation forbids but MRI's parser accepts. Perhaps mutant should catch these exceptions and handle them appropriately?

**Comment by mbj** [comment]
I agree. Mutant should simply skip over such regexp bodies and not emit mutations for them.

**Comment by mbj** [comment]
And possibly warn. As mutant added more result states recently this should nicely integrate.

**Comment by mbj** [comment]
@mvz Thanks for the report. Mutant is now skipping such regexps silently, but in future we may get a warning. 

Do you want me to cut a release now? I've buffered enough changes.

**Comment by mvz** [comment]
Thanks @mbj. I'll leave the choice whether or not to cut a release up to you. I have changed the offending regexp in my code to include a backslash, so there's no urgency at the moment.

**Comment by mbj** [comment]
@mvz BTW rhe fix was released as 0.8.24.
