### ISSUE TITLE
Current Licensing

### ISSUE THREAD

**Issue by Ixalion** [mbj/mutant#870]
Given the new licensing situation, is this to be interpreted that after commit d5b97e8f73b6135426d20ae986295549d02ca4e7 is to be regarded as unavailable for usage to the general public? (The typical interpretation of "All Rights Reserved")

**Comment by mbj** [comment]
Correct, as this point all commits I added after this commit make the project not available for use. All rights Reserved.

Feel free to use earlier releases or earlier repro state at the previous license terms, MIT.

I hope I can make mutant more accessible in the near future. But talking to all contributors individually (or removing their contributions) takes time.

**Comment by mbj** [comment]
Status update: I begun to collect signatures of the past contribotors, and for the ones I could not reach I removed almost all contirbutions.

Which means that I'll "soon" be able to release mutant again with a new license.

My intention is to keep mutant free to use for OSS projects, education and research. But charge a subscription fee for commercial use.

A blog post with the reasoning for this change will follow.

**Comment by Ixalion** [comment]
Awesome to hear that the project is indeed continuing, and that you are going to be keeping it free to use for education institutions. 

Will look forward to seeing the post and when the conversion is complete.

**Comment by mbj** [comment]
@Ixalion BTW what is your mutant use case?

**Comment by Ixalion** [comment]
I have just been testing it out right now, but I am a developer for a large public university and am planning to add it to a few of the rails applications that I support.

**Comment by mbj** [comment]
@Ixalion Cool. This would fall under a free subscription than.

Dealing with rails makes mutation testing a bit more "awkward" feel free to ask questions in the mutant slack channel when you hit odd behavior.

**Comment by Ixalion** [comment]
I'll definitely pop in once I start working on it, trying to sign in to the slack requires a @blockscore.com email address, is this correct?

**Comment by mbj** [comment]
Sorry I meant @dgollahon ^^

**Comment by mbj** [comment]
> @mbj I think you inadvertently removed the link to the invite system badge I created in [ef4e477](https://github.com/mbj/mutant/commit/ef4e4779755bd232be1e471d7d6b4a0dd719d154) from the readme. The current slack badge does not direct users to a page they can sign up at and there is no invite link in the current README.

Yeah, I had to prune the readme from lots of contributions of people I could not reach. I'll have to rebuild it.



> I'm really perplexed as to why the regular slack link shows an `@blockscore.com` address, that's inappropriate configuration somewhere (it is the company I work for, but not affiliated with this project in any way). I don't think my slack account is an administrator account anymore, but I'll try to see if I can tell what's going on or, if not, @mbj I'll ping you on slack when to see if we can sort it out when I have a little bit of free time. I'm not sure what series of events would have caused this misconfiguration since I did not use an `@blockscore.com` address for my account or the bot's account.

I apprechiate you are sorting this out. Thanks.

**Comment by mbj** [comment]
@Ixalion I think this can be closed for the moment. The README explains the situation quite clearly and I have lots of active (free) opensource licenses handed out so far.
