### ISSUE TITLE
Mutations causing infinite recursion

### ISSUE THREAD

**Issue by tomdalling** [mbj/mutant#871]
I have this method:

```ruby
    def method_missing(name, *args)
      if respond_to_missing?(name)
        def_attr(name, *args)
      else
        super
      end
    end
```

Mutant 0.8.24 introduced a mutation that turns `def_attr(name, *args)` into `def_attr(name, *self)`. The splat results in the `#to_a` method being called on `self`, which ends up in `#method_missing` again, causing infinite recursion.

This is the message that mutant outputs:

    Killfork exited nonzero. Its result (if any) was ignored:
    #<Process::Status: pid 82290 SIGILL (signal 4)>
    Killing the mutation resulted in an integration error.
    This is the case when the tests selected for the current mutation
    did not produce a test result, but instead an exception was raised.

    This may point to the following problems:
    * Bug in mutant
    * Bug in the ruby interpreter
    * Bug in your test suite
    * Bug in your test suite under concurrency

    The following exception was raised:

    ```
    #<EOFError: end of file reached>
    /Users/tom/.gem/ruby/2.6.0/gems/mutant-0.8.24/lib/mutant/isolation/fork.rb:65:in `load'
    /Users/tom/.gem/ruby/2.6.0/gems/mutant-0.8.24/lib/mutant/isolation/fork.rb:65:in `read_child_result'
    /Users/tom/.gem/ruby/2.6.0/gems/mutant-0.8.24/lib/mutant/isolation/fork.rb:43:in `call'
    /Users/tom/.gem/ruby/2.6.0/gems/procto-0.0.3/lib/procto.rb:62:in `public_send'
    /Users/tom/.gem/ruby/2.6.0/gems/procto-0.0.3/lib/procto.rb:62:in `block in initialize'
    /Users/tom/.gem/ruby/2.6.0/gems/mutant-0.8.24/lib/mutant/isolation/fork.rb:133:in `block in call'
    /Users/tom/.gem/ruby/2.6.0/gems/mutant-0.8.24/lib/mutant/isolation/fork.rb:132:in `pipe'
    /Users/tom/.gem/ruby/2.6.0/gems/mutant-0.8.24/lib/mutant/isolation/fork.rb:132:in `call'
    /Users/tom/.gem/ruby/2.6.0/gems/mutant-0.8.24/lib/mutant/env.rb:55:in `run_mutation_tests'
    /Users/tom/.gem/ruby/2.6.0/gems/mutant-0.8.24/lib/mutant/env.rb:30:in `kill'
    /Users/tom/.gem/ruby/2.6.0/gems/mutant-0.8.24/lib/mutant/parallel/worker.rb:62:in `call'
    /Users/tom/.gem/ruby/2.6.0/gems/mutant-0.8.24/lib/mutant/parallel/worker.rb:62:in `handle_job'
    /Users/tom/.gem/ruby/2.6.0/gems/mutant-0.8.24/lib/mutant/parallel/worker.rb:47:in `handle'
    /Users/tom/.gem/ruby/2.6.0/gems/mutant-0.8.24/lib/mutant/parallel/worker.rb:33:in `run'
    /Users/tom/.gem/ruby/2.6.0/gems/mutant-0.8.24/lib/mutant/parallel/worker.rb:19:in `run'
    /Users/tom/.gem/ruby/2.6.0/gems/mutant-0.8.24/lib/mutant/parallel/master.rb:45:in `block (2 levels) in run'
    /Users/tom/.gem/ruby/2.6.0/gems/mutant-0.8.24/lib/mutant/actor/env.rb:16:in `block in spawn'
    ```

Is there a better way to handle this? I'm currently using `--ignore-subject` to make mutant pass.

**Comment by mbj** [comment]
@tomdalling Can you post the output again with adding 10 lines just above your quote? I need to know the type of the mutation (evil or neutral).

**Comment by tomdalling** [comment]
I'm not 100% sure why, but I'm having trouble reproducing that specific error now (sorry, I know that's annoying).

I do have all the details for a related error that I was also seeing. It's still infinite recursion inside `#method_missing`.

- It's the latest version of mutant/mutant-rspec (0.8.24)
- [CI failure logs](https://travis-ci.org/tomdalling/value_semantics/jobs/481924831) (including `bundle install` output)
- [The code](https://github.com/tomdalling/value_semantics/blob/c5f5ed9f8973469663c515bedaa796aa7cfa1269/lib/value_semantics.rb#L291-L301) on the same commit that CI was run on
- [The RSpec output](https://gist.github.com/tomdalling/d73ae2caeba20e6ac6913a8f782f5865) for the failing mutation
- [The fix](https://github.com/tomdalling/value_semantics/commit/92bc9d7f09e7786f9229a71ba6192842816c7965) in the subsequent commit

I'm going to close this issue because I've got it working now. Feel free to reopen it if the error details above are useful to you. Thanks for your time.

**Comment by mbj** [comment]
@tomdalling In master (which is unreleased, and will not untill I get the new license done) mutant should behave better, and print the stack trace for the inner failure. Currently your CI logs only show the outer failure of the master process detecting the killfork to exit nonzero.

I'm happy to come back to this issue once I have a new release from master. I'll re-open this issue to be reminded.

**Comment by mbj** [comment]
@tomdalling do you have a payload that can reproduce this? I think that this rspec output:

```
Finished in 0.00049 seconds (files took 0.34984 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

Indicates that I should improve the rspec integration and also count a mutation as covered when there si `1 error outside of examples` as this state indicates rspec "exits with failure".

**Comment by tomdalling** [comment]
Here's a minimal working example of what I'm seeing in the latest mutant version: https://gist.github.com/tomdalling/77caec35aeb92e9cfd5e4f7705698c07

**Comment by mbj** [comment]
@tomdalling With `0.10.8` you now have the option to configure a coverage criteria that allows to consider mutations that cause abnormal process exits as covered:

```
coverage_criteria:
  process_abort: true
```

In your mutant config file. See: https://github.com/mbj/mutant/blob/master/docs/configuration.md#coverage_criteria

Closing this.
