### ISSUE TITLE
Mutation Killer for MiniTest

### ISSUE THREAD

**Issue by CyborgMaster** [mbj/mutant#92]
I'm starting a new Rails project.  I currently use SimpleCov to monitor my test code coverage, and I would love to use Mutant to do mutation testing and coverage as well.  I have seen that some progress has been done on getting Mutant running in a rails environment, and was wondering if anyone has started any work on developing a mutation killer for the minitest framework, which is what my project uses.  I know the correct response is to fork, impliment it myself, and submit a PR, but we are on a tight deadline and I don't have time to do it now and would prefer to collaborate with someone if there is already effort in that direction.

**Comment by kbrock** [comment]
Is there a non-working/stagnant branch somewhere that I could look at?
164 references @ahawkins but I didn't track down anything.

**Comment by plexus** [comment]
I'm guessing https://github.com/ahawkins/mutant/tree/minitest is the branch being referred to.

**Comment by mbj** [comment]
@plexus In meanwhile there is a much more maintained one by me, that lacks people testing it: https://github.com/kbrock/mutant/tree/minitest this branch is "far less stale" than the one you are referencing.

@kbrock With your agreement I'd move this branch to my repo + create a PR to give it more visibility.

**Comment by kbrock** [comment]
:+1:

**Comment by plexus** [comment]
Awesome!
