### ISSUE TITLE
EBADF bad file descriptor

### ISSUE THREAD

**Issue by tjchambers** [mbj/mutant#943]
Using mutant git commit:   remote: https://github.com/mbj/mutant.git
  revision: 6d46f49bbd2fde97d2de274a1a053199e2ef8110

The pattern as I see it is a neutral failure is reported, then a EBADF bad file descriptor error on some file. Sometimes the file reported is a gem, sometimes a code file.

Note the error at top indicates `fptr_finalize_flush` and the error below indicates `io_fillbuf`.
```-----------------------
PrepareProgress#needs_temp_themes_finished:/Users/tj/projects/AOT/app/lib/stage_progress/prepare_progress.rb:232
- rspec:0:./spec/lib/stage_progress/prepare_progress_spec.rb:22/PrepareProgress#determine_complete has calculate the progress of a virgin cycle
- rspec:1:./spec/lib/stage_progress/prepare_progress_spec.rb:31/PrepareProgress#determine_complete has calculate the progress of a real cycle
neutral:PrepareProgress#needs_temp_themes_finished:/Users/tj/projects/AOT/app/lib/stage_progress/prepare_progress.rb:232:d41fb
--- Neutral failure ---
Original code was inserted unmutated. And the test did NOT PASS.
Your tests do not pass initially or you found a bug in mutant / unparser.
Subject AST:
s(:def, :needs_temp_themes_finished,
  s(:args),
  s(:begin,
    s(:if,
      s(:send,
        s(:send, nil, :themes), :blank?),
      s(:return), nil),
    s(:lvasgn, :active,
      s(:send,
        s(:send, nil, :active_themes), :size)),
    s(:lvasgn, :temp,
      s(:send, nil, :num_temp_themes)),
    s(:send, nil, :add_stats,
      s(:lvar, :active),
      s(:send,
        s(:lvar, :active), :+,
        s(:lvar, :temp)),
      s(:send,
        s(:const, nil, :I18n), :t,
        s(:str, "finish_temp_themes"),
        s(:hash,
          s(:pair,
            s(:sym, :temp),
            s(:lvar, :temp)))))))
Unparsed Source:
def needs_temp_themes_finished
  if themes.blank?
    return
  end
  active = active_themes.size
  temp = num_temp_themes
  add_stats(active, active + temp, I18n.t("finish_temp_themes", temp: temp))
end
-----------------------
- 2 @ runtime: 0.8842679999943357
  - rspec:0:./spec/lib/stage_progress/prepare_progress_spec.rb:22/PrepareProgress#determine_complete has calculate the progress of a virgin cycle
  - rspec:1:./spec/lib/stage_progress/prepare_progress_spec.rb:31/PrepareProgress#determine_complete has calculate the progress of a real cycle
Test Output:

Randomized with seed 51352

PrepareProgress
  #determine_complete
    has calculate the progress of a real cycle (FAILED - 1)

Failures:

  1) PrepareProgress#determine_complete has calculate the progress of a real cycle
     Failure/Error: assessment_grammar_recommendations.reorder(nil).distinct.pluck(:code)

     Errno::EBADF:
       Bad file descriptor @ fptr_finalize_flush - /Users/tj/.rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/associations/join_dependency.rb
     # ./app/lib/aa_stats.rb:55:in `points_needing_grammar_fixed'
     # ./app/lib/stage_progress/prepare_progress.rb:11:in `points_needing_grammar_fixed'
     # ./app/lib/stage_progress/prepare_progress.rb:110:in `needs_grammar_review'
     # ./app/lib/stage_progress/prepare_progress.rb:54:in `top_level_cycle_checks'
     # ./app/lib/stage_progress/prepare_progress.rb:38:in `determine_complete'
     # ./app/lib/stage_progress/stage_progress_calculator.rb:36:in `block in completeness'
     # ./app/lib/stage_progress/stage_progress_calculator.rb:34:in `each'
     # ./app/lib/stage_progress/stage_progress_calculator.rb:34:in `completeness'
     # ./spec/lib/stage_progress/prepare_progress_spec.rb:34:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:53:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:52:in `block (2 levels) in <top (required)>'
     # /Users/tj/.bundle/ruby/2.5.0/mutant-6d46f49bbd2f/lib/mutant/env.rb:87:in `block in run_mutation_tests'
     # /Users/tj/.bundle/ruby/2.5.0/mutant-6d46f49bbd2f/lib/mutant/isolation/fork.rb:171:in `call'
     # /Users/tj/.bundle/ruby/2.5.0/mutant-6d46f49bbd2f/lib/mutant/isolation/fork.rb:81:in `block in start_child'
     # /Users/tj/.bundle/ruby/2.5.0/mutant-6d46f49bbd2f/lib/mutant/isolation/fork.rb:80:in `fork'
     # /Users/tj/.bundle/ruby/2.5.0/mutant-6d46f49bbd2f/lib/mutant/isolation/fork.rb:80:in `start_child'
     # /Users/tj/.bundle/ruby/2.5.0/mutant-6d46f49bbd2f/lib/mutant/isolation/fork.rb:67:in `call'
     # /Users/tj/.bundle/ruby/2.5.0/mutant-6d46f49bbd2f/lib/mutant/isolation/fork.rb:191:in `block (2 levels) in call'
     # /Users/tj/.bundle/ruby/2.5.0/mutant-6d46f49bbd2f/lib/mutant/isolation/fork.rb:32:in `block in with'
     # /Users/tj/.bundle/ruby/2.5.0/mutant-6d46f49bbd2f/lib/mutant/isolation/fork.rb:31:in `pipe'
     # /Users/tj/.bundle/ruby/2.5.0/mutant-6d46f49bbd2f/lib/mutant/isolation/fork.rb:31:in `with'
     # /Users/tj/.bundle/ruby/2.5.0/mutant-6d46f49bbd2f/lib/mutant/isolation/fork.rb:190:in `block in call'
     # /Users/tj/.bundle/ruby/2.5.0/mutant-6d46f49bbd2f/lib/mutant/isolation/fork.rb:32:in `block in with'
     # /Users/tj/.bundle/ruby/2.5.0/mutant-6d46f49bbd2f/lib/mutant/isolation/fork.rb:31:in `pipe'
     # /Users/tj/.bundle/ruby/2.5.0/mutant-6d46f49bbd2f/lib/mutant/isolation/fork.rb:31:in `with'
     # /Users/tj/.bundle/ruby/2.5.0/mutant-6d46f49bbd2f/lib/mutant/isolation/fork.rb:189:in `call'
     # /Users/tj/.bundle/ruby/2.5.0/mutant-6d46f49bbd2f/lib/mutant/env.rb:81:in `run_mutation_tests'
     # /Users/tj/.bundle/ruby/2.5.0/mutant-6d46f49bbd2f/lib/mutant/env.rb:49:in `kill'
     # /Users/tj/.bundle/ruby/2.5.0/mutant-6d46f49bbd2f/lib/mutant/parallel/worker.rb:28:in `call'
     # /Users/tj/.bundle/ruby/2.5.0/mutant-6d46f49bbd2f/lib/mutant/parallel/worker.rb:28:in `block in call'
     # /Users/tj/.bundle/ruby/2.5.0/mutant-6d46f49bbd2f/lib/mutant/parallel/worker.rb:23:in `loop'
     # /Users/tj/.bundle/ruby/2.5.0/mutant-6d46f49bbd2f/lib/mutant/parallel/worker.rb:23:in `call'
     # ------------------
     # --- Caused by: ---
     # Errno::EBADF:
     #   Bad file descriptor @ io_fillbuf - fd:10 /Users/tj/.rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/associations/join_dependency.rb
     #   ./app/lib/aa_stats.rb:55:in `points_needing_grammar_fixed'

Finished in 0.86997 seconds (files took 16 minutes 22 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/lib/stage_progress/prepare_progress_spec.rb:31 # PrepareProgress#determine_complete has calculate the progress of a real cycle

Randomized with seed 51352```

**Comment by mbj** [comment]
@tjchambers This smells like a bug in your database adapter. Which one are you using?

https://github.com/brianmario/mysql2/issues/547

**Comment by tjchambers** [comment]
I am running the latest 0.5.2 version of mysql2 gem in -j1 configuration with a pool of 55.

I am running 2.5.3 of Ruby. 

However there is an interesting comment here:

https://fossies.org/linux/ruby/ChangeLog

 3622 r66104 | normal | 2018-11-30 20:44:21 +0900 (Fri, 30 Nov 2018) | 6 lines
 3623 
 3624 test/ruby/test_io.rb (test_recycled_fd_close): remove hacks
 3625 
 3626 I think I finally fixed the underlying bug in r65937
 3627 ("io.c (fptr_finalize_flush): close race leading to EBADF")
 3628 
 3629 I've run this test over 100000 times on a multicore system, now.

**Comment by mbj** [comment]
@tjchambers As mutant forks per mutation, and if an underlying library does not handle FDs correctly in that event it indeed can yield the behavior you reported.

Can you reproduce this under 2.6.1?

**Comment by tjchambers** [comment]
I do not know if I can run under 2.6.1 so I can only attempt that and see what happens. Unfortunately it may not be possible to bundle with 2.6.1. I will try WTP.

**Comment by mbj** [comment]
@tjchambers An alternative is to ensure no DB fd is inherited into the fork.

You could kill all connections to the DB once the app is loaded. Each killfork would than reconnect on a fresh FD.

**Comment by tjchambers** [comment]
tbh I do not know hardly anything about file descriptors. I am confused about the DB references in your comments above. I need to do more educational research.

**Comment by mbj** [comment]
@tjchambers NP, I can TLDR what I want you to try: 

To test my theory on how to workaround the issue without digging into FDs: Try to find a reference to the DB connection pool object, and instruct it to close all DB connections, after your app is fully loaded. Like in your spec helper.

This makes sure no DB connection is inherited into mutants environment, and each time a test of yours dos hit the DB AR will create a fresh connection.

This strategy may workaround the entire issue.

**Comment by tjchambers** [comment]
I was able to try 2.6.1.

- Loaded 2.6.1 and rebundled. Without any other alterations reran a failing class. It failed worse - 2 bad file descriptors reported in the console and one in the log. In addition a `marshal data too short`. 

The 2 errors indicated they were coming from bootsnap. And generally when I get the `marshal` error I clear out `/tmp/cache` - which btw had references to `bootsnap`.

Cleared out `/tmp/cache/` and reran. NO bad file descriptor errors. Normal mutation alive (killed 196 of 204). No console errors re: bad file descriptors either.

- reran again (without clearing /tmp/cache). Still no FD errors - same mutation results (196 out of 204 killed).

My inference from this is three fold:

- I should have cleared out the prior bootsnap info in `/tmp/cache` when changing Ruby versions. 
- That the issue with bad file descriptors is Ruby related under mutation runs
- That the issue with bad file descriptors is somehow broken in 2.5.3 of Ruby and addressed in 2.6.1

based on that I am going to rerun my suite of failed classes again now under 2.6.1 and gauge further results.

**Comment by mbj** [comment]
@tjchambers When you have a spare cycle please also try the method of not inheriting an active DB connection pool. Thank you for spending so much of your time on the issue.

I think we are observing several classes of problems, likely related to the environment mutant creates.

**Comment by tjchambers** [comment]
FWIW the class I have been using for testing does almost zero DB IO. it does 2 queries and then formats a graph and emails it. The email portion is stubbed. So that particular class - compared to many of mine - is on the far end of the "does not use DB" spectrum - it is readonly and does not alter the DB.

**Comment by tjchambers** [comment]
I reran the failed specs on 2.6.1 and 19 of the failed classes resolved themselves - no neutral failures. 4 of the remaining have bad file descriptor errors -  2 of those with 1 error, and 2 with 4+. So it did not resolve all but did resolve most. 

I am going to continue to research - I want to ensure they are reproducible and will give a try at changing the DB characteristics. The 4 that are still failing with EBADF issues are also heavy DB modifiers, so the DB impact is still potential. They are also 4 that have not been de-privatized. They have significant private methods that require outer specs - extensive specs - to kill mutations. SO they are not very targeted, making them also do a considerable amount of unnecessary activity. 

It is this type of info that informs me in terms of what I should spend time accelerating or refactoring, which is part of the beauty of using mutant for this process.

**Comment by mbj** [comment]
@tjchambers Mutant had a number of very relevant changes in the area:

* The child process handling was re-implemented, producing better error messages.
* We now have [coverage-criteria-configuration](https://github.com/mbj/mutant/blob/master/docs/configuration.md#coverage_criteria) that allows to tell mutant to consider abnormal situations as covered.

For the moment I've to assume this issue is solved, I'm happy to re-open once you got the chance to produce a report from a more recent mutant.
