### ISSUE TITLE
Feature request: license identifier

### ISSUE THREAD

**Issue by timoschilling** [mbj/mutant#957]
currently the licenses url is something like this:
```
https://duiweihdiuwehdiweuh@gem.mutant.dev
```
I would request somethiing like this:
```
https://companyname-oss:duiweihdiuwehdiweuh@gem.mutant.dev
https://companyname-com:duiweihdiuwehdiweuh@gem.mutant.dev
# or 
https://oss:duiweihdiuwehdiweuh@gem.mutant.dev
https://com:duiweihdiuwehdiweuh@gem.mutant.dev
```
That's makes it easier to deal with multiple licenses, explicit to divide your private and commercial license.

Maybe you can simply allow any string between `//` and `:`.

**Comment by mbj** [comment]
It needs to parse as a valid URL. So `oss:$key` is viable.

I think I'll go for `oss:` and `com:` as these do not disclose the company / person who has the account, while still making the propose more identifiable.

**Comment by mbj** [comment]
@timoschilling This was addressed via the latest mutant-manager deployment. The old format is still supported but to be considered deprectated.

Use `oss:` prefix (username) for opensource licenses, and `com:` for commercial licenses.
