### ISSUE TITLE
Trouble setting up OSS license in gem

### ISSUE THREAD

**Issue by tomdalling** [mbj/mutant#964]
I've added this to my Gemfile for [my gem](https://github.com/tomdalling/value_semantics):

```ruby
source "https://rubygems.org"

source 'https://oss:fLUos7k6c7Ak7zjhwbYphPJbwBk1Uuew@gem.mutant.dev' do
  gem 'mutant-license'
end

# Specify your gem's dependencies in the gemspec
gemspec
```

And when I run `bundle install` I get this output:

```txt
Fetching source index from https://gem.mutant.dev/

Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://gem.mutant.dev/
Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from https://gem.mutant.dev/
Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from https://gem.mutant.dev/
Could not fetch specs from https://gem.mutant.dev/
```

These may or may not be helpful:

```txt
$bundler --version
Bundler version 1.17.2
$ ruby --version
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
```

What am I doing wrong?

**Comment by mbj** [comment]
I think you are doing nothing wrong, I only implemented the subset of API endpoints in my license gem server I could get rubygems / bundler to hit on my testing.

For some reason bundler, in your case decided to fetch the full source index:

```
Fetching source index from https://gem.mutant.dev/
```

This is an endpoint I do not yet support. Can you do me the favor and re-run the `bundle install` with the `--verbose` flag here? I do want to learn on the circumstances when bundler tries to reduce to the "older" api endpoints.

**Comment by tomdalling** [comment]
Yep, sure. Here's the output: https://gist.github.com/tomdalling/fba3a33ed3ba56af3f6666cf5601fad4

**Comment by mbj** [comment]
@tomdalling Can you check your network? In the gist I exclusively see errors from `net-http` like:

* Gem::RemoteFetcher::FetchError: Errno::ECONNREFUSED: Failed to open TCP connection to gem.mutant.dev:443 (Connection refused - connect(2) for "gem.mutant.dev" port 443)
* Bundler::HTTPError: Network error while fetching https://oss@gem.mutant.dev/versions (connection refused: gem.mutant.dev:80)

Under the assumption that AWS ApiGateway / Lambda has high uptime and was not down at the time you tested: I suspect the issue may be some kind of intercepting proxy in your network.

You can check for this problem outside of bundler:

```
curl -i https://oss:fLUos7k6c7Ak7zjhwbYphPJbwBk1Uuew@gem.mutant.dev/versions
```

**Comment by tomdalling** [comment]
Yeah, I can't access any `.dev` domains, so something is wrong on my end. Probably [pow](https://pow.cx) or something like that. I'll look into it. Thanks.

**Comment by mbj** [comment]
`.dev` is now an official TLD, I recommend to follow this RFC for selecting a local TLD: https://tools.ietf.org/html/rfc6761

**Comment by tomdalling** [comment]
Pow already switched to using `.test` as the TLD a couple of years ago, so I'm not sure why it's still messing with the DNS resolver for `.dev` domains. I don't know if it's still being actively maintained.

**Comment by mbj** [comment]
kk, eventually the pow devs will decide to change the default to a reasonable domain.
