### ISSUE TITLE
Promote elsif cases

### ISSUE THREAD

**Issue by mbj** [mbj/mutant#968]
Original (not desugared):

```
if foo
  # do_a
elsif bar
  # do_b
else
  # do_c
end
```

mutation:

```
if bar
  # do_b
else
  # do_c
end
```

**Comment by dgollahon** [comment]
@mbj This already happens in master--I verified with by locally adding a your testcase to the meta and checking that the output is included. I can add additional test coverage if you want, but I'm pretty sure this happens naturally (or was specifically added at some point) and this issue can be closed.

**Comment by mbj** [comment]
@dgollahon yes it is, closing thanks for checking.
