### ISSUE TITLE
Suggestion: do not fail as evil if the mutation is between synonyms

### ISSUE THREAD

**Issue by drseg** [mbj/mutant#969]
Currently, mutant will throw up an evil failure if tests do not fail even when the mutation is from one synonym to another. For example, no reasonable test should fail if `array[0]` was mutated to `array.at(0)`, as these are identical statements, yet mutant will fail this as an evil.

I do not know if mutant has some handling of synonyms in general, but from this example, it is not yet complete. Perhaps this is too complex an example because there are some cases where `array.at()` and `array[]` would behave differently (ranges for example), but it would still be nice in the specific case of statements that are truly identical not to have a failure.

**Comment by mbj** [comment]
@drseg There is a semantic difference between:

* `Array#[]` 
* `Array#at`

The latter is a strict subset of the former in terms of semantics. `#[]` accepts more input.

Mutants mutation operators fall into 2 classes:

* Semantic reduction
* Orthogonal replacement.

`#[]` -> `#at` is a semantic reduction, as `#[]` accepts more input than `#at`. Unless you have a test case that shows the unique to `#[]` semantics are used: Mutant will report a semantic reduction to `#at[]` and unless you *need* the extra semantics of `#[]` you should probably change your code to `#at[]`.

An alive mutation can either represent:

* Unused semantics
* Missing test coverage

In this case mutant likely found unused semantics, you should remove from your code.

**Comment by mbj** [comment]
OT: Another way to understand that `#at` and `#[]` are not synonyms is to look at the parse tree:

```
bundle exec ruby-parse -e 'foo[bar]'
(index
  (send nil :foo)
  (send nil :bar))
(send
  (send nil :foo) :at
  (send nil :bar))
```

This AST is different, and when the AST is different there is a semantic difference. The ASTs primary propose is to be condensed semantics.

Now lets look at a true synonym:

```
bundle exec ruby-parse -e 'a && b'     
(and
  (send nil :a)
  (send nil :b))
bundle exec ruby-parse -e 'a and b'
(and
  (send nil :a)
  (send nil :b))
```

Mutant will never force you to turn an `&&` to an `and` (or vice versa) as it would never report such a mutation, as it would never generate such a mutation as they are the same at the AST level.

**Comment by drseg** [comment]
If I understand you correctly, you are saying that mutant would reduce `#[]` to` #at`, but would never try to do the opposite, i.e. substituting `#[]` for `#at`?

In that case, all is clear. Many thanks for the wonderful tool.

**Comment by mbj** [comment]
> mutant would reduce `#[]` to `#at`, but would never try to do the opposite, i.e. substituting `#[]` for `#at`?

Correct. Mutant only performs semantic reductions.

> Many thanks for the wonderful tool.

Thank you for the kind words.

Feel free to show up at our mutation testing slack channel for more discussions. Or open more issues. I like the chance to explain mutants concepts.
