### ISSUE TITLE
Silence warnings when running mutator

### ISSUE THREAD

**Issue by dkubb** [mbj/mutant#97]
This might seem at odds with @snusnu's #96 ticket, but I think we should silence warnings to STDOUT/STDERR in mutations; at least the warnings that ruby generates because an ivar isn't initialized, etc.

While I would love extra debug output, I would also like to see less extraneous information when running the mutations.

**Comment by mbj** [comment]
Actually mutant does silencing of warnings already for several releases. Closing this issue.
