### ISSUE TITLE
Neutral mutation failing - only on CI

### ISSUE THREAD

**Issue by szalansky** [mbj/mutant#976]
Hey @mbj, I asked you a question about this on twitter previously but failed to debug it myself.

I'm experiencing a mismatch in the results between local machine and CI, and unfortunately I'm getting failures in the latter. The failure is about neutral mutation:

```
--- Neutral failure ---
Original code was inserted unmutated. And the test did NOT PASS.
Your tests do not pass initially or you found a bug in mutant / unparser.
Subject AST:
s(:def, :execute,
  s(:args),
  s(:begin,
    s(:if,
      s(:send, nil, :template_path), nil,
      s(:return)),
    s(:send,
      s(:const, nil, :YAML), :load_file,
      s(:send, nil, :template_path))))
Unparsed Source:
def execute
  unless template_path
    return
  end
  YAML.load_file(template_path)
end
```

Local setup:
* MacOS 10.14.6 w/ Ruby 2.5.3 -> pass
* Docker (minideb/stretch-based w/ Ruby 2.5.3) -> pass

CI setup:
* Exactly same docker image running on Gitlab CI EE -> fail.

At worst I will move this method elsewhere but I'd still like to understand the cause.

Apart from that mutant has been absolutely stellar and helped me improve the codebase, and I wanted to say thank you for sharing it.

**Comment by mbj** [comment]
@szalansky Can you please post the test output, printed below the neutral error?

**Comment by szalansky** [comment]
@mbj sure thing, sorry about that!

```
-----------------------
Mutant configuration:
Matcher:         #<Mutant::Matcher::Config match_expressions: [KlassNameGoesHere]>
Integration:     Mutant::Integration::Rspec
Jobs:            8
Includes:        []
Requires:        ["./config/environment"]
Subjects:        3
Mutations:       269
Results:         12
Kills:           11
Alive:           1
Runtime:         1.04s
Killtime:        1.08s
Overhead:        -4.01%
Mutations/s:     11.54
Coverage:        91.67%
```

That's all I have. I get a success when running the tests using rspec.

**Comment by mbj** [comment]
@szalansky Chances you can try on more recent mutant? the 0.9 series is far more sensitive and prints far better information on these errors.

**Comment by mbj** [comment]
@szalansky I'm closing this for the moment, I need more information, especially the original code before mutation and the killfork output (it gets printed in latest versions).

For the moment there is not much I can do, and since the unparser re-write we have to assume your problem is fixed.
