### ISSUE TITLE
Add option for specs file pattern

### ISSUE THREAD

**Issue by Haelle** [mbj/mutant#997]
It would be nice to be able to run mutant against a bunch of specs instead of one "deducted" file. 

For instance:`bundle exec mutant --use rspec --specs **/*foo*_spec.rb Foo`
Would run "all" specs regarding Foo.

#### Why ?
My specs file are unit tests, and e2e tests are in another folder and so mutant detect many mutants that would be killed by e2e specs !

wdyt ?

**Comment by mbj** [comment]
@Haelle Mutant does not "deduct files". It runs the mutations against a test of tests selected from rspec metadata or minitest annotations.

What you want is explicit annotation of mutation subjects to tests. Or you want to configure the metadata so that mutants discovery picks up the right tests?

**Comment by Haelle** [comment]
I think explicit annotations to either add or replace all spec perimeter.

For a one shot mutation testing adding a dedicated metadata (like `mutant: true` or `mutant_spec: true`) would be ideal, like the `focus` option of RSpec

But for regular mutation testing something like `mutant_subjects: [Foo, Bar]` would be better but would pollute the specs...

I'm more interested in the first solution currently.

P.S: it would be nice to have a way to check which specs will be run also.

**Comment by mbj** [comment]
@Haelle this is actually implemented, you have:

```
mutant: true|false # individually de/selects examples.
mutant: 'SomeExpression*' # allows to overwrite the auto detection
```
